/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_operators_blas_l1.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_operators_blas_l1.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = ((NI) 1);
	{
		NI value;
		value = (NI)0;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (*a).len;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA4;
					i = i_2;
					value = (*a).data[(i)- 0];
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&result), value);
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	return result;
}

static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = product_k2YXWcJ5lNu24E2yfX7EKQvectorize((&(*t).shape));
	return result;
}

static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = (NI)((*a).len - ((NI) 1));
	return result;
}

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write((&(*t).shape));
		res = colontmp_;
		{
			while (1) {
				NI T12_;
				if (!(((NI) 0) <= res)) goto LA3;
				i = res;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				res -= ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NF* result;
	result = (NF*)0;
	result = ((NF*) ((&(*t).storage.Fdata->data[(*t).offset])));
	return result;
}

static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = (*t).shape.len;
	return result;
}

static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI* result;
	result = (NI*)0;
	result = (&(*a).data[(idx)- 0]);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, pluseq__k0y4rc9aHyhmsJBSS4FKm4g)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* b) {
	NI ompsize;
	ompsize = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&(*a)));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = likely((((NI) 0) < ompsize));
		if (!T3_) goto LA4_;
		{
			NI block_offset;
			NI block_size;
			block_offset = ((NI) 0);
			block_size = ompsize;
			{
				{
					NF* x;
					NF y;
					NIM_BOOL t1_contiguous;
					NIM_BOOL t2_contiguous;
					NF* t1data;
					NF* t2data;
					x = (NF*)0;
					y = (NF)0;
					t1_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&(*a)));
					t2_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write(b);
					t1data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&(*a)));
					t2data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write(b);
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = t1_contiguous;
						if (!(T11_)) goto LA12_;
						T11_ = t2_contiguous;
						LA12_: ;
						if (!T11_) goto LA13_;
						{
							NI i;
							NI colontmp_;
							NI i_2;
							i = (NI)0;
							colontmp_ = (NI)0;
							colontmp_ = (NI)(block_offset + block_size);
							i_2 = block_offset;
							{
								while (1) {
									if (!(i_2 < colontmp_)) goto LA17;
									i = i_2;
									x = (&t1data[(i)- 0]);
									y = t2data[(i)- 0];
									(*x) = ((NF)((*x)) + (NF)(y));
									i_2 += ((NI) 1);
								} LA17: ;
							}
						}
					}
					goto LA9_;
					LA13_: ;
					{
						NI t2_iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides;
						if (!t1_contiguous) goto LA19_;
						t2_iter_pos = ((NI) 0);
						{
							NI i_3;
							NI colontmp__2;
							NI i_4;
							i_3 = (NI)0;
							colontmp__2 = (NI)0;
							colontmp__2 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(b);
							i_4 = ((NI) 0);
							{
								while (1) {
									NI T24_;
									NI T25_;
									if (!(i_4 < colontmp__2)) goto LA23;
									i_3 = i_4;
									T24_ = (NI)0;
									T24_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).strides), i_3);
									T25_ = (NI)0;
									T25_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), i_3);
									t2_backstrides[(i_3)- 0] = (NI)(T24_ * (NI)(T25_ - ((NI) 1)));
									t2_coord[(i_3)- 0] = ((NI) 0);
									i_4 += ((NI) 1);
								} LA23: ;
							}
						}
						{
							NI z;
							if (!!((block_offset == ((NI) 0)))) goto LA28_;
							z = ((NI) 1);
							{
								NI i_5;
								NI colontmp__3;
								NI T31_;
								NI res;
								i_5 = (NI)0;
								colontmp__3 = (NI)0;
								T31_ = (NI)0;
								T31_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(b);
								colontmp__3 = (NI)(T31_ - ((NI) 1));
								res = colontmp__3;
								{
									while (1) {
										NI T34_;
										NI T35_;
										NI T36_;
										if (!(((NI) 0) <= res)) goto LA33;
										i_5 = res;
										T34_ = (NI)0;
										T34_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), i_5);
										t2_coord[(i_5)- 0] = (NI)((NI)(block_offset / z) % T34_);
										T35_ = (NI)0;
										T35_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).strides), i_5);
										t2_iter_pos += (NI)(t2_coord[(i_5)- 0] * T35_);
										T36_ = (NI)0;
										T36_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), i_5);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T36_);
										res -= ((NI) 1);
									} LA33: ;
								}
							}
						}
						LA28_: ;
						{
							NI i_6;
							NI colontmp__4;
							NI i_7;
							i_6 = (NI)0;
							colontmp__4 = (NI)0;
							colontmp__4 = (NI)(block_offset + block_size);
							i_7 = block_offset;
							{
								while (1) {
									if (!(i_7 < colontmp__4)) goto LA39;
									i_6 = i_7;
									x = (&t1data[(i_6)- 0]);
									y = t2data[(t2_iter_pos)- 0];
									(*x) = ((NF)((*x)) + (NF)(y));
									{
										NI k;
										NI colontmp__5;
										NI T41_;
										NI res_2;
										k = (NI)0;
										colontmp__5 = (NI)0;
										T41_ = (NI)0;
										T41_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(b);
										colontmp__5 = (NI)(T41_ - ((NI) 1));
										res_2 = colontmp__5;
										{
											while (1) {
												if (!(((NI) 0) <= res_2)) goto LA43;
												k = res_2;
												{
													NI T46_;
													NI T49_;
													T46_ = (NI)0;
													T46_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), k);
													if (!(t2_coord[(k)- 0] < (NI)(T46_ - ((NI) 1)))) goto LA47_;
													t2_coord[(k)- 0] += ((NI) 1);
													T49_ = (NI)0;
													T49_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).strides), k);
													t2_iter_pos += T49_;
													goto LA40;
												}
												goto LA44_;
												LA47_: ;
												{
													t2_coord[(k)- 0] = ((NI) 0);
													t2_iter_pos -= t2_backstrides[(k)- 0];
												}
												LA44_: ;
												res_2 -= ((NI) 1);
											} LA43: ;
										}
									} LA40: ;
									i_7 += ((NI) 1);
								} LA39: ;
							}
						}
					}
					goto LA9_;
					LA19_: ;
					{
						NI t1_iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides;
						if (!t2_contiguous) goto LA52_;
						t1_iter_pos = ((NI) 0);
						{
							NI i_8;
							NI colontmp__6;
							NI i_9;
							i_8 = (NI)0;
							colontmp__6 = (NI)0;
							colontmp__6 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*a)));
							i_9 = ((NI) 0);
							{
								while (1) {
									NI* T57_;
									NI* T58_;
									if (!(i_9 < colontmp__6)) goto LA56;
									i_8 = i_9;
									T57_ = (NI*)0;
									T57_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).strides), i_8);
									T58_ = (NI*)0;
									T58_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).shape), i_8);
									t1_backstrides[(i_8)- 0] = (NI)((*T57_) * (NI)((*T58_) - ((NI) 1)));
									t1_coord[(i_8)- 0] = ((NI) 0);
									i_9 += ((NI) 1);
								} LA56: ;
							}
						}
						{
							NI z_2;
							if (!!((block_offset == ((NI) 0)))) goto LA61_;
							z_2 = ((NI) 1);
							{
								NI i_10;
								NI colontmp__7;
								NI T64_;
								NI res_3;
								i_10 = (NI)0;
								colontmp__7 = (NI)0;
								T64_ = (NI)0;
								T64_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*a)));
								colontmp__7 = (NI)(T64_ - ((NI) 1));
								res_3 = colontmp__7;
								{
									while (1) {
										NI* T67_;
										NI* T68_;
										NI* T69_;
										if (!(((NI) 0) <= res_3)) goto LA66;
										i_10 = res_3;
										T67_ = (NI*)0;
										T67_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).shape), i_10);
										t1_coord[(i_10)- 0] = (NI)((NI)(block_offset / z_2) % (*T67_));
										T68_ = (NI*)0;
										T68_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).strides), i_10);
										t1_iter_pos += (NI)(t1_coord[(i_10)- 0] * (*T68_));
										T69_ = (NI*)0;
										T69_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).shape), i_10);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_2), (*T69_));
										res_3 -= ((NI) 1);
									} LA66: ;
								}
							}
						}
						LA61_: ;
						{
							NI i_11;
							NI colontmp__8;
							NI i_12;
							i_11 = (NI)0;
							colontmp__8 = (NI)0;
							colontmp__8 = (NI)(block_offset + block_size);
							i_12 = block_offset;
							{
								while (1) {
									if (!(i_12 < colontmp__8)) goto LA72;
									i_11 = i_12;
									x = (&t1data[(t1_iter_pos)- 0]);
									y = t2data[(i_11)- 0];
									(*x) = ((NF)((*x)) + (NF)(y));
									{
										NI k_2;
										NI colontmp__9;
										NI T74_;
										NI res_4;
										k_2 = (NI)0;
										colontmp__9 = (NI)0;
										T74_ = (NI)0;
										T74_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*a)));
										colontmp__9 = (NI)(T74_ - ((NI) 1));
										res_4 = colontmp__9;
										{
											while (1) {
												if (!(((NI) 0) <= res_4)) goto LA76;
												k_2 = res_4;
												{
													NI* T79_;
													NI* T82_;
													T79_ = (NI*)0;
													T79_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).shape), k_2);
													if (!(t1_coord[(k_2)- 0] < (NI)((*T79_) - ((NI) 1)))) goto LA80_;
													t1_coord[(k_2)- 0] += ((NI) 1);
													T82_ = (NI*)0;
													T82_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).strides), k_2);
													t1_iter_pos += (*T82_);
													goto LA73;
												}
												goto LA77_;
												LA80_: ;
												{
													t1_coord[(k_2)- 0] = ((NI) 0);
													t1_iter_pos -= t1_backstrides[(k_2)- 0];
												}
												LA77_: ;
												res_4 -= ((NI) 1);
											} LA76: ;
										}
									} LA73: ;
									i_12 += ((NI) 1);
								} LA72: ;
							}
						}
					}
					goto LA9_;
					LA52_: ;
					{
						NI t1_iter_pos_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides_2;
						NI t2_iter_pos_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides_2;
						t1_iter_pos_2 = ((NI) 0);
						{
							NI i_13;
							NI colontmp__10;
							NI i_14;
							i_13 = (NI)0;
							colontmp__10 = (NI)0;
							colontmp__10 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*a)));
							i_14 = ((NI) 0);
							{
								while (1) {
									NI* T88_;
									NI* T89_;
									if (!(i_14 < colontmp__10)) goto LA87;
									i_13 = i_14;
									T88_ = (NI*)0;
									T88_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).strides), i_13);
									T89_ = (NI*)0;
									T89_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).shape), i_13);
									t1_backstrides_2[(i_13)- 0] = (NI)((*T88_) * (NI)((*T89_) - ((NI) 1)));
									t1_coord_2[(i_13)- 0] = ((NI) 0);
									i_14 += ((NI) 1);
								} LA87: ;
							}
						}
						{
							NI z_3;
							if (!!((block_offset == ((NI) 0)))) goto LA92_;
							z_3 = ((NI) 1);
							{
								NI i_15;
								NI colontmp__11;
								NI T95_;
								NI res_5;
								i_15 = (NI)0;
								colontmp__11 = (NI)0;
								T95_ = (NI)0;
								T95_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*a)));
								colontmp__11 = (NI)(T95_ - ((NI) 1));
								res_5 = colontmp__11;
								{
									while (1) {
										NI* T98_;
										NI* T99_;
										NI* T100_;
										if (!(((NI) 0) <= res_5)) goto LA97;
										i_15 = res_5;
										T98_ = (NI*)0;
										T98_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).shape), i_15);
										t1_coord_2[(i_15)- 0] = (NI)((NI)(block_offset / z_3) % (*T98_));
										T99_ = (NI*)0;
										T99_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).strides), i_15);
										t1_iter_pos_2 += (NI)(t1_coord_2[(i_15)- 0] * (*T99_));
										T100_ = (NI*)0;
										T100_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).shape), i_15);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_3), (*T100_));
										res_5 -= ((NI) 1);
									} LA97: ;
								}
							}
						}
						LA92_: ;
						t2_iter_pos_2 = ((NI) 0);
						{
							NI i_16;
							NI colontmp__12;
							NI i_17;
							i_16 = (NI)0;
							colontmp__12 = (NI)0;
							colontmp__12 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(b);
							i_17 = ((NI) 0);
							{
								while (1) {
									NI T104_;
									NI T105_;
									if (!(i_17 < colontmp__12)) goto LA103;
									i_16 = i_17;
									T104_ = (NI)0;
									T104_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).strides), i_16);
									T105_ = (NI)0;
									T105_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), i_16);
									t2_backstrides_2[(i_16)- 0] = (NI)(T104_ * (NI)(T105_ - ((NI) 1)));
									t2_coord_2[(i_16)- 0] = ((NI) 0);
									i_17 += ((NI) 1);
								} LA103: ;
							}
						}
						{
							NI z_4;
							if (!!((block_offset == ((NI) 0)))) goto LA108_;
							z_4 = ((NI) 1);
							{
								NI i_18;
								NI colontmp__13;
								NI T111_;
								NI res_6;
								i_18 = (NI)0;
								colontmp__13 = (NI)0;
								T111_ = (NI)0;
								T111_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(b);
								colontmp__13 = (NI)(T111_ - ((NI) 1));
								res_6 = colontmp__13;
								{
									while (1) {
										NI T114_;
										NI T115_;
										NI T116_;
										if (!(((NI) 0) <= res_6)) goto LA113;
										i_18 = res_6;
										T114_ = (NI)0;
										T114_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), i_18);
										t2_coord_2[(i_18)- 0] = (NI)((NI)(block_offset / z_4) % T114_);
										T115_ = (NI)0;
										T115_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).strides), i_18);
										t2_iter_pos_2 += (NI)(t2_coord_2[(i_18)- 0] * T115_);
										T116_ = (NI)0;
										T116_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), i_18);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_4), T116_);
										res_6 -= ((NI) 1);
									} LA113: ;
								}
							}
						}
						LA108_: ;
						{
							NI i_19;
							NI colontmp__14;
							NI i_20;
							i_19 = (NI)0;
							colontmp__14 = (NI)0;
							colontmp__14 = (NI)(block_offset + block_size);
							i_20 = block_offset;
							{
								while (1) {
									if (!(i_20 < colontmp__14)) goto LA119;
									i_19 = i_20;
									x = (&t1data[(t1_iter_pos_2)- 0]);
									y = t2data[(t2_iter_pos_2)- 0];
									(*x) = ((NF)((*x)) + (NF)(y));
									{
										NI k_3;
										NI colontmp__15;
										NI T121_;
										NI res_7;
										k_3 = (NI)0;
										colontmp__15 = (NI)0;
										T121_ = (NI)0;
										T121_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*a)));
										colontmp__15 = (NI)(T121_ - ((NI) 1));
										res_7 = colontmp__15;
										{
											while (1) {
												if (!(((NI) 0) <= res_7)) goto LA123;
												k_3 = res_7;
												{
													NI* T126_;
													NI* T129_;
													T126_ = (NI*)0;
													T126_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).shape), k_3);
													if (!(t1_coord_2[(k_3)- 0] < (NI)((*T126_) - ((NI) 1)))) goto LA127_;
													t1_coord_2[(k_3)- 0] += ((NI) 1);
													T129_ = (NI*)0;
													T129_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*a).strides), k_3);
													t1_iter_pos_2 += (*T129_);
													goto LA120;
												}
												goto LA124_;
												LA127_: ;
												{
													t1_coord_2[(k_3)- 0] = ((NI) 0);
													t1_iter_pos_2 -= t1_backstrides_2[(k_3)- 0];
												}
												LA124_: ;
												res_7 -= ((NI) 1);
											} LA123: ;
										}
									} LA120: ;
									{
										NI k_4;
										NI colontmp__16;
										NI T132_;
										NI res_8;
										k_4 = (NI)0;
										colontmp__16 = (NI)0;
										T132_ = (NI)0;
										T132_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(b);
										colontmp__16 = (NI)(T132_ - ((NI) 1));
										res_8 = colontmp__16;
										{
											while (1) {
												if (!(((NI) 0) <= res_8)) goto LA134;
												k_4 = res_8;
												{
													NI T137_;
													NI T140_;
													T137_ = (NI)0;
													T137_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), k_4);
													if (!(t2_coord_2[(k_4)- 0] < (NI)(T137_ - ((NI) 1)))) goto LA138_;
													t2_coord_2[(k_4)- 0] += ((NI) 1);
													T140_ = (NI)0;
													T140_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).strides), k_4);
													t2_iter_pos_2 += T140_;
													goto LA131;
												}
												goto LA135_;
												LA138_: ;
												{
													t2_coord_2[(k_4)- 0] = ((NI) 0);
													t2_iter_pos_2 -= t2_backstrides_2[(k_4)- 0];
												}
												LA135_: ;
												res_8 -= ((NI) 1);
											} LA134: ;
										}
									} LA131: ;
									i_20 += ((NI) 1);
								} LA119: ;
							}
						}
					}
					LA9_: ;
				}
			}
		}
	}
	LA4_: ;
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_operators_blas_l1Init000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_operators_blas_l1DatInit000)(void) {
}

