/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_ufunc.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_ufunc.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef struct {
N_NIMCALL_PTR(NF, ClP_0) (NF i0, void* ClE_0);
void* ClE_0;
} tyProc_UJrbQLXc7rZUxKKxPs1nFQ;
typedef N_CLOSURE_PTR(NF, TM_fmNOU9bEeS1MaV0LB1jCoCA_2) (NF i0, void* ClE_0);
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
typedef NU8 tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, map_CFMytP25P7n0a9b8jusu4gA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyProc_UJrbQLXc7rZUxKKxPs1nFQ f, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
N_LIB_PRIVATE N_NIMCALL(NF, colonanonymous__uPhD05Ypmvhhxwfq54iAGw)(NF x);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
static N_INLINE(void, tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* out_shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout);
static N_INLINE(void, copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* s);
N_LIB_PRIVATE N_NIMCALL(void, shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* result);
static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting)(NI len);
N_NIMCALL(void*, nimNewSeqOfCap)(TNimType* typ, NI cap);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
extern TNimType NTI_urhjHEwA2NkLvIUFwuBxiQ_;
extern TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;

N_LIB_PRIVATE N_NIMCALL(NF, colonanonymous__uPhD05Ypmvhhxwfq54iAGw)(NF x) {
	NF result;
	result = (NF)0;
	result = x;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, astype_sLqpxHJRDZjSEKByu9cGYdA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	tyProc_UJrbQLXc7rZUxKKxPs1nFQ T1_;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ T2_;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	memset((void*)(&T1_), 0, sizeof(T1_));
	T1_.ClP_0 = ((TM_fmNOU9bEeS1MaV0LB1jCoCA_2) (colonanonymous__uPhD05Ypmvhhxwfq54iAGw)); T1_.ClE_0 = NIM_NIL;
	memset((void*)(&T2_), 0, sizeof(T2_));
	map_CFMytP25P7n0a9b8jusu4gA(t, T1_, (&T2_));
	(*Result).shape = T2_.shape;
	(*Result).strides = T2_.strides;
	(*Result).offset = T2_.offset;
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), T2_.storage.Fdata);
}

static N_INLINE(void, copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* s) {
	(*a).len = (*s).len;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (*s).len;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				(*a).data[(i)- 0] = (*s).data[(i)- 0];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

static N_INLINE(void, tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* out_shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout) {
	copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting((&(*result).shape), out_shape);
	shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A((&(*result).shape), layout, (&(*result).strides));
	(*result).offset = ((NI) 0);
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting)(NI len) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* result;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)nimNewSeqOfCap((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), len);
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) setLengthSeq(&(result)->Sup, sizeof(NF), len);
	return result;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = ((NI) 1);
	{
		NI value;
		value = (NI)0;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (*a).len;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA4;
					i = i_2;
					value = (*a).data[(i)- 0];
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&result), value);
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	return result;
}

static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = product_k2YXWcJ5lNu24E2yfX7EKQvectorize((&(*t).shape));
	return result;
}

static N_INLINE(void, newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NI T1_;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting(shape, Result, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101));
	T1_ = (NI)0;
	T1_ = size_9c9bGcb6H7uf0KFeicXmH40Avectorize(Result);
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting(((NI) (T1_))));
}

static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NF* result;
	result = (NF*)0;
	result = ((NF*) ((&(*t).storage.Fdata->data[(*t).offset])));
	return result;
}

static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = (NI)((*a).len - ((NI) 1));
	return result;
}

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write((&(*t).shape));
		res = colontmp_;
		{
			while (1) {
				NI T12_;
				if (!(((NI) 0) <= res)) goto LA3;
				i = res;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				res -= ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = (*t).shape.len;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, sqrt_wsKZGSC9ahwRyR9cTg8Mt1Fw)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ z;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ dest;
	NF* __restrict__ data;
	NI ompsize;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	memset((void*)(&z), 0, sizeof(z));
	z.shape = (*t).shape;
	z.strides = (*t).strides;
	z.offset = (*t).offset;
	z.storage.Fdata = (*t).storage.Fdata;
	memset((void*)(&dest), 0, sizeof(dest));
	newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting((&z.shape), (&dest));
	data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&dest));
	ompsize = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&dest));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = likely((((NI) 0) < ompsize));
		if (!T3_) goto LA4_;
		{
			NI block_offset;
			NI block_size;
			block_offset = ((NI) 0);
			block_size = ompsize;
			{
				{
					NI i;
					NF x;
					NF* data_2;
					i = (NI)0;
					x = (NF)0;
					data_2 = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&z));
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&z));
						if (!T11_) goto LA12_;
						{
							NI i_2;
							NI colontmp_;
							NI i_3;
							i_2 = (NI)0;
							colontmp_ = (NI)0;
							colontmp_ = (NI)(block_offset + block_size);
							i_3 = block_offset;
							{
								while (1) {
									if (!(i_3 < colontmp_)) goto LA16;
									i_2 = i_3;
									i = i_2;
									x = data_2[(i_2)- 0];
									data[(i)- 0] = sqrt(x);
									i_3 += ((NI) 1);
								} LA16: ;
							}
						}
					}
					goto LA9_;
					LA12_: ;
					{
						NI iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw backstrides;
						iter_pos = ((NI) 0);
						{
							NI i_4;
							NI colontmp__2;
							NI i_5;
							i_4 = (NI)0;
							colontmp__2 = (NI)0;
							colontmp__2 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z));
							i_5 = ((NI) 0);
							{
								while (1) {
									NI T21_;
									NI T22_;
									if (!(i_5 < colontmp__2)) goto LA20;
									i_4 = i_5;
									T21_ = (NI)0;
									T21_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.strides), i_4);
									T22_ = (NI)0;
									T22_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), i_4);
									backstrides[(i_4)- 0] = (NI)(T21_ * (NI)(T22_ - ((NI) 1)));
									coord[(i_4)- 0] = ((NI) 0);
									i_5 += ((NI) 1);
								} LA20: ;
							}
						}
						{
							NI z_2;
							if (!!((block_offset == ((NI) 0)))) goto LA25_;
							z_2 = ((NI) 1);
							{
								NI i_6;
								NI colontmp__3;
								NI T28_;
								NI res;
								i_6 = (NI)0;
								colontmp__3 = (NI)0;
								T28_ = (NI)0;
								T28_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z));
								colontmp__3 = (NI)(T28_ - ((NI) 1));
								res = colontmp__3;
								{
									while (1) {
										NI T31_;
										NI T32_;
										NI T33_;
										if (!(((NI) 0) <= res)) goto LA30;
										i_6 = res;
										T31_ = (NI)0;
										T31_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), i_6);
										coord[(i_6)- 0] = (NI)((NI)(block_offset / z_2) % T31_);
										T32_ = (NI)0;
										T32_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.strides), i_6);
										iter_pos += (NI)(coord[(i_6)- 0] * T32_);
										T33_ = (NI)0;
										T33_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), i_6);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_2), T33_);
										res -= ((NI) 1);
									} LA30: ;
								}
							}
						}
						LA25_: ;
						{
							NI i_7;
							NI colontmp__4;
							NI i_8;
							i_7 = (NI)0;
							colontmp__4 = (NI)0;
							colontmp__4 = (NI)(block_offset + block_size);
							i_8 = block_offset;
							{
								while (1) {
									if (!(i_8 < colontmp__4)) goto LA36;
									i_7 = i_8;
									i = i_7;
									x = data_2[(iter_pos)- 0];
									data[(i)- 0] = sqrt(x);
									{
										NI k;
										NI colontmp__5;
										NI T38_;
										NI res_2;
										k = (NI)0;
										colontmp__5 = (NI)0;
										T38_ = (NI)0;
										T38_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z));
										colontmp__5 = (NI)(T38_ - ((NI) 1));
										res_2 = colontmp__5;
										{
											while (1) {
												if (!(((NI) 0) <= res_2)) goto LA40;
												k = res_2;
												{
													NI T43_;
													NI T46_;
													T43_ = (NI)0;
													T43_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), k);
													if (!(coord[(k)- 0] < (NI)(T43_ - ((NI) 1)))) goto LA44_;
													coord[(k)- 0] += ((NI) 1);
													T46_ = (NI)0;
													T46_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.strides), k);
													iter_pos += T46_;
													goto LA37;
												}
												goto LA41_;
												LA44_: ;
												{
													coord[(k)- 0] = ((NI) 0);
													iter_pos -= backstrides[(k)- 0];
												}
												LA41_: ;
												res_2 -= ((NI) 1);
											} LA40: ;
										}
									} LA37: ;
									i_8 += ((NI) 1);
								} LA36: ;
							}
						}
					}
					LA9_: ;
				}
			}
		}
	}
	LA4_: ;
	(*Result).shape = dest.shape;
	(*Result).strides = dest.strides;
	(*Result).offset = dest.offset;
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), dest.storage.Fdata);
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_ufuncInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_ufuncDatInit000)(void) {
}

