/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_operators_broadcasted.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_operators_broadcasted.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple_ZqtwwojkKZ9bCA58nE5quMA tyTuple_ZqtwwojkKZ9bCA58nE5quMA;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
struct tyTuple_ZqtwwojkKZ9bCA58nE5quMA {
tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ Field0;
tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ Field1;
};
typedef NU8 tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, broadcast2_9cisCuLqWVGwqHwLLd3eV5A)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* b, tyTuple_ZqtwwojkKZ9bCA58nE5quMA* Result);
static N_INLINE(void, newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
static N_INLINE(void, tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* out_shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout);
static N_INLINE(void, copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* s);
N_LIB_PRIVATE N_NIMCALL(void, shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* result);
static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting)(NI len);
N_NIMCALL(void*, nimNewSeqOfCap)(TNimType* typ, NI cap);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
extern TNimType NTI_urhjHEwA2NkLvIUFwuBxiQ_;
extern TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;

static N_INLINE(void, copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* s) {
	(*a).len = (*s).len;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (*s).len;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				(*a).data[(i)- 0] = (*s).data[(i)- 0];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

static N_INLINE(void, tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* out_shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout) {
	copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting((&(*result).shape), out_shape);
	shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A((&(*result).shape), layout, (&(*result).strides));
	(*result).offset = ((NI) 0);
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting)(NI len) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* result;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)nimNewSeqOfCap((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), len);
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) setLengthSeq(&(result)->Sup, sizeof(NF), len);
	return result;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = ((NI) 1);
	{
		NI value;
		value = (NI)0;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (*a).len;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA4;
					i = i_2;
					value = (*a).data[(i)- 0];
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&result), value);
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	return result;
}

static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = product_k2YXWcJ5lNu24E2yfX7EKQvectorize((&(*t).shape));
	return result;
}

static N_INLINE(void, newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NI T1_;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting(shape, Result, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101));
	T1_ = (NI)0;
	T1_ = size_9c9bGcb6H7uf0KFeicXmH40Avectorize(Result);
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting(((NI) (T1_))));
}

static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NF* result;
	result = (NF*)0;
	result = ((NF*) ((&(*t).storage.Fdata->data[(*t).offset])));
	return result;
}

static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = (NI)((*a).len - ((NI) 1));
	return result;
}

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write((&(*t).shape));
		res = colontmp_;
		{
			while (1) {
				NI T12_;
				if (!(((NI) 0) <= res)) goto LA3;
				i = res;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				res -= ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = (*t).shape.len;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, dotslash__9aM1bLZKdt6TM6yy2moV9cwg)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* b, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	tyTuple_ZqtwwojkKZ9bCA58nE5quMA T1_;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tmp_a;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tmp_b;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ z1;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ z2;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ dest;
	NF* __restrict__ data;
	NI ompsize;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	memset((void*)(&T1_), 0, sizeof(T1_));
	broadcast2_9cisCuLqWVGwqHwLLd3eV5A(a, b, (&T1_));
	memset((void*)(&tmp_a), 0, sizeof(tmp_a));
	tmp_a.shape = T1_.Field0.shape;
	tmp_a.strides = T1_.Field0.strides;
	tmp_a.offset = T1_.Field0.offset;
	tmp_a.storage.Fdata = T1_.Field0.storage.Fdata;
	memset((void*)(&tmp_b), 0, sizeof(tmp_b));
	tmp_b.shape = T1_.Field1.shape;
	tmp_b.strides = T1_.Field1.strides;
	tmp_b.offset = T1_.Field1.offset;
	tmp_b.storage.Fdata = T1_.Field1.storage.Fdata;
	memset((void*)(&z1), 0, sizeof(z1));
	z1.shape = tmp_a.shape;
	z1.strides = tmp_a.strides;
	z1.offset = tmp_a.offset;
	z1.storage.Fdata = tmp_a.storage.Fdata;
	memset((void*)(&z2), 0, sizeof(z2));
	z2.shape = tmp_b.shape;
	z2.strides = tmp_b.strides;
	z2.offset = tmp_b.offset;
	z2.storage.Fdata = tmp_b.storage.Fdata;
	memset((void*)(&dest), 0, sizeof(dest));
	newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting((&z1.shape), (&dest));
	data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&dest));
	ompsize = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&z1));
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = likely((((NI) 0) < ompsize));
		if (!T4_) goto LA5_;
		{
			NI block_offset;
			NI block_size;
			block_offset = ((NI) 0);
			block_size = ompsize;
			{
				{
					NI i;
					NF x;
					NF y;
					NIM_BOOL t1_contiguous;
					NIM_BOOL t2_contiguous;
					NF* t1data;
					NF* t2data;
					i = (NI)0;
					x = (NF)0;
					y = (NF)0;
					t1_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&z1));
					t2_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&z2));
					t1data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&z1));
					t2data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&z2));
					{
						NIM_BOOL T12_;
						T12_ = (NIM_BOOL)0;
						T12_ = t1_contiguous;
						if (!(T12_)) goto LA13_;
						T12_ = t2_contiguous;
						LA13_: ;
						if (!T12_) goto LA14_;
						{
							NI i_2;
							NI colontmp_;
							NI i_3;
							i_2 = (NI)0;
							colontmp_ = (NI)0;
							colontmp_ = (NI)(block_offset + block_size);
							i_3 = block_offset;
							{
								while (1) {
									if (!(i_3 < colontmp_)) goto LA18;
									i_2 = i_3;
									i = i_2;
									x = t1data[(i_2)- 0];
									y = t2data[(i_2)- 0];
									data[(i)- 0] = ((NF)(x) / (NF)(y));
									i_3 += ((NI) 1);
								} LA18: ;
							}
						}
					}
					goto LA10_;
					LA14_: ;
					{
						NI t2_iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides;
						if (!t1_contiguous) goto LA20_;
						t2_iter_pos = ((NI) 0);
						{
							NI i_4;
							NI colontmp__2;
							NI i_5;
							i_4 = (NI)0;
							colontmp__2 = (NI)0;
							colontmp__2 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z2));
							i_5 = ((NI) 0);
							{
								while (1) {
									NI T25_;
									NI T26_;
									if (!(i_5 < colontmp__2)) goto LA24;
									i_4 = i_5;
									T25_ = (NI)0;
									T25_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.strides), i_4);
									T26_ = (NI)0;
									T26_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.shape), i_4);
									t2_backstrides[(i_4)- 0] = (NI)(T25_ * (NI)(T26_ - ((NI) 1)));
									t2_coord[(i_4)- 0] = ((NI) 0);
									i_5 += ((NI) 1);
								} LA24: ;
							}
						}
						{
							NI z;
							if (!!((block_offset == ((NI) 0)))) goto LA29_;
							z = ((NI) 1);
							{
								NI i_6;
								NI colontmp__3;
								NI T32_;
								NI res;
								i_6 = (NI)0;
								colontmp__3 = (NI)0;
								T32_ = (NI)0;
								T32_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z2));
								colontmp__3 = (NI)(T32_ - ((NI) 1));
								res = colontmp__3;
								{
									while (1) {
										NI T35_;
										NI T36_;
										NI T37_;
										if (!(((NI) 0) <= res)) goto LA34;
										i_6 = res;
										T35_ = (NI)0;
										T35_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.shape), i_6);
										t2_coord[(i_6)- 0] = (NI)((NI)(block_offset / z) % T35_);
										T36_ = (NI)0;
										T36_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.strides), i_6);
										t2_iter_pos += (NI)(t2_coord[(i_6)- 0] * T36_);
										T37_ = (NI)0;
										T37_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.shape), i_6);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T37_);
										res -= ((NI) 1);
									} LA34: ;
								}
							}
						}
						LA29_: ;
						{
							NI i_7;
							NI colontmp__4;
							NI i_8;
							i_7 = (NI)0;
							colontmp__4 = (NI)0;
							colontmp__4 = (NI)(block_offset + block_size);
							i_8 = block_offset;
							{
								while (1) {
									if (!(i_8 < colontmp__4)) goto LA40;
									i_7 = i_8;
									i = i_7;
									x = t1data[(i_7)- 0];
									y = t2data[(t2_iter_pos)- 0];
									data[(i)- 0] = ((NF)(x) / (NF)(y));
									{
										NI k;
										NI colontmp__5;
										NI T42_;
										NI res_2;
										k = (NI)0;
										colontmp__5 = (NI)0;
										T42_ = (NI)0;
										T42_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z2));
										colontmp__5 = (NI)(T42_ - ((NI) 1));
										res_2 = colontmp__5;
										{
											while (1) {
												if (!(((NI) 0) <= res_2)) goto LA44;
												k = res_2;
												{
													NI T47_;
													NI T50_;
													T47_ = (NI)0;
													T47_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.shape), k);
													if (!(t2_coord[(k)- 0] < (NI)(T47_ - ((NI) 1)))) goto LA48_;
													t2_coord[(k)- 0] += ((NI) 1);
													T50_ = (NI)0;
													T50_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.strides), k);
													t2_iter_pos += T50_;
													goto LA41;
												}
												goto LA45_;
												LA48_: ;
												{
													t2_coord[(k)- 0] = ((NI) 0);
													t2_iter_pos -= t2_backstrides[(k)- 0];
												}
												LA45_: ;
												res_2 -= ((NI) 1);
											} LA44: ;
										}
									} LA41: ;
									i_8 += ((NI) 1);
								} LA40: ;
							}
						}
					}
					goto LA10_;
					LA20_: ;
					{
						NI t1_iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides;
						if (!t2_contiguous) goto LA53_;
						t1_iter_pos = ((NI) 0);
						{
							NI i_9;
							NI colontmp__6;
							NI i_10;
							i_9 = (NI)0;
							colontmp__6 = (NI)0;
							colontmp__6 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z1));
							i_10 = ((NI) 0);
							{
								while (1) {
									NI T58_;
									NI T59_;
									if (!(i_10 < colontmp__6)) goto LA57;
									i_9 = i_10;
									T58_ = (NI)0;
									T58_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.strides), i_9);
									T59_ = (NI)0;
									T59_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.shape), i_9);
									t1_backstrides[(i_9)- 0] = (NI)(T58_ * (NI)(T59_ - ((NI) 1)));
									t1_coord[(i_9)- 0] = ((NI) 0);
									i_10 += ((NI) 1);
								} LA57: ;
							}
						}
						{
							NI z_2;
							if (!!((block_offset == ((NI) 0)))) goto LA62_;
							z_2 = ((NI) 1);
							{
								NI i_11;
								NI colontmp__7;
								NI T65_;
								NI res_3;
								i_11 = (NI)0;
								colontmp__7 = (NI)0;
								T65_ = (NI)0;
								T65_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z1));
								colontmp__7 = (NI)(T65_ - ((NI) 1));
								res_3 = colontmp__7;
								{
									while (1) {
										NI T68_;
										NI T69_;
										NI T70_;
										if (!(((NI) 0) <= res_3)) goto LA67;
										i_11 = res_3;
										T68_ = (NI)0;
										T68_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.shape), i_11);
										t1_coord[(i_11)- 0] = (NI)((NI)(block_offset / z_2) % T68_);
										T69_ = (NI)0;
										T69_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.strides), i_11);
										t1_iter_pos += (NI)(t1_coord[(i_11)- 0] * T69_);
										T70_ = (NI)0;
										T70_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.shape), i_11);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_2), T70_);
										res_3 -= ((NI) 1);
									} LA67: ;
								}
							}
						}
						LA62_: ;
						{
							NI i_12;
							NI colontmp__8;
							NI i_13;
							i_12 = (NI)0;
							colontmp__8 = (NI)0;
							colontmp__8 = (NI)(block_offset + block_size);
							i_13 = block_offset;
							{
								while (1) {
									if (!(i_13 < colontmp__8)) goto LA73;
									i_12 = i_13;
									i = i_12;
									x = t1data[(t1_iter_pos)- 0];
									y = t2data[(i_12)- 0];
									data[(i)- 0] = ((NF)(x) / (NF)(y));
									{
										NI k_2;
										NI colontmp__9;
										NI T75_;
										NI res_4;
										k_2 = (NI)0;
										colontmp__9 = (NI)0;
										T75_ = (NI)0;
										T75_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z1));
										colontmp__9 = (NI)(T75_ - ((NI) 1));
										res_4 = colontmp__9;
										{
											while (1) {
												if (!(((NI) 0) <= res_4)) goto LA77;
												k_2 = res_4;
												{
													NI T80_;
													NI T83_;
													T80_ = (NI)0;
													T80_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.shape), k_2);
													if (!(t1_coord[(k_2)- 0] < (NI)(T80_ - ((NI) 1)))) goto LA81_;
													t1_coord[(k_2)- 0] += ((NI) 1);
													T83_ = (NI)0;
													T83_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.strides), k_2);
													t1_iter_pos += T83_;
													goto LA74;
												}
												goto LA78_;
												LA81_: ;
												{
													t1_coord[(k_2)- 0] = ((NI) 0);
													t1_iter_pos -= t1_backstrides[(k_2)- 0];
												}
												LA78_: ;
												res_4 -= ((NI) 1);
											} LA77: ;
										}
									} LA74: ;
									i_13 += ((NI) 1);
								} LA73: ;
							}
						}
					}
					goto LA10_;
					LA53_: ;
					{
						NI t1_iter_pos_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides_2;
						NI t2_iter_pos_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides_2;
						t1_iter_pos_2 = ((NI) 0);
						{
							NI i_14;
							NI colontmp__10;
							NI i_15;
							i_14 = (NI)0;
							colontmp__10 = (NI)0;
							colontmp__10 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z1));
							i_15 = ((NI) 0);
							{
								while (1) {
									NI T89_;
									NI T90_;
									if (!(i_15 < colontmp__10)) goto LA88;
									i_14 = i_15;
									T89_ = (NI)0;
									T89_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.strides), i_14);
									T90_ = (NI)0;
									T90_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.shape), i_14);
									t1_backstrides_2[(i_14)- 0] = (NI)(T89_ * (NI)(T90_ - ((NI) 1)));
									t1_coord_2[(i_14)- 0] = ((NI) 0);
									i_15 += ((NI) 1);
								} LA88: ;
							}
						}
						{
							NI z_3;
							if (!!((block_offset == ((NI) 0)))) goto LA93_;
							z_3 = ((NI) 1);
							{
								NI i_16;
								NI colontmp__11;
								NI T96_;
								NI res_5;
								i_16 = (NI)0;
								colontmp__11 = (NI)0;
								T96_ = (NI)0;
								T96_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z1));
								colontmp__11 = (NI)(T96_ - ((NI) 1));
								res_5 = colontmp__11;
								{
									while (1) {
										NI T99_;
										NI T100_;
										NI T101_;
										if (!(((NI) 0) <= res_5)) goto LA98;
										i_16 = res_5;
										T99_ = (NI)0;
										T99_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.shape), i_16);
										t1_coord_2[(i_16)- 0] = (NI)((NI)(block_offset / z_3) % T99_);
										T100_ = (NI)0;
										T100_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.strides), i_16);
										t1_iter_pos_2 += (NI)(t1_coord_2[(i_16)- 0] * T100_);
										T101_ = (NI)0;
										T101_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.shape), i_16);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_3), T101_);
										res_5 -= ((NI) 1);
									} LA98: ;
								}
							}
						}
						LA93_: ;
						t2_iter_pos_2 = ((NI) 0);
						{
							NI i_17;
							NI colontmp__12;
							NI i_18;
							i_17 = (NI)0;
							colontmp__12 = (NI)0;
							colontmp__12 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z2));
							i_18 = ((NI) 0);
							{
								while (1) {
									NI T105_;
									NI T106_;
									if (!(i_18 < colontmp__12)) goto LA104;
									i_17 = i_18;
									T105_ = (NI)0;
									T105_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.strides), i_17);
									T106_ = (NI)0;
									T106_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.shape), i_17);
									t2_backstrides_2[(i_17)- 0] = (NI)(T105_ * (NI)(T106_ - ((NI) 1)));
									t2_coord_2[(i_17)- 0] = ((NI) 0);
									i_18 += ((NI) 1);
								} LA104: ;
							}
						}
						{
							NI z_4;
							if (!!((block_offset == ((NI) 0)))) goto LA109_;
							z_4 = ((NI) 1);
							{
								NI i_19;
								NI colontmp__13;
								NI T112_;
								NI res_6;
								i_19 = (NI)0;
								colontmp__13 = (NI)0;
								T112_ = (NI)0;
								T112_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z2));
								colontmp__13 = (NI)(T112_ - ((NI) 1));
								res_6 = colontmp__13;
								{
									while (1) {
										NI T115_;
										NI T116_;
										NI T117_;
										if (!(((NI) 0) <= res_6)) goto LA114;
										i_19 = res_6;
										T115_ = (NI)0;
										T115_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.shape), i_19);
										t2_coord_2[(i_19)- 0] = (NI)((NI)(block_offset / z_4) % T115_);
										T116_ = (NI)0;
										T116_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.strides), i_19);
										t2_iter_pos_2 += (NI)(t2_coord_2[(i_19)- 0] * T116_);
										T117_ = (NI)0;
										T117_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.shape), i_19);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_4), T117_);
										res_6 -= ((NI) 1);
									} LA114: ;
								}
							}
						}
						LA109_: ;
						{
							NI i_20;
							NI colontmp__14;
							NI i_21;
							i_20 = (NI)0;
							colontmp__14 = (NI)0;
							colontmp__14 = (NI)(block_offset + block_size);
							i_21 = block_offset;
							{
								while (1) {
									if (!(i_21 < colontmp__14)) goto LA120;
									i_20 = i_21;
									i = i_20;
									x = t1data[(t1_iter_pos_2)- 0];
									y = t2data[(t2_iter_pos_2)- 0];
									data[(i)- 0] = ((NF)(x) / (NF)(y));
									{
										NI k_3;
										NI colontmp__15;
										NI T122_;
										NI res_7;
										k_3 = (NI)0;
										colontmp__15 = (NI)0;
										T122_ = (NI)0;
										T122_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z1));
										colontmp__15 = (NI)(T122_ - ((NI) 1));
										res_7 = colontmp__15;
										{
											while (1) {
												if (!(((NI) 0) <= res_7)) goto LA124;
												k_3 = res_7;
												{
													NI T127_;
													NI T130_;
													T127_ = (NI)0;
													T127_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.shape), k_3);
													if (!(t1_coord_2[(k_3)- 0] < (NI)(T127_ - ((NI) 1)))) goto LA128_;
													t1_coord_2[(k_3)- 0] += ((NI) 1);
													T130_ = (NI)0;
													T130_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z1.strides), k_3);
													t1_iter_pos_2 += T130_;
													goto LA121;
												}
												goto LA125_;
												LA128_: ;
												{
													t1_coord_2[(k_3)- 0] = ((NI) 0);
													t1_iter_pos_2 -= t1_backstrides_2[(k_3)- 0];
												}
												LA125_: ;
												res_7 -= ((NI) 1);
											} LA124: ;
										}
									} LA121: ;
									{
										NI k_4;
										NI colontmp__16;
										NI T133_;
										NI res_8;
										k_4 = (NI)0;
										colontmp__16 = (NI)0;
										T133_ = (NI)0;
										T133_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z2));
										colontmp__16 = (NI)(T133_ - ((NI) 1));
										res_8 = colontmp__16;
										{
											while (1) {
												if (!(((NI) 0) <= res_8)) goto LA135;
												k_4 = res_8;
												{
													NI T138_;
													NI T141_;
													T138_ = (NI)0;
													T138_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.shape), k_4);
													if (!(t2_coord_2[(k_4)- 0] < (NI)(T138_ - ((NI) 1)))) goto LA139_;
													t2_coord_2[(k_4)- 0] += ((NI) 1);
													T141_ = (NI)0;
													T141_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z2.strides), k_4);
													t2_iter_pos_2 += T141_;
													goto LA132;
												}
												goto LA136_;
												LA139_: ;
												{
													t2_coord_2[(k_4)- 0] = ((NI) 0);
													t2_iter_pos_2 -= t2_backstrides_2[(k_4)- 0];
												}
												LA136_: ;
												res_8 -= ((NI) 1);
											} LA135: ;
										}
									} LA132: ;
									i_21 += ((NI) 1);
								} LA120: ;
							}
						}
					}
					LA10_: ;
				}
			}
		}
	}
	LA5_: ;
	(*Result).shape = dest.shape;
	(*Result).strides = dest.strides;
	(*Result).offset = dest.offset;
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), dest.storage.Fdata);
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_operators_broadcastedInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_operators_broadcastedDatInit000)(void) {
}

