/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_p_operator_blas_l2l3.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_p_operator_blas_l2l3.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
typedef NU8 tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg;
typedef NU8 tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg;
typedef N_CDECL_PTR(void, tyProc_IQPoQu8ZvVJvD9cQ6uVbH7g) (tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg ORDER, tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg TRANSA, tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg TRANSB, NI M, NI N, NI K, NF ALPHA, NF* A, NI LDA, NF* B, NI LDB, NF BETA, NF* C, NI LDC);
typedef N_CDECL_PTR(void, tyProc_egI5LaZetLEHtClnwDYycQ) (tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg ORDER, tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg TRANS, NI M, NI N, NF ALPHA, NF* A, NI LDA, NF* X, NI INCX, NF BETA, NF* Y, NI INCY);
struct TGenericSeq {
NI len;
NI reserved;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
N_LIB_PRIVATE N_NIMCALL(void, asContiguous_3BZwdaXStdH0qceZAOttRw)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, NIM_BOOL force, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
static N_INLINE(NF*, get_offset_ptr_7j9bbv7iiFutQHSe5SiqO9bAp_operator_blas_l2l3)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
extern tyProc_IQPoQu8ZvVJvD9cQ6uVbH7g Dl_281962_;
extern tyProc_egI5LaZetLEHtClnwDYycQ Dl_281926_;

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = (NI)((*a).len - ((NI) 1));
	return result;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write((&(*t).shape));
		res = colontmp_;
		{
			while (1) {
				NI T12_;
				if (!(((NI) 0) <= res)) goto LA3;
				i = res;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				res -= ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NF*, get_offset_ptr_7j9bbv7iiFutQHSe5SiqO9bAp_operator_blas_l2l3)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NF* result;
	result = (NF*)0;
	result = (&(*t).storage.Fdata->data[(*t).offset]);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, blasMM_C_eq_aAB_p_bC_ot3l15VXXZwPZ2GQHw7CHA)(NF alpha, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* b, NF beta, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* c) {
	NI M;
	NI K;
	NI N;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ cont_A;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ T1_;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ cont_B;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ T2_;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ c_2;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ T3_;
	NIM_BOOL cont_A_is_rowMajor;
	NIM_BOOL cont_B_is_rowMajor;
	NIM_BOOL c_is_rowMajor;
	tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg transpose_A;
	NI lda;
	tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg transpose_B;
	NI ldb;
	tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg order_C;
	NI ldc;
	NF* T34_;
	NF* T35_;
	NF* T36_;
	M = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*a).shape), ((NI) 0));
	K = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*a).shape), ((NI) 1));
	N = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), ((NI) 1));
	memset((void*)(&cont_A), 0, sizeof(cont_A));
	memset((void*)(&T1_), 0, sizeof(T1_));
	asContiguous_3BZwdaXStdH0qceZAOttRw(a, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101), NIM_FALSE, (&T1_));
	cont_A.shape = T1_.shape;
	cont_A.strides = T1_.strides;
	cont_A.offset = T1_.offset;
	cont_A.storage.Fdata = T1_.storage.Fdata;
	memset((void*)(&cont_B), 0, sizeof(cont_B));
	memset((void*)(&T2_), 0, sizeof(T2_));
	asContiguous_3BZwdaXStdH0qceZAOttRw(b, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101), NIM_FALSE, (&T2_));
	cont_B.shape = T2_.shape;
	cont_B.strides = T2_.strides;
	cont_B.offset = T2_.offset;
	cont_B.storage.Fdata = T2_.storage.Fdata;
	memset((void*)(&c_2), 0, sizeof(c_2));
	memset((void*)(&T3_), 0, sizeof(T3_));
	asContiguous_3BZwdaXStdH0qceZAOttRw((&(*c)), ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101), NIM_FALSE, (&T3_));
	c_2.shape = T3_.shape;
	c_2.strides = T3_.strides;
	c_2.offset = T3_.offset;
	c_2.storage.Fdata = T3_.storage.Fdata;
	cont_A_is_rowMajor = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&cont_A));
	cont_B_is_rowMajor = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&cont_B));
	c_is_rowMajor = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&c_2));
	{
		if (!cont_A_is_rowMajor) goto LA6_;
		transpose_A = ((tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg) 111);
	}
	goto LA4_;
	LA6_: ;
	{
		transpose_A = ((tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg) 112);
	}
	LA4_: ;
	{
		if (!cont_A_is_rowMajor) goto LA11_;
		lda = K;
	}
	goto LA9_;
	LA11_: ;
	{
		lda = M;
	}
	LA9_: ;
	{
		if (!cont_B_is_rowMajor) goto LA16_;
		transpose_B = ((tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg) 111);
	}
	goto LA14_;
	LA16_: ;
	{
		transpose_B = ((tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg) 112);
	}
	LA14_: ;
	{
		if (!cont_B_is_rowMajor) goto LA21_;
		ldb = N;
	}
	goto LA19_;
	LA21_: ;
	{
		ldb = K;
	}
	LA19_: ;
	{
		if (!c_is_rowMajor) goto LA26_;
		order_C = ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101);
	}
	goto LA24_;
	LA26_: ;
	{
		order_C = ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 102);
	}
	LA24_: ;
	{
		if (!c_is_rowMajor) goto LA31_;
		ldc = N;
	}
	goto LA29_;
	LA31_: ;
	{
		ldc = M;
	}
	LA29_: ;
	T34_ = (NF*)0;
	T34_ = get_offset_ptr_7j9bbv7iiFutQHSe5SiqO9bAp_operator_blas_l2l3((&cont_A));
	T35_ = (NF*)0;
	T35_ = get_offset_ptr_7j9bbv7iiFutQHSe5SiqO9bAp_operator_blas_l2l3((&cont_B));
	T36_ = (NF*)0;
	T36_ = get_offset_ptr_7j9bbv7iiFutQHSe5SiqO9bAp_operator_blas_l2l3((&c_2));
	Dl_281962_(order_C, transpose_A, transpose_B, M, N, K, alpha, T34_, lda, T35_, ldb, beta, T36_, ldc);
}

static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI* result;
	result = (NI*)0;
	result = (&(*a).data[(idx)- 0]);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, blasMV_y_eq_aAx_p_by_IwkaLYMEGnuDE3112aDKAA)(NF alpha, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* x, NF beta, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* y) {
	NI M;
	NI N;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ cont_A;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ T1_;
	NIM_BOOL cont_A_is_rowMajor;
	tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg cont_A_order;
	NI lda;
	NF* T12_;
	NF* T13_;
	NI T14_;
	NF* T15_;
	NI* T16_;
	M = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*a).shape), ((NI) 0));
	N = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*a).shape), ((NI) 1));
	memset((void*)(&cont_A), 0, sizeof(cont_A));
	memset((void*)(&T1_), 0, sizeof(T1_));
	asContiguous_3BZwdaXStdH0qceZAOttRw(a, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101), NIM_FALSE, (&T1_));
	cont_A.shape = T1_.shape;
	cont_A.strides = T1_.strides;
	cont_A.offset = T1_.offset;
	cont_A.storage.Fdata = T1_.storage.Fdata;
	cont_A_is_rowMajor = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&cont_A));
	{
		if (!cont_A_is_rowMajor) goto LA4_;
		cont_A_order = ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101);
	}
	goto LA2_;
	LA4_: ;
	{
		cont_A_order = ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 102);
	}
	LA2_: ;
	{
		if (!cont_A_is_rowMajor) goto LA9_;
		lda = N;
	}
	goto LA7_;
	LA9_: ;
	{
		lda = M;
	}
	LA7_: ;
	T12_ = (NF*)0;
	T12_ = get_offset_ptr_7j9bbv7iiFutQHSe5SiqO9bAp_operator_blas_l2l3((&cont_A));
	T13_ = (NF*)0;
	T13_ = get_offset_ptr_7j9bbv7iiFutQHSe5SiqO9bAp_operator_blas_l2l3(x);
	T14_ = (NI)0;
	T14_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*x).strides), ((NI) 0));
	T15_ = (NF*)0;
	T15_ = get_offset_ptr_7j9bbv7iiFutQHSe5SiqO9bAp_operator_blas_l2l3((&(*y)));
	T16_ = (NI*)0;
	T16_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*y).strides), ((NI) 0));
	Dl_281926_(cont_A_order, ((tyEnum_TransposeType_M7gJ9aK3Je73Q9a4qUsFc5Xg) 111), M, N, alpha, T12_, lda, T13_, T14_, beta, T15_, (*T16_));
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_p_operator_blas_l2l3Init000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_p_operator_blas_l2l3DatInit000)(void) {
}

