/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_aggregate.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_aggregate.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
typedef NU8 tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
N_LIB_PRIVATE N_NIMCALL(void, clone_ZM1QOqEv5MvfReVUOV9cKEA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
static N_INLINE(void, atAxisIndex_wRyG1o7J1Htr2PzCHcrD9bQaggregate)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI axis, NI idx, NI length, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(void, X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx, NI v);
static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
N_LIB_PRIVATE N_NIMCALL(void, pluseq__k0y4rc9aHyhmsJBSS4FKm4g)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* b);
extern TNimType NTI_urhjHEwA2NkLvIUFwuBxiQ_;

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = ((NI) 1);
	{
		NI value;
		value = (NI)0;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (*a).len;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA4;
					i = i_2;
					value = (*a).data[(i)- 0];
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&result), value);
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	return result;
}

static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = product_k2YXWcJ5lNu24E2yfX7EKQvectorize((&(*t).shape));
	return result;
}

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(void, X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx, NI v) {
	(*a).data[(idx)- 0] = v;
}

static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI* result;
	result = (NI*)0;
	result = (&(*a).data[(idx)- 0]);
	return result;
}

static N_INLINE(void, atAxisIndex_wRyG1o7J1Htr2PzCHcrD9bQaggregate)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI axis, NI idx, NI length, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NI* T1_;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	(*Result).shape = (*t).shape;
	(*Result).strides = (*t).strides;
	(*Result).offset = (*t).offset;
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), (*t).storage.Fdata);
	X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&(*Result).shape), axis, length);
	T1_ = (NI*)0;
	T1_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*Result).strides), axis);
	(*Result).offset += (NI)((*T1_) * idx);
}

N_LIB_PRIVATE N_NIMCALL(void, sum_dugRll9afFe9cBR9cbgnMtjBg)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI axis, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ z;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ reduced;
	NI weight;
	NI T1_;
	NI T2_;
	NI ompsize;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	memset((void*)(&z), 0, sizeof(z));
	z.shape = (*t).shape;
	z.strides = (*t).strides;
	z.offset = (*t).offset;
	z.storage.Fdata = (*t).storage.Fdata;
	memset((void*)(&reduced), 0, sizeof(reduced));
	T1_ = (NI)0;
	T1_ = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&z));
	T2_ = (NI)0;
	T2_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), axis);
	weight = (NI)(T1_ / T2_);
	ompsize = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), axis);
	{
		NIM_BOOL T5_;
		T5_ = (NIM_BOOL)0;
		T5_ = likely((((NI) 0) < ompsize));
		if (!T5_) goto LA6_;
		{
			{
				NI block_offset;
				NI block_size;
				block_offset = ((NI) 0);
				{
					{
						tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ T12_;
						memset((void*)(&T12_), 0, sizeof(T12_));
						atAxisIndex_wRyG1o7J1Htr2PzCHcrD9bQaggregate((&z), axis, block_offset, ((NI) 1), (&T12_));
						clone_ZM1QOqEv5MvfReVUOV9cKEA((&T12_), ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101), (&reduced));
					}
				}
				block_offset = ((NI) 1);
				block_size = (NI)(ompsize - ((NI) 1));
				{
					if (!(((NI) 0) < block_size)) goto LA15_;
					{
						{
							tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ y;
							tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ out_t;
							memset((void*)(&y), 0, sizeof(y));
							memset((void*)(&out_t), 0, sizeof(out_t));
							atAxisIndex_wRyG1o7J1Htr2PzCHcrD9bQaggregate((&z), axis, block_offset, ((NI) 1), (&out_t));
							{
								NI _;
								NI i;
								_ = (NI)0;
								i = ((NI) 0);
								{
									while (1) {
										NI T22_;
										if (!(i < block_size)) goto LA21;
										_ = i;
										y.shape = out_t.shape;
										y.strides = out_t.strides;
										y.offset = out_t.offset;
										y.storage.Fdata = out_t.storage.Fdata;
										pluseq__k0y4rc9aHyhmsJBSS4FKm4g((&reduced), (&y));
										T22_ = (NI)0;
										T22_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.strides), axis);
										out_t.offset += T22_;
										i += ((NI) 1);
									} LA21: ;
								}
							}
						}
					}
				}
				LA15_: ;
			}
		}
	}
	LA6_: ;
	(*Result).shape = reduced.shape;
	(*Result).strides = reduced.strides;
	(*Result).offset = reduced.offset;
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), reduced.storage.Fdata);
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_aggregateInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_aggregateDatInit000)(void) {
}

