/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_p_shapeshifting.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_p_shapeshifting.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_ZqtwwojkKZ9bCA58nE5quMA tyTuple_ZqtwwojkKZ9bCA58nE5quMA;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
typedef NU8 tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct RootObj {
TNimType* m_type;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyTuple_ZqtwwojkKZ9bCA58nE5quMA {
tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ Field0;
tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ Field1;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isContiguous_rS8xRFMCajURo6KXS4BJfQp_shapeshifting)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
static N_INLINE(NIM_BOOL, is_F_contiguous_rS8xRFMCajURo6KXS4BJfQ_2p_shapeshifting)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
N_LIB_PRIVATE N_NIMCALL(void, reshape_no_copy_BM8u7EiCpktujgIBsWNNxQ_2)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* new_shape, NI new_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result);
static N_INLINE(void, copyFrom_87gws0flOBNTaof6z6y4kwvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI* s, NI sLen_0);
N_LIB_PRIVATE N_NIMCALL(void, shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, reshape_with_copy_BM8u7EiCpktujgIBsWNNxQ_3)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* new_shape, NI new_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result);
static N_INLINE(void, newTensorUninit_8IqP8DVP9clOgUGmzYBEvMgp_shapeshifting)(NI* shape, NI shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(void, tensorCpu_cwvbRqbkqB6HikRuAXFeWQvectorize)(NI* out_shape, NI out_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout);
static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting)(NI len);
N_NIMCALL(void*, nimNewSeqOfCap)(TNimType* typ, NI cap);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
static N_INLINE(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw, initMetadataArray_tdYr19aGh9c169aZjt03Hs0ewp_shapeshifting)(NI len);
static N_INLINE(void, X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx, NI v);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(void, newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
static N_INLINE(void, tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* out_shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout);
static N_INLINE(void, copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* s);
static N_INLINE(void, dataeq__xsjjBf8E9cY5K77iZjy0gMQp_shapeshifting)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tySequence_Zj5xKXgsXnI4n4hPS6nACA* s);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
extern TNimType NTI_urhjHEwA2NkLvIUFwuBxiQ_;
extern TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_9aGlkjH9bCuvlzxydw4zyvaw_2, "Broadcasting error: non-singleton dimensions must be the same i"
"n both tensors", 77);

static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = (NI)((*a).len - ((NI) 1));
	return result;
}

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write((&(*t).shape));
		res = colontmp_;
		{
			while (1) {
				NI T12_;
				if (!(((NI) 0) <= res)) goto LA3;
				i = res;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				res -= ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, is_F_contiguous_rS8xRFMCajURo6KXS4BJfQ_2p_shapeshifting)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (*t).shape.len;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI T12_;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, isContiguous_rS8xRFMCajURo6KXS4BJfQp_shapeshifting)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NIM_BOOL T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T1_ = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write(t);
	if (T1_) goto LA2_;
	T1_ = is_F_contiguous_rS8xRFMCajURo6KXS4BJfQ_2p_shapeshifting(t);
	LA2_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyFrom_87gws0flOBNTaof6z6y4kwvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI* s, NI sLen_0) {
	(*a).len = sLen_0;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = sLen_0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				(*a).data[(i)- 0] = s[i];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

N_LIB_PRIVATE N_NIMCALL(void, reshape_no_copy_BM8u7EiCpktujgIBsWNNxQ_2)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* new_shape, NI new_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result) {
	copyFrom_87gws0flOBNTaof6z6y4kwvectorize((&(*result).shape), new_shape, new_shapeLen_0);
	shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A((&(*result).shape), ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101), (&(*result).strides));
	(*result).offset = (*t).offset;
}

static N_INLINE(void, tensorCpu_cwvbRqbkqB6HikRuAXFeWQvectorize)(NI* out_shape, NI out_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout) {
	copyFrom_87gws0flOBNTaof6z6y4kwvectorize((&(*result).shape), out_shape, out_shapeLen_0);
	shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A((&(*result).shape), layout, (&(*result).strides));
	(*result).offset = ((NI) 0);
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting)(NI len) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* result;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)nimNewSeqOfCap((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), len);
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) setLengthSeq(&(result)->Sup, sizeof(NF), len);
	return result;
}

static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = ((NI) 1);
	{
		NI value;
		value = (NI)0;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (*a).len;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA4;
					i = i_2;
					value = (*a).data[(i)- 0];
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&result), value);
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	return result;
}

static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = product_k2YXWcJ5lNu24E2yfX7EKQvectorize((&(*t).shape));
	return result;
}

static N_INLINE(void, newTensorUninit_8IqP8DVP9clOgUGmzYBEvMgp_shapeshifting)(NI* shape, NI shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NI T1_;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	tensorCpu_cwvbRqbkqB6HikRuAXFeWQvectorize(shape, shapeLen_0, Result, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101));
	T1_ = (NI)0;
	T1_ = size_9c9bGcb6H7uf0KFeicXmH40Avectorize(Result);
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting(((NI) (T1_))));
}

static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NF* result;
	result = (NF*)0;
	result = ((NF*) ((&(*t).storage.Fdata->data[(*t).offset])));
	return result;
}

static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = (*t).shape.len;
	return result;
}

static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI* result;
	result = (NI*)0;
	result = (&(*a).data[(idx)- 0]);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, reshape_with_copy_BM8u7EiCpktujgIBsWNNxQ_3)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* new_shape, NI new_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result) {
	NI ompsize;
	newTensorUninit_8IqP8DVP9clOgUGmzYBEvMgp_shapeshifting(new_shape, new_shapeLen_0, (&(*result)));
	ompsize = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&(*result)));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = likely((((NI) 0) < ompsize));
		if (!T3_) goto LA4_;
		{
			NI block_offset;
			NI block_size;
			block_offset = ((NI) 0);
			block_size = ompsize;
			{
				{
					NF* x;
					NF y;
					NIM_BOOL t1_contiguous;
					NIM_BOOL t2_contiguous;
					NF* t1data;
					NF* t2data;
					x = (NF*)0;
					y = (NF)0;
					t1_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&(*result)));
					t2_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write(t);
					t1data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&(*result)));
					t2data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write(t);
					{
						NIM_BOOL T11_;
						T11_ = (NIM_BOOL)0;
						T11_ = t1_contiguous;
						if (!(T11_)) goto LA12_;
						T11_ = t2_contiguous;
						LA12_: ;
						if (!T11_) goto LA13_;
						{
							NI i;
							NI colontmp_;
							NI i_2;
							i = (NI)0;
							colontmp_ = (NI)0;
							colontmp_ = (NI)(block_offset + block_size);
							i_2 = block_offset;
							{
								while (1) {
									if (!(i_2 < colontmp_)) goto LA17;
									i = i_2;
									x = (&t1data[(i)- 0]);
									y = t2data[(i)- 0];
									(*x) = y;
									i_2 += ((NI) 1);
								} LA17: ;
							}
						}
					}
					goto LA9_;
					LA13_: ;
					{
						NI t2_iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides;
						if (!t1_contiguous) goto LA19_;
						t2_iter_pos = ((NI) 0);
						{
							NI i_3;
							NI colontmp__2;
							NI i_4;
							i_3 = (NI)0;
							colontmp__2 = (NI)0;
							colontmp__2 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
							i_4 = ((NI) 0);
							{
								while (1) {
									NI T24_;
									NI T25_;
									if (!(i_4 < colontmp__2)) goto LA23;
									i_3 = i_4;
									T24_ = (NI)0;
									T24_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i_3);
									T25_ = (NI)0;
									T25_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_3);
									t2_backstrides[(i_3)- 0] = (NI)(T24_ * (NI)(T25_ - ((NI) 1)));
									t2_coord[(i_3)- 0] = ((NI) 0);
									i_4 += ((NI) 1);
								} LA23: ;
							}
						}
						{
							NI z;
							if (!!((block_offset == ((NI) 0)))) goto LA28_;
							z = ((NI) 1);
							{
								NI i_5;
								NI colontmp__3;
								NI T31_;
								NI res;
								i_5 = (NI)0;
								colontmp__3 = (NI)0;
								T31_ = (NI)0;
								T31_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
								colontmp__3 = (NI)(T31_ - ((NI) 1));
								res = colontmp__3;
								{
									while (1) {
										NI T34_;
										NI T35_;
										NI T36_;
										if (!(((NI) 0) <= res)) goto LA33;
										i_5 = res;
										T34_ = (NI)0;
										T34_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_5);
										t2_coord[(i_5)- 0] = (NI)((NI)(block_offset / z) % T34_);
										T35_ = (NI)0;
										T35_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i_5);
										t2_iter_pos += (NI)(t2_coord[(i_5)- 0] * T35_);
										T36_ = (NI)0;
										T36_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_5);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T36_);
										res -= ((NI) 1);
									} LA33: ;
								}
							}
						}
						LA28_: ;
						{
							NI i_6;
							NI colontmp__4;
							NI i_7;
							i_6 = (NI)0;
							colontmp__4 = (NI)0;
							colontmp__4 = (NI)(block_offset + block_size);
							i_7 = block_offset;
							{
								while (1) {
									if (!(i_7 < colontmp__4)) goto LA39;
									i_6 = i_7;
									x = (&t1data[(i_6)- 0]);
									y = t2data[(t2_iter_pos)- 0];
									(*x) = y;
									{
										NI k;
										NI colontmp__5;
										NI T41_;
										NI res_2;
										k = (NI)0;
										colontmp__5 = (NI)0;
										T41_ = (NI)0;
										T41_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
										colontmp__5 = (NI)(T41_ - ((NI) 1));
										res_2 = colontmp__5;
										{
											while (1) {
												if (!(((NI) 0) <= res_2)) goto LA43;
												k = res_2;
												{
													NI T46_;
													NI T49_;
													T46_ = (NI)0;
													T46_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), k);
													if (!(t2_coord[(k)- 0] < (NI)(T46_ - ((NI) 1)))) goto LA47_;
													t2_coord[(k)- 0] += ((NI) 1);
													T49_ = (NI)0;
													T49_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), k);
													t2_iter_pos += T49_;
													goto LA40;
												}
												goto LA44_;
												LA47_: ;
												{
													t2_coord[(k)- 0] = ((NI) 0);
													t2_iter_pos -= t2_backstrides[(k)- 0];
												}
												LA44_: ;
												res_2 -= ((NI) 1);
											} LA43: ;
										}
									} LA40: ;
									i_7 += ((NI) 1);
								} LA39: ;
							}
						}
					}
					goto LA9_;
					LA19_: ;
					{
						NI t1_iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides;
						if (!t2_contiguous) goto LA52_;
						t1_iter_pos = ((NI) 0);
						{
							NI i_8;
							NI colontmp__6;
							NI i_9;
							i_8 = (NI)0;
							colontmp__6 = (NI)0;
							colontmp__6 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
							i_9 = ((NI) 0);
							{
								while (1) {
									NI* T57_;
									NI* T58_;
									if (!(i_9 < colontmp__6)) goto LA56;
									i_8 = i_9;
									T57_ = (NI*)0;
									T57_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), i_8);
									T58_ = (NI*)0;
									T58_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_8);
									t1_backstrides[(i_8)- 0] = (NI)((*T57_) * (NI)((*T58_) - ((NI) 1)));
									t1_coord[(i_8)- 0] = ((NI) 0);
									i_9 += ((NI) 1);
								} LA56: ;
							}
						}
						{
							NI z_2;
							if (!!((block_offset == ((NI) 0)))) goto LA61_;
							z_2 = ((NI) 1);
							{
								NI i_10;
								NI colontmp__7;
								NI T64_;
								NI res_3;
								i_10 = (NI)0;
								colontmp__7 = (NI)0;
								T64_ = (NI)0;
								T64_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
								colontmp__7 = (NI)(T64_ - ((NI) 1));
								res_3 = colontmp__7;
								{
									while (1) {
										NI* T67_;
										NI* T68_;
										NI* T69_;
										if (!(((NI) 0) <= res_3)) goto LA66;
										i_10 = res_3;
										T67_ = (NI*)0;
										T67_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_10);
										t1_coord[(i_10)- 0] = (NI)((NI)(block_offset / z_2) % (*T67_));
										T68_ = (NI*)0;
										T68_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), i_10);
										t1_iter_pos += (NI)(t1_coord[(i_10)- 0] * (*T68_));
										T69_ = (NI*)0;
										T69_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_10);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_2), (*T69_));
										res_3 -= ((NI) 1);
									} LA66: ;
								}
							}
						}
						LA61_: ;
						{
							NI i_11;
							NI colontmp__8;
							NI i_12;
							i_11 = (NI)0;
							colontmp__8 = (NI)0;
							colontmp__8 = (NI)(block_offset + block_size);
							i_12 = block_offset;
							{
								while (1) {
									if (!(i_12 < colontmp__8)) goto LA72;
									i_11 = i_12;
									x = (&t1data[(t1_iter_pos)- 0]);
									y = t2data[(i_11)- 0];
									(*x) = y;
									{
										NI k_2;
										NI colontmp__9;
										NI T74_;
										NI res_4;
										k_2 = (NI)0;
										colontmp__9 = (NI)0;
										T74_ = (NI)0;
										T74_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
										colontmp__9 = (NI)(T74_ - ((NI) 1));
										res_4 = colontmp__9;
										{
											while (1) {
												if (!(((NI) 0) <= res_4)) goto LA76;
												k_2 = res_4;
												{
													NI* T79_;
													NI* T82_;
													T79_ = (NI*)0;
													T79_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), k_2);
													if (!(t1_coord[(k_2)- 0] < (NI)((*T79_) - ((NI) 1)))) goto LA80_;
													t1_coord[(k_2)- 0] += ((NI) 1);
													T82_ = (NI*)0;
													T82_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), k_2);
													t1_iter_pos += (*T82_);
													goto LA73;
												}
												goto LA77_;
												LA80_: ;
												{
													t1_coord[(k_2)- 0] = ((NI) 0);
													t1_iter_pos -= t1_backstrides[(k_2)- 0];
												}
												LA77_: ;
												res_4 -= ((NI) 1);
											} LA76: ;
										}
									} LA73: ;
									i_12 += ((NI) 1);
								} LA72: ;
							}
						}
					}
					goto LA9_;
					LA52_: ;
					{
						NI t1_iter_pos_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides_2;
						NI t2_iter_pos_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides_2;
						t1_iter_pos_2 = ((NI) 0);
						{
							NI i_13;
							NI colontmp__10;
							NI i_14;
							i_13 = (NI)0;
							colontmp__10 = (NI)0;
							colontmp__10 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
							i_14 = ((NI) 0);
							{
								while (1) {
									NI* T88_;
									NI* T89_;
									if (!(i_14 < colontmp__10)) goto LA87;
									i_13 = i_14;
									T88_ = (NI*)0;
									T88_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), i_13);
									T89_ = (NI*)0;
									T89_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_13);
									t1_backstrides_2[(i_13)- 0] = (NI)((*T88_) * (NI)((*T89_) - ((NI) 1)));
									t1_coord_2[(i_13)- 0] = ((NI) 0);
									i_14 += ((NI) 1);
								} LA87: ;
							}
						}
						{
							NI z_3;
							if (!!((block_offset == ((NI) 0)))) goto LA92_;
							z_3 = ((NI) 1);
							{
								NI i_15;
								NI colontmp__11;
								NI T95_;
								NI res_5;
								i_15 = (NI)0;
								colontmp__11 = (NI)0;
								T95_ = (NI)0;
								T95_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
								colontmp__11 = (NI)(T95_ - ((NI) 1));
								res_5 = colontmp__11;
								{
									while (1) {
										NI* T98_;
										NI* T99_;
										NI* T100_;
										if (!(((NI) 0) <= res_5)) goto LA97;
										i_15 = res_5;
										T98_ = (NI*)0;
										T98_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_15);
										t1_coord_2[(i_15)- 0] = (NI)((NI)(block_offset / z_3) % (*T98_));
										T99_ = (NI*)0;
										T99_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), i_15);
										t1_iter_pos_2 += (NI)(t1_coord_2[(i_15)- 0] * (*T99_));
										T100_ = (NI*)0;
										T100_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_15);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_3), (*T100_));
										res_5 -= ((NI) 1);
									} LA97: ;
								}
							}
						}
						LA92_: ;
						t2_iter_pos_2 = ((NI) 0);
						{
							NI i_16;
							NI colontmp__12;
							NI i_17;
							i_16 = (NI)0;
							colontmp__12 = (NI)0;
							colontmp__12 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
							i_17 = ((NI) 0);
							{
								while (1) {
									NI T104_;
									NI T105_;
									if (!(i_17 < colontmp__12)) goto LA103;
									i_16 = i_17;
									T104_ = (NI)0;
									T104_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i_16);
									T105_ = (NI)0;
									T105_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_16);
									t2_backstrides_2[(i_16)- 0] = (NI)(T104_ * (NI)(T105_ - ((NI) 1)));
									t2_coord_2[(i_16)- 0] = ((NI) 0);
									i_17 += ((NI) 1);
								} LA103: ;
							}
						}
						{
							NI z_4;
							if (!!((block_offset == ((NI) 0)))) goto LA108_;
							z_4 = ((NI) 1);
							{
								NI i_18;
								NI colontmp__13;
								NI T111_;
								NI res_6;
								i_18 = (NI)0;
								colontmp__13 = (NI)0;
								T111_ = (NI)0;
								T111_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
								colontmp__13 = (NI)(T111_ - ((NI) 1));
								res_6 = colontmp__13;
								{
									while (1) {
										NI T114_;
										NI T115_;
										NI T116_;
										if (!(((NI) 0) <= res_6)) goto LA113;
										i_18 = res_6;
										T114_ = (NI)0;
										T114_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_18);
										t2_coord_2[(i_18)- 0] = (NI)((NI)(block_offset / z_4) % T114_);
										T115_ = (NI)0;
										T115_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i_18);
										t2_iter_pos_2 += (NI)(t2_coord_2[(i_18)- 0] * T115_);
										T116_ = (NI)0;
										T116_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_18);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_4), T116_);
										res_6 -= ((NI) 1);
									} LA113: ;
								}
							}
						}
						LA108_: ;
						{
							NI i_19;
							NI colontmp__14;
							NI i_20;
							i_19 = (NI)0;
							colontmp__14 = (NI)0;
							colontmp__14 = (NI)(block_offset + block_size);
							i_20 = block_offset;
							{
								while (1) {
									if (!(i_20 < colontmp__14)) goto LA119;
									i_19 = i_20;
									x = (&t1data[(t1_iter_pos_2)- 0]);
									y = t2data[(t2_iter_pos_2)- 0];
									(*x) = y;
									{
										NI k_3;
										NI colontmp__15;
										NI T121_;
										NI res_7;
										k_3 = (NI)0;
										colontmp__15 = (NI)0;
										T121_ = (NI)0;
										T121_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
										colontmp__15 = (NI)(T121_ - ((NI) 1));
										res_7 = colontmp__15;
										{
											while (1) {
												if (!(((NI) 0) <= res_7)) goto LA123;
												k_3 = res_7;
												{
													NI* T126_;
													NI* T129_;
													T126_ = (NI*)0;
													T126_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), k_3);
													if (!(t1_coord_2[(k_3)- 0] < (NI)((*T126_) - ((NI) 1)))) goto LA127_;
													t1_coord_2[(k_3)- 0] += ((NI) 1);
													T129_ = (NI*)0;
													T129_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), k_3);
													t1_iter_pos_2 += (*T129_);
													goto LA120;
												}
												goto LA124_;
												LA127_: ;
												{
													t1_coord_2[(k_3)- 0] = ((NI) 0);
													t1_iter_pos_2 -= t1_backstrides_2[(k_3)- 0];
												}
												LA124_: ;
												res_7 -= ((NI) 1);
											} LA123: ;
										}
									} LA120: ;
									{
										NI k_4;
										NI colontmp__16;
										NI T132_;
										NI res_8;
										k_4 = (NI)0;
										colontmp__16 = (NI)0;
										T132_ = (NI)0;
										T132_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
										colontmp__16 = (NI)(T132_ - ((NI) 1));
										res_8 = colontmp__16;
										{
											while (1) {
												if (!(((NI) 0) <= res_8)) goto LA134;
												k_4 = res_8;
												{
													NI T137_;
													NI T140_;
													T137_ = (NI)0;
													T137_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), k_4);
													if (!(t2_coord_2[(k_4)- 0] < (NI)(T137_ - ((NI) 1)))) goto LA138_;
													t2_coord_2[(k_4)- 0] += ((NI) 1);
													T140_ = (NI)0;
													T140_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), k_4);
													t2_iter_pos_2 += T140_;
													goto LA131;
												}
												goto LA135_;
												LA138_: ;
												{
													t2_coord_2[(k_4)- 0] = ((NI) 0);
													t2_iter_pos_2 -= t2_backstrides_2[(k_4)- 0];
												}
												LA135_: ;
												res_8 -= ((NI) 1);
											} LA134: ;
										}
									} LA131: ;
									i_20 += ((NI) 1);
								} LA119: ;
							}
						}
					}
					LA9_: ;
				}
			}
		}
	}
	LA4_: ;
}

N_LIB_PRIVATE N_NIMCALL(void, reshapeImpl_BM8u7EiCpktujgIBsWNNxQ)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* new_shape, NI new_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result) {
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isContiguous_rS8xRFMCajURo6KXS4BJfQp_shapeshifting(t);
		if (!T3_) goto LA4_;
		reshape_no_copy_BM8u7EiCpktujgIBsWNNxQ_2(t, new_shape, new_shapeLen_0, result);
		unsureAsgnRef((void**) (&(*result).storage.Fdata), (*t).storage.Fdata);
		goto BeforeRet_;
	}
	LA4_: ;
	reshape_with_copy_BM8u7EiCpktujgIBsWNNxQ_3(t, new_shape, new_shapeLen_0, result);
	}BeforeRet_: ;
}

static N_INLINE(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw, initMetadataArray_tdYr19aGh9c169aZjt03Hs0ewp_shapeshifting)(NI len) {
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw result;
	memset((void*)(&result), 0, sizeof(result));
	result.len = len;
	return result;
}

static N_INLINE(void, X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx, NI v) {
	(*a).data[(idx)- 0] = v;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(void, broadcast2Impl_ZE7WYwzEy0uEQgPiRfB1dA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* b, tyTuple_ZqtwwojkKZ9bCA58nE5quMA* result) {
	NI rank;
	NI T1_;
	NI T2_;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shapeA;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw stridesA;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shapeB;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw stridesB;
	T1_ = (NI)0;
	T1_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(a);
	T2_ = (NI)0;
	T2_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(b);
	rank = ((T1_ >= T2_) ? T1_ : T2_);
	shapeA = initMetadataArray_tdYr19aGh9c169aZjt03Hs0ewp_shapeshifting(rank);
	stridesA = initMetadataArray_tdYr19aGh9c169aZjt03Hs0ewp_shapeshifting(rank);
	shapeB = initMetadataArray_tdYr19aGh9c169aZjt03Hs0ewp_shapeshifting(rank);
	stridesB = initMetadataArray_tdYr19aGh9c169aZjt03Hs0ewp_shapeshifting(rank);
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI shape_A_iter;
				NI shape_B_iter;
				if (!(i_2 < rank)) goto LA5;
				i = i_2;
				{
					if (!(i < rank)) goto LA8_;
					shape_A_iter = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*a).shape), i);
				}
				goto LA6_;
				LA8_: ;
				{
					shape_A_iter = ((NI) 1);
				}
				LA6_: ;
				{
					if (!(i < rank)) goto LA13_;
					shape_B_iter = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).shape), i);
				}
				goto LA11_;
				LA13_: ;
				{
					shape_B_iter = ((NI) 1);
				}
				LA11_: ;
				{
					NI T20_;
					NI T21_;
					if (!(shape_A_iter == shape_B_iter)) goto LA18_;
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&shapeA), i, shape_A_iter);
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&shapeB), i, shape_A_iter);
					T20_ = (NI)0;
					T20_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*a).strides), i);
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&stridesA), i, T20_);
					T21_ = (NI)0;
					T21_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).strides), i);
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&stridesB), i, T21_);
				}
				goto LA16_;
				LA18_: ;
				{
					NI T25_;
					if (!(shape_A_iter == ((NI) 1))) goto LA23_;
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&shapeA), i, shape_B_iter);
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&shapeB), i, shape_B_iter);
					T25_ = (NI)0;
					T25_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*b).strides), i);
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&stridesB), i, T25_);
				}
				goto LA16_;
				LA23_: ;
				{
					NI T29_;
					if (!(shape_B_iter == ((NI) 1))) goto LA27_;
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&shapeA), i, shape_A_iter);
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&shapeB), i, shape_A_iter);
					T29_ = (NI)0;
					T29_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*a).strides), i);
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&stridesA), i, T29_);
				}
				goto LA16_;
				LA27_: ;
				{
					tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
					NimStringDesc* T31_;
					e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
					e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
					(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
					T31_ = (NimStringDesc*)0;
					T31_ = (*e).Sup.message; (*e).Sup.message = copyStringRC1(((NimStringDesc*) &TM_9aGlkjH9bCuvlzxydw4zyvaw_2));
					if (T31_) nimGCunrefNoCycle(T31_);
					asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
					raiseException((Exception*)e, "ValueError");
				}
				LA16_: ;
				i_2 += ((NI) 1);
			} LA5: ;
		}
	}
	(*result).Field0.shape = shapeA;
	(*result).Field0.strides = stridesA;
	(*result).Field0.offset = (*a).offset;
	(*result).Field1.shape = shapeB;
	(*result).Field1.strides = stridesB;
	(*result).Field1.offset = (*b).offset;
}

static N_INLINE(void, copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* s) {
	(*a).len = (*s).len;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (*s).len;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				(*a).data[(i)- 0] = (*s).data[(i)- 0];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

static N_INLINE(void, tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* out_shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout) {
	copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting((&(*result).shape), out_shape);
	shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A((&(*result).shape), layout, (&(*result).strides));
	(*result).offset = ((NI) 0);
}

static N_INLINE(void, newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NI T1_;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting(shape, Result, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101));
	T1_ = (NI)0;
	T1_ = size_9c9bGcb6H7uf0KFeicXmH40Avectorize(Result);
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting(((NI) (T1_))));
}

static N_INLINE(void, dataeq__xsjjBf8E9cY5K77iZjy0gMQp_shapeshifting)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tySequence_Zj5xKXgsXnI4n4hPS6nACA* s) {
	genericSeqAssign((&(*t).storage.Fdata), s, (&NTI_Zj5xKXgsXnI4n4hPS6nACA_));
}

N_LIB_PRIVATE N_NIMCALL(void, contiguousImpl_Svljdva1cfcaVIAOz2N6GA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result) {
	{
		tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ z;
		tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ dest;
		NF* __restrict__ data;
		NI ompsize;
		if (!(layout == ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101))) goto LA3_;
		memset((void*)(&z), 0, sizeof(z));
		z.shape = (*t).shape;
		z.strides = (*t).strides;
		z.offset = (*t).offset;
		z.storage.Fdata = (*t).storage.Fdata;
		memset((void*)(&dest), 0, sizeof(dest));
		newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting((&z.shape), (&dest));
		data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&dest));
		ompsize = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&dest));
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = likely((((NI) 0) < ompsize));
			if (!T7_) goto LA8_;
			{
				NI block_offset;
				NI block_size;
				block_offset = ((NI) 0);
				block_size = ompsize;
				{
					{
						NI i;
						NF x;
						NF* data_2;
						i = (NI)0;
						x = (NF)0;
						data_2 = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&z));
						{
							NIM_BOOL T15_;
							T15_ = (NIM_BOOL)0;
							T15_ = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&z));
							if (!T15_) goto LA16_;
							{
								NI i_2;
								NI colontmp_;
								NI i_3;
								i_2 = (NI)0;
								colontmp_ = (NI)0;
								colontmp_ = (NI)(block_offset + block_size);
								i_3 = block_offset;
								{
									while (1) {
										if (!(i_3 < colontmp_)) goto LA20;
										i_2 = i_3;
										i = i_2;
										x = data_2[(i_2)- 0];
										data[(i)- 0] = x;
										i_3 += ((NI) 1);
									} LA20: ;
								}
							}
						}
						goto LA13_;
						LA16_: ;
						{
							NI iter_pos;
							tyArray_7faYhUidbIkFZQJndG6Ggw coord;
							tyArray_7faYhUidbIkFZQJndG6Ggw backstrides;
							iter_pos = ((NI) 0);
							{
								NI i_4;
								NI colontmp__2;
								NI i_5;
								i_4 = (NI)0;
								colontmp__2 = (NI)0;
								colontmp__2 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z));
								i_5 = ((NI) 0);
								{
									while (1) {
										NI T25_;
										NI T26_;
										if (!(i_5 < colontmp__2)) goto LA24;
										i_4 = i_5;
										T25_ = (NI)0;
										T25_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.strides), i_4);
										T26_ = (NI)0;
										T26_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), i_4);
										backstrides[(i_4)- 0] = (NI)(T25_ * (NI)(T26_ - ((NI) 1)));
										coord[(i_4)- 0] = ((NI) 0);
										i_5 += ((NI) 1);
									} LA24: ;
								}
							}
							{
								NI z_2;
								if (!!((block_offset == ((NI) 0)))) goto LA29_;
								z_2 = ((NI) 1);
								{
									NI i_6;
									NI colontmp__3;
									NI T32_;
									NI res;
									i_6 = (NI)0;
									colontmp__3 = (NI)0;
									T32_ = (NI)0;
									T32_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z));
									colontmp__3 = (NI)(T32_ - ((NI) 1));
									res = colontmp__3;
									{
										while (1) {
											NI T35_;
											NI T36_;
											NI T37_;
											if (!(((NI) 0) <= res)) goto LA34;
											i_6 = res;
											T35_ = (NI)0;
											T35_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), i_6);
											coord[(i_6)- 0] = (NI)((NI)(block_offset / z_2) % T35_);
											T36_ = (NI)0;
											T36_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.strides), i_6);
											iter_pos += (NI)(coord[(i_6)- 0] * T36_);
											T37_ = (NI)0;
											T37_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), i_6);
											stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_2), T37_);
											res -= ((NI) 1);
										} LA34: ;
									}
								}
							}
							LA29_: ;
							{
								NI i_7;
								NI colontmp__4;
								NI i_8;
								i_7 = (NI)0;
								colontmp__4 = (NI)0;
								colontmp__4 = (NI)(block_offset + block_size);
								i_8 = block_offset;
								{
									while (1) {
										if (!(i_8 < colontmp__4)) goto LA40;
										i_7 = i_8;
										i = i_7;
										x = data_2[(iter_pos)- 0];
										data[(i)- 0] = x;
										{
											NI k;
											NI colontmp__5;
											NI T42_;
											NI res_2;
											k = (NI)0;
											colontmp__5 = (NI)0;
											T42_ = (NI)0;
											T42_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&z));
											colontmp__5 = (NI)(T42_ - ((NI) 1));
											res_2 = colontmp__5;
											{
												while (1) {
													if (!(((NI) 0) <= res_2)) goto LA44;
													k = res_2;
													{
														NI T47_;
														NI T50_;
														T47_ = (NI)0;
														T47_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.shape), k);
														if (!(coord[(k)- 0] < (NI)(T47_ - ((NI) 1)))) goto LA48_;
														coord[(k)- 0] += ((NI) 1);
														T50_ = (NI)0;
														T50_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&z.strides), k);
														iter_pos += T50_;
														goto LA41;
													}
													goto LA45_;
													LA48_: ;
													{
														coord[(k)- 0] = ((NI) 0);
														iter_pos -= backstrides[(k)- 0];
													}
													LA45_: ;
													res_2 -= ((NI) 1);
												} LA44: ;
											}
										} LA41: ;
										i_8 += ((NI) 1);
									} LA40: ;
								}
							}
						}
						LA13_: ;
					}
				}
			}
		}
		LA8_: ;
		(*result).shape = dest.shape;
		(*result).strides = dest.strides;
		(*result).offset = dest.offset;
		unsureAsgnRef((void**) (&(*result).storage.Fdata), dest.storage.Fdata);
	}
	goto LA1_;
	LA3_: ;
	{
		NI T53_;
		tySequence_Zj5xKXgsXnI4n4hPS6nACA* T54_;
		NI ompsize_2;
		tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting((&(*t).shape), result, layout);
		T53_ = (NI)0;
		T53_ = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&(*result)));
		T54_ = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
		T54_ = newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting(((NI) (T53_)));
		dataeq__xsjjBf8E9cY5K77iZjy0gMQp_shapeshifting(result, T54_);
		ompsize_2 = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&(*result)));
		{
			NIM_BOOL T57_;
			T57_ = (NIM_BOOL)0;
			T57_ = likely((((NI) 0) < ompsize_2));
			if (!T57_) goto LA58_;
			{
				NI block_offset_2;
				NI block_size_2;
				block_offset_2 = ((NI) 0);
				block_size_2 = ompsize_2;
				{
					{
						NF* x_2;
						NF y;
						NIM_BOOL t1_contiguous;
						NIM_BOOL t2_contiguous;
						NF* t1data;
						NF* t2data;
						x_2 = (NF*)0;
						y = (NF)0;
						t1_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&(*result)));
						t2_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write(t);
						t1data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&(*result)));
						t2data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write(t);
						{
							NIM_BOOL T65_;
							T65_ = (NIM_BOOL)0;
							T65_ = t1_contiguous;
							if (!(T65_)) goto LA66_;
							T65_ = t2_contiguous;
							LA66_: ;
							if (!T65_) goto LA67_;
							{
								NI i_9;
								NI colontmp__6;
								NI i_10;
								i_9 = (NI)0;
								colontmp__6 = (NI)0;
								colontmp__6 = (NI)(block_offset_2 + block_size_2);
								i_10 = block_offset_2;
								{
									while (1) {
										if (!(i_10 < colontmp__6)) goto LA71;
										i_9 = i_10;
										x_2 = (&t1data[(i_9)- 0]);
										y = t2data[(i_9)- 0];
										(*x_2) = y;
										i_10 += ((NI) 1);
									} LA71: ;
								}
							}
						}
						goto LA63_;
						LA67_: ;
						{
							NI t2_iter_pos;
							tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord;
							tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides;
							if (!t1_contiguous) goto LA73_;
							t2_iter_pos = ((NI) 0);
							{
								NI i_11;
								NI colontmp__7;
								NI i_12;
								i_11 = (NI)0;
								colontmp__7 = (NI)0;
								colontmp__7 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
								i_12 = ((NI) 0);
								{
									while (1) {
										NI T78_;
										NI T79_;
										if (!(i_12 < colontmp__7)) goto LA77;
										i_11 = i_12;
										T78_ = (NI)0;
										T78_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i_11);
										T79_ = (NI)0;
										T79_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_11);
										t2_backstrides[(i_11)- 0] = (NI)(T78_ * (NI)(T79_ - ((NI) 1)));
										t2_coord[(i_11)- 0] = ((NI) 0);
										i_12 += ((NI) 1);
									} LA77: ;
								}
							}
							{
								NI z_3;
								if (!!((block_offset_2 == ((NI) 0)))) goto LA82_;
								z_3 = ((NI) 1);
								{
									NI i_13;
									NI colontmp__8;
									NI T85_;
									NI res_3;
									i_13 = (NI)0;
									colontmp__8 = (NI)0;
									T85_ = (NI)0;
									T85_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
									colontmp__8 = (NI)(T85_ - ((NI) 1));
									res_3 = colontmp__8;
									{
										while (1) {
											NI T88_;
											NI T89_;
											NI T90_;
											if (!(((NI) 0) <= res_3)) goto LA87;
											i_13 = res_3;
											T88_ = (NI)0;
											T88_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_13);
											t2_coord[(i_13)- 0] = (NI)((NI)(block_offset_2 / z_3) % T88_);
											T89_ = (NI)0;
											T89_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i_13);
											t2_iter_pos += (NI)(t2_coord[(i_13)- 0] * T89_);
											T90_ = (NI)0;
											T90_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_13);
											stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_3), T90_);
											res_3 -= ((NI) 1);
										} LA87: ;
									}
								}
							}
							LA82_: ;
							{
								NI i_14;
								NI colontmp__9;
								NI i_15;
								i_14 = (NI)0;
								colontmp__9 = (NI)0;
								colontmp__9 = (NI)(block_offset_2 + block_size_2);
								i_15 = block_offset_2;
								{
									while (1) {
										if (!(i_15 < colontmp__9)) goto LA93;
										i_14 = i_15;
										x_2 = (&t1data[(i_14)- 0]);
										y = t2data[(t2_iter_pos)- 0];
										(*x_2) = y;
										{
											NI k_2;
											NI colontmp__10;
											NI T95_;
											NI res_4;
											k_2 = (NI)0;
											colontmp__10 = (NI)0;
											T95_ = (NI)0;
											T95_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
											colontmp__10 = (NI)(T95_ - ((NI) 1));
											res_4 = colontmp__10;
											{
												while (1) {
													if (!(((NI) 0) <= res_4)) goto LA97;
													k_2 = res_4;
													{
														NI T100_;
														NI T103_;
														T100_ = (NI)0;
														T100_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), k_2);
														if (!(t2_coord[(k_2)- 0] < (NI)(T100_ - ((NI) 1)))) goto LA101_;
														t2_coord[(k_2)- 0] += ((NI) 1);
														T103_ = (NI)0;
														T103_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), k_2);
														t2_iter_pos += T103_;
														goto LA94;
													}
													goto LA98_;
													LA101_: ;
													{
														t2_coord[(k_2)- 0] = ((NI) 0);
														t2_iter_pos -= t2_backstrides[(k_2)- 0];
													}
													LA98_: ;
													res_4 -= ((NI) 1);
												} LA97: ;
											}
										} LA94: ;
										i_15 += ((NI) 1);
									} LA93: ;
								}
							}
						}
						goto LA63_;
						LA73_: ;
						{
							NI t1_iter_pos;
							tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord;
							tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides;
							if (!t2_contiguous) goto LA106_;
							t1_iter_pos = ((NI) 0);
							{
								NI i_16;
								NI colontmp__11;
								NI i_17;
								i_16 = (NI)0;
								colontmp__11 = (NI)0;
								colontmp__11 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
								i_17 = ((NI) 0);
								{
									while (1) {
										NI* T111_;
										NI* T112_;
										if (!(i_17 < colontmp__11)) goto LA110;
										i_16 = i_17;
										T111_ = (NI*)0;
										T111_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), i_16);
										T112_ = (NI*)0;
										T112_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_16);
										t1_backstrides[(i_16)- 0] = (NI)((*T111_) * (NI)((*T112_) - ((NI) 1)));
										t1_coord[(i_16)- 0] = ((NI) 0);
										i_17 += ((NI) 1);
									} LA110: ;
								}
							}
							{
								NI z_4;
								if (!!((block_offset_2 == ((NI) 0)))) goto LA115_;
								z_4 = ((NI) 1);
								{
									NI i_18;
									NI colontmp__12;
									NI T118_;
									NI res_5;
									i_18 = (NI)0;
									colontmp__12 = (NI)0;
									T118_ = (NI)0;
									T118_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
									colontmp__12 = (NI)(T118_ - ((NI) 1));
									res_5 = colontmp__12;
									{
										while (1) {
											NI* T121_;
											NI* T122_;
											NI* T123_;
											if (!(((NI) 0) <= res_5)) goto LA120;
											i_18 = res_5;
											T121_ = (NI*)0;
											T121_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_18);
											t1_coord[(i_18)- 0] = (NI)((NI)(block_offset_2 / z_4) % (*T121_));
											T122_ = (NI*)0;
											T122_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), i_18);
											t1_iter_pos += (NI)(t1_coord[(i_18)- 0] * (*T122_));
											T123_ = (NI*)0;
											T123_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_18);
											stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_4), (*T123_));
											res_5 -= ((NI) 1);
										} LA120: ;
									}
								}
							}
							LA115_: ;
							{
								NI i_19;
								NI colontmp__13;
								NI i_20;
								i_19 = (NI)0;
								colontmp__13 = (NI)0;
								colontmp__13 = (NI)(block_offset_2 + block_size_2);
								i_20 = block_offset_2;
								{
									while (1) {
										if (!(i_20 < colontmp__13)) goto LA126;
										i_19 = i_20;
										x_2 = (&t1data[(t1_iter_pos)- 0]);
										y = t2data[(i_19)- 0];
										(*x_2) = y;
										{
											NI k_3;
											NI colontmp__14;
											NI T128_;
											NI res_6;
											k_3 = (NI)0;
											colontmp__14 = (NI)0;
											T128_ = (NI)0;
											T128_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
											colontmp__14 = (NI)(T128_ - ((NI) 1));
											res_6 = colontmp__14;
											{
												while (1) {
													if (!(((NI) 0) <= res_6)) goto LA130;
													k_3 = res_6;
													{
														NI* T133_;
														NI* T136_;
														T133_ = (NI*)0;
														T133_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), k_3);
														if (!(t1_coord[(k_3)- 0] < (NI)((*T133_) - ((NI) 1)))) goto LA134_;
														t1_coord[(k_3)- 0] += ((NI) 1);
														T136_ = (NI*)0;
														T136_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), k_3);
														t1_iter_pos += (*T136_);
														goto LA127;
													}
													goto LA131_;
													LA134_: ;
													{
														t1_coord[(k_3)- 0] = ((NI) 0);
														t1_iter_pos -= t1_backstrides[(k_3)- 0];
													}
													LA131_: ;
													res_6 -= ((NI) 1);
												} LA130: ;
											}
										} LA127: ;
										i_20 += ((NI) 1);
									} LA126: ;
								}
							}
						}
						goto LA63_;
						LA106_: ;
						{
							NI t1_iter_pos_2;
							tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord_2;
							tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides_2;
							NI t2_iter_pos_2;
							tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord_2;
							tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides_2;
							t1_iter_pos_2 = ((NI) 0);
							{
								NI i_21;
								NI colontmp__15;
								NI i_22;
								i_21 = (NI)0;
								colontmp__15 = (NI)0;
								colontmp__15 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
								i_22 = ((NI) 0);
								{
									while (1) {
										NI* T142_;
										NI* T143_;
										if (!(i_22 < colontmp__15)) goto LA141;
										i_21 = i_22;
										T142_ = (NI*)0;
										T142_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), i_21);
										T143_ = (NI*)0;
										T143_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_21);
										t1_backstrides_2[(i_21)- 0] = (NI)((*T142_) * (NI)((*T143_) - ((NI) 1)));
										t1_coord_2[(i_21)- 0] = ((NI) 0);
										i_22 += ((NI) 1);
									} LA141: ;
								}
							}
							{
								NI z_5;
								if (!!((block_offset_2 == ((NI) 0)))) goto LA146_;
								z_5 = ((NI) 1);
								{
									NI i_23;
									NI colontmp__16;
									NI T149_;
									NI res_7;
									i_23 = (NI)0;
									colontmp__16 = (NI)0;
									T149_ = (NI)0;
									T149_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
									colontmp__16 = (NI)(T149_ - ((NI) 1));
									res_7 = colontmp__16;
									{
										while (1) {
											NI* T152_;
											NI* T153_;
											NI* T154_;
											if (!(((NI) 0) <= res_7)) goto LA151;
											i_23 = res_7;
											T152_ = (NI*)0;
											T152_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_23);
											t1_coord_2[(i_23)- 0] = (NI)((NI)(block_offset_2 / z_5) % (*T152_));
											T153_ = (NI*)0;
											T153_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), i_23);
											t1_iter_pos_2 += (NI)(t1_coord_2[(i_23)- 0] * (*T153_));
											T154_ = (NI*)0;
											T154_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), i_23);
											stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_5), (*T154_));
											res_7 -= ((NI) 1);
										} LA151: ;
									}
								}
							}
							LA146_: ;
							t2_iter_pos_2 = ((NI) 0);
							{
								NI i_24;
								NI colontmp__17;
								NI i_25;
								i_24 = (NI)0;
								colontmp__17 = (NI)0;
								colontmp__17 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
								i_25 = ((NI) 0);
								{
									while (1) {
										NI T158_;
										NI T159_;
										if (!(i_25 < colontmp__17)) goto LA157;
										i_24 = i_25;
										T158_ = (NI)0;
										T158_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i_24);
										T159_ = (NI)0;
										T159_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_24);
										t2_backstrides_2[(i_24)- 0] = (NI)(T158_ * (NI)(T159_ - ((NI) 1)));
										t2_coord_2[(i_24)- 0] = ((NI) 0);
										i_25 += ((NI) 1);
									} LA157: ;
								}
							}
							{
								NI z_6;
								if (!!((block_offset_2 == ((NI) 0)))) goto LA162_;
								z_6 = ((NI) 1);
								{
									NI i_26;
									NI colontmp__18;
									NI T165_;
									NI res_8;
									i_26 = (NI)0;
									colontmp__18 = (NI)0;
									T165_ = (NI)0;
									T165_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
									colontmp__18 = (NI)(T165_ - ((NI) 1));
									res_8 = colontmp__18;
									{
										while (1) {
											NI T168_;
											NI T169_;
											NI T170_;
											if (!(((NI) 0) <= res_8)) goto LA167;
											i_26 = res_8;
											T168_ = (NI)0;
											T168_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_26);
											t2_coord_2[(i_26)- 0] = (NI)((NI)(block_offset_2 / z_6) % T168_);
											T169_ = (NI)0;
											T169_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i_26);
											t2_iter_pos_2 += (NI)(t2_coord_2[(i_26)- 0] * T169_);
											T170_ = (NI)0;
											T170_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i_26);
											stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_6), T170_);
											res_8 -= ((NI) 1);
										} LA167: ;
									}
								}
							}
							LA162_: ;
							{
								NI i_27;
								NI colontmp__19;
								NI i_28;
								i_27 = (NI)0;
								colontmp__19 = (NI)0;
								colontmp__19 = (NI)(block_offset_2 + block_size_2);
								i_28 = block_offset_2;
								{
									while (1) {
										if (!(i_28 < colontmp__19)) goto LA173;
										i_27 = i_28;
										x_2 = (&t1data[(t1_iter_pos_2)- 0]);
										y = t2data[(t2_iter_pos_2)- 0];
										(*x_2) = y;
										{
											NI k_4;
											NI colontmp__20;
											NI T175_;
											NI res_9;
											k_4 = (NI)0;
											colontmp__20 = (NI)0;
											T175_ = (NI)0;
											T175_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&(*result)));
											colontmp__20 = (NI)(T175_ - ((NI) 1));
											res_9 = colontmp__20;
											{
												while (1) {
													if (!(((NI) 0) <= res_9)) goto LA177;
													k_4 = res_9;
													{
														NI* T180_;
														NI* T183_;
														T180_ = (NI*)0;
														T180_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).shape), k_4);
														if (!(t1_coord_2[(k_4)- 0] < (NI)((*T180_) - ((NI) 1)))) goto LA181_;
														t1_coord_2[(k_4)- 0] += ((NI) 1);
														T183_ = (NI*)0;
														T183_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&(*result).strides), k_4);
														t1_iter_pos_2 += (*T183_);
														goto LA174;
													}
													goto LA178_;
													LA181_: ;
													{
														t1_coord_2[(k_4)- 0] = ((NI) 0);
														t1_iter_pos_2 -= t1_backstrides_2[(k_4)- 0];
													}
													LA178_: ;
													res_9 -= ((NI) 1);
												} LA177: ;
											}
										} LA174: ;
										{
											NI k_5;
											NI colontmp__21;
											NI T186_;
											NI res_10;
											k_5 = (NI)0;
											colontmp__21 = (NI)0;
											T186_ = (NI)0;
											T186_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t);
											colontmp__21 = (NI)(T186_ - ((NI) 1));
											res_10 = colontmp__21;
											{
												while (1) {
													if (!(((NI) 0) <= res_10)) goto LA188;
													k_5 = res_10;
													{
														NI T191_;
														NI T194_;
														T191_ = (NI)0;
														T191_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), k_5);
														if (!(t2_coord_2[(k_5)- 0] < (NI)(T191_ - ((NI) 1)))) goto LA192_;
														t2_coord_2[(k_5)- 0] += ((NI) 1);
														T194_ = (NI)0;
														T194_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), k_5);
														t2_iter_pos_2 += T194_;
														goto LA185;
													}
													goto LA189_;
													LA192_: ;
													{
														t2_coord_2[(k_5)- 0] = ((NI) 0);
														t2_iter_pos_2 -= t2_backstrides_2[(k_5)- 0];
													}
													LA189_: ;
													res_10 -= ((NI) 1);
												} LA188: ;
											}
										} LA185: ;
										i_28 += ((NI) 1);
									} LA173: ;
								}
							}
						}
						LA63_: ;
					}
				}
			}
		}
		LA58_: ;
	}
	LA1_: ;
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_p_shapeshiftingInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_p_shapeshiftingDatInit000)(void) {
}

