/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_p_accessors_macros_write.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_p_accessors_macros_write.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TGenericSeq TGenericSeq;
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
struct tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg {
NI a;
NI b;
NI step;
NIM_BOOL a_from_end;
NIM_BOOL b_from_end;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, slicer_T9aR1NWbt3fIvTFg84JzL2Q)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg* slices, NI slicesLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = ((NI) 1);
	{
		NI value;
		value = (NI)0;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (*a).len;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA4;
					i = i_2;
					value = (*a).data[(i)- 0];
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&result), value);
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	return result;
}

static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = product_k2YXWcJ5lNu24E2yfX7EKQvectorize((&(*t).shape));
	return result;
}

static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = (NI)((*a).len - ((NI) 1));
	return result;
}

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write((&(*t).shape));
		res = colontmp_;
		{
			while (1) {
				NI T12_;
				if (!(((NI) 0) <= res)) goto LA3;
				i = res;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				res -= ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NF*, dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NF* result;
	result = (NF*)0;
	result = ((NF*) ((&(*t).storage.Fdata->data[(*t).offset])));
	return result;
}

static N_INLINE(NI, rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = (*t).shape.len;
	return result;
}

static N_INLINE(NI*, X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI* result;
	result = (NI*)0;
	result = (&(*a).data[(idx)- 0]);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, slicerMut_l6U8uN9cg40j7SNpXpEi39bA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg* slices, NI slicesLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t2) {
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ sliced;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ T1_;
	NI ompsize;
	memset((void*)(&sliced), 0, sizeof(sliced));
	memset((void*)(&T1_), 0, sizeof(T1_));
	slicer_T9aR1NWbt3fIvTFg84JzL2Q((&(*t)), slices, slicesLen_0, (&T1_));
	sliced.shape = T1_.shape;
	sliced.strides = T1_.strides;
	sliced.offset = T1_.offset;
	sliced.storage.Fdata = T1_.storage.Fdata;
	ompsize = size_9c9bGcb6H7uf0KFeicXmH40Avectorize((&sliced));
	{
		NIM_BOOL T4_;
		T4_ = (NIM_BOOL)0;
		T4_ = likely((((NI) 0) < ompsize));
		if (!T4_) goto LA5_;
		{
			NI block_offset;
			NI block_size;
			block_offset = ((NI) 0);
			block_size = ompsize;
			{
				{
					NF* x;
					NF y;
					NIM_BOOL t1_contiguous;
					NIM_BOOL t2_contiguous;
					NF* t1data;
					NF* t2data;
					x = (NF*)0;
					y = (NF)0;
					t1_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write((&sliced));
					t2_contiguous = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write(t2);
					t1data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write((&sliced));
					t2data = dataArray_VHD2YeTLKVSMO7lZ1My9bfQp_accessors_macros_write(t2);
					{
						NIM_BOOL T12_;
						T12_ = (NIM_BOOL)0;
						T12_ = t1_contiguous;
						if (!(T12_)) goto LA13_;
						T12_ = t2_contiguous;
						LA13_: ;
						if (!T12_) goto LA14_;
						{
							NI i;
							NI colontmp_;
							NI i_2;
							i = (NI)0;
							colontmp_ = (NI)0;
							colontmp_ = (NI)(block_offset + block_size);
							i_2 = block_offset;
							{
								while (1) {
									if (!(i_2 < colontmp_)) goto LA18;
									i = i_2;
									x = (&t1data[(i)- 0]);
									y = t2data[(i)- 0];
									(*x) = y;
									i_2 += ((NI) 1);
								} LA18: ;
							}
						}
					}
					goto LA10_;
					LA14_: ;
					{
						NI t2_iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides;
						if (!t1_contiguous) goto LA20_;
						t2_iter_pos = ((NI) 0);
						{
							NI i_3;
							NI colontmp__2;
							NI i_4;
							i_3 = (NI)0;
							colontmp__2 = (NI)0;
							colontmp__2 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t2);
							i_4 = ((NI) 0);
							{
								while (1) {
									NI T25_;
									NI T26_;
									if (!(i_4 < colontmp__2)) goto LA24;
									i_3 = i_4;
									T25_ = (NI)0;
									T25_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).strides), i_3);
									T26_ = (NI)0;
									T26_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).shape), i_3);
									t2_backstrides[(i_3)- 0] = (NI)(T25_ * (NI)(T26_ - ((NI) 1)));
									t2_coord[(i_3)- 0] = ((NI) 0);
									i_4 += ((NI) 1);
								} LA24: ;
							}
						}
						{
							NI z;
							if (!!((block_offset == ((NI) 0)))) goto LA29_;
							z = ((NI) 1);
							{
								NI i_5;
								NI colontmp__3;
								NI T32_;
								NI res;
								i_5 = (NI)0;
								colontmp__3 = (NI)0;
								T32_ = (NI)0;
								T32_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t2);
								colontmp__3 = (NI)(T32_ - ((NI) 1));
								res = colontmp__3;
								{
									while (1) {
										NI T35_;
										NI T36_;
										NI T37_;
										if (!(((NI) 0) <= res)) goto LA34;
										i_5 = res;
										T35_ = (NI)0;
										T35_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).shape), i_5);
										t2_coord[(i_5)- 0] = (NI)((NI)(block_offset / z) % T35_);
										T36_ = (NI)0;
										T36_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).strides), i_5);
										t2_iter_pos += (NI)(t2_coord[(i_5)- 0] * T36_);
										T37_ = (NI)0;
										T37_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).shape), i_5);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T37_);
										res -= ((NI) 1);
									} LA34: ;
								}
							}
						}
						LA29_: ;
						{
							NI i_6;
							NI colontmp__4;
							NI i_7;
							i_6 = (NI)0;
							colontmp__4 = (NI)0;
							colontmp__4 = (NI)(block_offset + block_size);
							i_7 = block_offset;
							{
								while (1) {
									if (!(i_7 < colontmp__4)) goto LA40;
									i_6 = i_7;
									x = (&t1data[(i_6)- 0]);
									y = t2data[(t2_iter_pos)- 0];
									(*x) = y;
									{
										NI k;
										NI colontmp__5;
										NI T42_;
										NI res_2;
										k = (NI)0;
										colontmp__5 = (NI)0;
										T42_ = (NI)0;
										T42_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t2);
										colontmp__5 = (NI)(T42_ - ((NI) 1));
										res_2 = colontmp__5;
										{
											while (1) {
												if (!(((NI) 0) <= res_2)) goto LA44;
												k = res_2;
												{
													NI T47_;
													NI T50_;
													T47_ = (NI)0;
													T47_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).shape), k);
													if (!(t2_coord[(k)- 0] < (NI)(T47_ - ((NI) 1)))) goto LA48_;
													t2_coord[(k)- 0] += ((NI) 1);
													T50_ = (NI)0;
													T50_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).strides), k);
													t2_iter_pos += T50_;
													goto LA41;
												}
												goto LA45_;
												LA48_: ;
												{
													t2_coord[(k)- 0] = ((NI) 0);
													t2_iter_pos -= t2_backstrides[(k)- 0];
												}
												LA45_: ;
												res_2 -= ((NI) 1);
											} LA44: ;
										}
									} LA41: ;
									i_7 += ((NI) 1);
								} LA40: ;
							}
						}
					}
					goto LA10_;
					LA20_: ;
					{
						NI t1_iter_pos;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides;
						if (!t2_contiguous) goto LA53_;
						t1_iter_pos = ((NI) 0);
						{
							NI i_8;
							NI colontmp__6;
							NI i_9;
							i_8 = (NI)0;
							colontmp__6 = (NI)0;
							colontmp__6 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&sliced));
							i_9 = ((NI) 0);
							{
								while (1) {
									NI* T58_;
									NI* T59_;
									if (!(i_9 < colontmp__6)) goto LA57;
									i_8 = i_9;
									T58_ = (NI*)0;
									T58_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.strides), i_8);
									T59_ = (NI*)0;
									T59_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.shape), i_8);
									t1_backstrides[(i_8)- 0] = (NI)((*T58_) * (NI)((*T59_) - ((NI) 1)));
									t1_coord[(i_8)- 0] = ((NI) 0);
									i_9 += ((NI) 1);
								} LA57: ;
							}
						}
						{
							NI z_2;
							if (!!((block_offset == ((NI) 0)))) goto LA62_;
							z_2 = ((NI) 1);
							{
								NI i_10;
								NI colontmp__7;
								NI T65_;
								NI res_3;
								i_10 = (NI)0;
								colontmp__7 = (NI)0;
								T65_ = (NI)0;
								T65_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&sliced));
								colontmp__7 = (NI)(T65_ - ((NI) 1));
								res_3 = colontmp__7;
								{
									while (1) {
										NI* T68_;
										NI* T69_;
										NI* T70_;
										if (!(((NI) 0) <= res_3)) goto LA67;
										i_10 = res_3;
										T68_ = (NI*)0;
										T68_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.shape), i_10);
										t1_coord[(i_10)- 0] = (NI)((NI)(block_offset / z_2) % (*T68_));
										T69_ = (NI*)0;
										T69_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.strides), i_10);
										t1_iter_pos += (NI)(t1_coord[(i_10)- 0] * (*T69_));
										T70_ = (NI*)0;
										T70_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.shape), i_10);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_2), (*T70_));
										res_3 -= ((NI) 1);
									} LA67: ;
								}
							}
						}
						LA62_: ;
						{
							NI i_11;
							NI colontmp__8;
							NI i_12;
							i_11 = (NI)0;
							colontmp__8 = (NI)0;
							colontmp__8 = (NI)(block_offset + block_size);
							i_12 = block_offset;
							{
								while (1) {
									if (!(i_12 < colontmp__8)) goto LA73;
									i_11 = i_12;
									x = (&t1data[(t1_iter_pos)- 0]);
									y = t2data[(i_11)- 0];
									(*x) = y;
									{
										NI k_2;
										NI colontmp__9;
										NI T75_;
										NI res_4;
										k_2 = (NI)0;
										colontmp__9 = (NI)0;
										T75_ = (NI)0;
										T75_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&sliced));
										colontmp__9 = (NI)(T75_ - ((NI) 1));
										res_4 = colontmp__9;
										{
											while (1) {
												if (!(((NI) 0) <= res_4)) goto LA77;
												k_2 = res_4;
												{
													NI* T80_;
													NI* T83_;
													T80_ = (NI*)0;
													T80_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.shape), k_2);
													if (!(t1_coord[(k_2)- 0] < (NI)((*T80_) - ((NI) 1)))) goto LA81_;
													t1_coord[(k_2)- 0] += ((NI) 1);
													T83_ = (NI*)0;
													T83_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.strides), k_2);
													t1_iter_pos += (*T83_);
													goto LA74;
												}
												goto LA78_;
												LA81_: ;
												{
													t1_coord[(k_2)- 0] = ((NI) 0);
													t1_iter_pos -= t1_backstrides[(k_2)- 0];
												}
												LA78_: ;
												res_4 -= ((NI) 1);
											} LA77: ;
										}
									} LA74: ;
									i_12 += ((NI) 1);
								} LA73: ;
							}
						}
					}
					goto LA10_;
					LA53_: ;
					{
						NI t1_iter_pos_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_coord_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t1_backstrides_2;
						NI t2_iter_pos_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_coord_2;
						tyArray_7faYhUidbIkFZQJndG6Ggw t2_backstrides_2;
						t1_iter_pos_2 = ((NI) 0);
						{
							NI i_13;
							NI colontmp__10;
							NI i_14;
							i_13 = (NI)0;
							colontmp__10 = (NI)0;
							colontmp__10 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&sliced));
							i_14 = ((NI) 0);
							{
								while (1) {
									NI* T89_;
									NI* T90_;
									if (!(i_14 < colontmp__10)) goto LA88;
									i_13 = i_14;
									T89_ = (NI*)0;
									T89_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.strides), i_13);
									T90_ = (NI*)0;
									T90_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.shape), i_13);
									t1_backstrides_2[(i_13)- 0] = (NI)((*T89_) * (NI)((*T90_) - ((NI) 1)));
									t1_coord_2[(i_13)- 0] = ((NI) 0);
									i_14 += ((NI) 1);
								} LA88: ;
							}
						}
						{
							NI z_3;
							if (!!((block_offset == ((NI) 0)))) goto LA93_;
							z_3 = ((NI) 1);
							{
								NI i_15;
								NI colontmp__11;
								NI T96_;
								NI res_5;
								i_15 = (NI)0;
								colontmp__11 = (NI)0;
								T96_ = (NI)0;
								T96_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&sliced));
								colontmp__11 = (NI)(T96_ - ((NI) 1));
								res_5 = colontmp__11;
								{
									while (1) {
										NI* T99_;
										NI* T100_;
										NI* T101_;
										if (!(((NI) 0) <= res_5)) goto LA98;
										i_15 = res_5;
										T99_ = (NI*)0;
										T99_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.shape), i_15);
										t1_coord_2[(i_15)- 0] = (NI)((NI)(block_offset / z_3) % (*T99_));
										T100_ = (NI*)0;
										T100_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.strides), i_15);
										t1_iter_pos_2 += (NI)(t1_coord_2[(i_15)- 0] * (*T100_));
										T101_ = (NI*)0;
										T101_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.shape), i_15);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_3), (*T101_));
										res_5 -= ((NI) 1);
									} LA98: ;
								}
							}
						}
						LA93_: ;
						t2_iter_pos_2 = ((NI) 0);
						{
							NI i_16;
							NI colontmp__12;
							NI i_17;
							i_16 = (NI)0;
							colontmp__12 = (NI)0;
							colontmp__12 = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t2);
							i_17 = ((NI) 0);
							{
								while (1) {
									NI T105_;
									NI T106_;
									if (!(i_17 < colontmp__12)) goto LA104;
									i_16 = i_17;
									T105_ = (NI)0;
									T105_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).strides), i_16);
									T106_ = (NI)0;
									T106_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).shape), i_16);
									t2_backstrides_2[(i_16)- 0] = (NI)(T105_ * (NI)(T106_ - ((NI) 1)));
									t2_coord_2[(i_16)- 0] = ((NI) 0);
									i_17 += ((NI) 1);
								} LA104: ;
							}
						}
						{
							NI z_4;
							if (!!((block_offset == ((NI) 0)))) goto LA109_;
							z_4 = ((NI) 1);
							{
								NI i_18;
								NI colontmp__13;
								NI T112_;
								NI res_6;
								i_18 = (NI)0;
								colontmp__13 = (NI)0;
								T112_ = (NI)0;
								T112_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t2);
								colontmp__13 = (NI)(T112_ - ((NI) 1));
								res_6 = colontmp__13;
								{
									while (1) {
										NI T115_;
										NI T116_;
										NI T117_;
										if (!(((NI) 0) <= res_6)) goto LA114;
										i_18 = res_6;
										T115_ = (NI)0;
										T115_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).shape), i_18);
										t2_coord_2[(i_18)- 0] = (NI)((NI)(block_offset / z_4) % T115_);
										T116_ = (NI)0;
										T116_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).strides), i_18);
										t2_iter_pos_2 += (NI)(t2_coord_2[(i_18)- 0] * T116_);
										T117_ = (NI)0;
										T117_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).shape), i_18);
										stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z_4), T117_);
										res_6 -= ((NI) 1);
									} LA114: ;
								}
							}
						}
						LA109_: ;
						{
							NI i_19;
							NI colontmp__14;
							NI i_20;
							i_19 = (NI)0;
							colontmp__14 = (NI)0;
							colontmp__14 = (NI)(block_offset + block_size);
							i_20 = block_offset;
							{
								while (1) {
									if (!(i_20 < colontmp__14)) goto LA120;
									i_19 = i_20;
									x = (&t1data[(t1_iter_pos_2)- 0]);
									y = t2data[(t2_iter_pos_2)- 0];
									(*x) = y;
									{
										NI k_3;
										NI colontmp__15;
										NI T122_;
										NI res_7;
										k_3 = (NI)0;
										colontmp__15 = (NI)0;
										T122_ = (NI)0;
										T122_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write((&sliced));
										colontmp__15 = (NI)(T122_ - ((NI) 1));
										res_7 = colontmp__15;
										{
											while (1) {
												if (!(((NI) 0) <= res_7)) goto LA124;
												k_3 = res_7;
												{
													NI* T127_;
													NI* T130_;
													T127_ = (NI*)0;
													T127_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.shape), k_3);
													if (!(t1_coord_2[(k_3)- 0] < (NI)((*T127_) - ((NI) 1)))) goto LA128_;
													t1_coord_2[(k_3)- 0] += ((NI) 1);
													T130_ = (NI*)0;
													T130_ = X5BX5D__BzaB3OiBv9aAFFPYkpdgGwgp_accessors_macros_read((&sliced.strides), k_3);
													t1_iter_pos_2 += (*T130_);
													goto LA121;
												}
												goto LA125_;
												LA128_: ;
												{
													t1_coord_2[(k_3)- 0] = ((NI) 0);
													t1_iter_pos_2 -= t1_backstrides_2[(k_3)- 0];
												}
												LA125_: ;
												res_7 -= ((NI) 1);
											} LA124: ;
										}
									} LA121: ;
									{
										NI k_4;
										NI colontmp__16;
										NI T133_;
										NI res_8;
										k_4 = (NI)0;
										colontmp__16 = (NI)0;
										T133_ = (NI)0;
										T133_ = rank_9c9bGcb6H7uf0KFeicXmH40Ap_accessors_macros_write(t2);
										colontmp__16 = (NI)(T133_ - ((NI) 1));
										res_8 = colontmp__16;
										{
											while (1) {
												if (!(((NI) 0) <= res_8)) goto LA135;
												k_4 = res_8;
												{
													NI T138_;
													NI T141_;
													T138_ = (NI)0;
													T138_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).shape), k_4);
													if (!(t2_coord_2[(k_4)- 0] < (NI)(T138_ - ((NI) 1)))) goto LA139_;
													t2_coord_2[(k_4)- 0] += ((NI) 1);
													T141_ = (NI)0;
													T141_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t2).strides), k_4);
													t2_iter_pos_2 += T141_;
													goto LA132;
												}
												goto LA136_;
												LA139_: ;
												{
													t2_coord_2[(k_4)- 0] = ((NI) 0);
													t2_iter_pos_2 -= t2_backstrides_2[(k_4)- 0];
												}
												LA136_: ;
												res_8 -= ((NI) 1);
											} LA135: ;
										}
									} LA132: ;
									i_20 += ((NI) 1);
								} LA120: ;
							}
						}
					}
					LA10_: ;
				}
			}
		}
	}
	LA5_: ;
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_p_accessors_macros_writeInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_p_accessors_macros_writeDatInit000)(void) {
}

