/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_data_structure.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_data_structure.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct TGenericSeq TGenericSeq;
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg;
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op);
static N_INLINE(void, X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx, NI v);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
TNimType NTI_urhjHEwA2NkLvIUFwuBxiQ_;
extern TNimType NTI_sGjc7KeArQw8Nb9cdBLtCaw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_M9ai5QMEb9bZ9cMikEuLTKxTQ_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
static N_NIMCALL(void, Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA)(void* p, NI op) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* a;
	NI T1_;
	a = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)p;
	T1_ = (NI)0;
}

static N_INLINE(void, X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx, NI v) {
	(*a).data[(idx)- 0] = v;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* result) {
	NI accum;
{	accum = ((NI) 1);
	(*result).len = (*shape).len;
	{
		if (!(layout == ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101))) goto LA3_;
		{
			NI i;
			NI colontmp_;
			NI res;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (NI)((*shape).len - ((NI) 1));
			res = colontmp_;
			{
				while (1) {
					NI T8_;
					if (!(((NI) 0) <= res)) goto LA7;
					i = res;
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure(result, i, accum);
					T8_ = (NI)0;
					T8_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure(shape, i);
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&accum), T8_);
					res -= ((NI) 1);
				} LA7: ;
			}
		}
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NI i_2;
		NI colontmp__2;
		NI i_3;
		i_2 = (NI)0;
		colontmp__2 = (NI)0;
		colontmp__2 = (*shape).len;
		i_3 = ((NI) 0);
		{
			while (1) {
				NI T12_;
				if (!(i_3 < colontmp__2)) goto LA11;
				i_2 = i_3;
				X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure(result, i_2, accum);
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure(shape, i_2);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&accum), T12_);
				i_3 += ((NI) 1);
			} LA11: ;
		}
	}
	goto BeforeRet_;
	}BeforeRet_: ;
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_data_structureInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_data_structureDatInit000)(void) {
static TNimNode* TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_2[4];
static TNimNode TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[6];
NTI_urhjHEwA2NkLvIUFwuBxiQ_.size = sizeof(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ);
NTI_urhjHEwA2NkLvIUFwuBxiQ_.kind = 18;
NTI_urhjHEwA2NkLvIUFwuBxiQ_.base = 0;
NTI_urhjHEwA2NkLvIUFwuBxiQ_.flags = 2;
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_2[0] = &TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[1];
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[1].kind = 1;
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[1].offset = offsetof(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ, shape);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[1].typ = (&NTI_sGjc7KeArQw8Nb9cdBLtCaw_);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[1].name = "shape";
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_2[1] = &TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[2];
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[2].kind = 1;
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[2].offset = offsetof(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ, strides);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[2].typ = (&NTI_sGjc7KeArQw8Nb9cdBLtCaw_);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[2].name = "strides";
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_2[2] = &TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[3];
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[3].kind = 1;
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[3].offset = offsetof(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ, offset);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[3].name = "offset";
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_2[3] = &TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[4];
NTI_M9ai5QMEb9bZ9cMikEuLTKxTQ_.size = sizeof(tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ);
NTI_M9ai5QMEb9bZ9cMikEuLTKxTQ_.kind = 18;
NTI_M9ai5QMEb9bZ9cMikEuLTKxTQ_.base = 0;
NTI_M9ai5QMEb9bZ9cMikEuLTKxTQ_.flags = 2;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.size = sizeof(tySequence_Zj5xKXgsXnI4n4hPS6nACA*);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.kind = 24;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_Zj5xKXgsXnI4n4hPS6nACA_.flags = 2;
NTI_Zj5xKXgsXnI4n4hPS6nACA_.marker = Marker_tySequence_Zj5xKXgsXnI4n4hPS6nACA;
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[5].kind = 1;
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[5].offset = offsetof(tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ, Fdata);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[5].typ = (&NTI_Zj5xKXgsXnI4n4hPS6nACA_);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[5].name = "Fdata";
NTI_M9ai5QMEb9bZ9cMikEuLTKxTQ_.node = &TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[5];
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[4].kind = 1;
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[4].offset = offsetof(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ, storage);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[4].typ = (&NTI_M9ai5QMEb9bZ9cMikEuLTKxTQ_);
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[4].name = "storage";
TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[0].len = 4; TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[0].kind = 2; TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[0].sons = &TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_2[0];
NTI_urhjHEwA2NkLvIUFwuBxiQ_.node = &TM_R9aI6cK2sKUP9cKb9aXJ7kmRg_0[0];
}

