/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_shapeshifting.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/arraymancer_shapeshifting.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_SxW2aYvggKVwFUyXX1AjXA tySequence_SxW2aYvggKVwFUyXX1AjXA;
typedef struct tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg;
typedef struct tyTuple_ZqtwwojkKZ9bCA58nE5quMA tyTuple_ZqtwwojkKZ9bCA58nE5quMA;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NU8 tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg;
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg {
NI a;
NI b;
NI step;
NIM_BOOL a_from_end;
NIM_BOOL b_from_end;
};
struct tyTuple_ZqtwwojkKZ9bCA58nE5quMA {
tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ Field0;
tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ Field1;
};
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
struct tySequence_SxW2aYvggKVwFUyXX1AjXA {
  TGenericSeq Sup;
  tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
static N_INLINE(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw, amp__Ips9bwFHrIX6rSlYPxE9bPBgshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* b);
static N_INLINE(void, X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx, NI v);
static N_INLINE(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw, amp__TOjJ20TuL4jRu4dv9aAx9bUQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI value);
static N_INLINE(void, add_a9bUxVL9cOPtb4G5qorPvQFwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI value);
static N_INLINE(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw, X5BX5D__OoS4dD6CJIWv4xdZIS9cmqAshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA slice);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qshapeshifting)(NI a, NI b);
static N_INLINE(void, newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
static N_INLINE(void, tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* out_shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout);
static N_INLINE(void, copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* s);
N_LIB_PRIVATE N_NIMCALL(void, shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* result);
static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting)(NI len);
N_NIMCALL(void*, nimNewSeqOfCap)(TNimType* typ, NI cap);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tySequence_SxW2aYvggKVwFUyXX1AjXA*, newSeq_peIRSE1mVPDhJfPEUfy84Q)(NI len);
static N_INLINE(tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg, bar__AAWg6UBiP1ZXuvNGjYCf5gshapeshifting)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA s, NI step);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, slicerMut_l6U8uN9cg40j7SNpXpEi39bA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg* slices, NI slicesLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t2);
N_LIB_PRIVATE N_NIMCALL(void, reshapeImpl_BM8u7EiCpktujgIBsWNNxQ)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* new_shape, NI new_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result);
N_LIB_PRIVATE N_NIMCALL(void, broadcast2Impl_ZE7WYwzEy0uEQgPiRfB1dA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* b, tyTuple_ZqtwwojkKZ9bCA58nE5quMA* result);
static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(NIM_BOOL, is_F_contiguous_rS8xRFMCajURo6KXS4BJfQ_2p_shapeshifting)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
N_LIB_PRIVATE N_NIMCALL(void, contiguousImpl_Svljdva1cfcaVIAOz2N6GA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result);
extern TNimType NTI_urhjHEwA2NkLvIUFwuBxiQ_;
extern TNimType NTI_Zj5xKXgsXnI4n4hPS6nACA_;
extern TNimType NTI_SxW2aYvggKVwFUyXX1AjXA_;
TNimType NTI_ZqtwwojkKZ9bCA58nE5quMA_;

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(void, X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx, NI v) {
	(*a).data[(idx)- 0] = v;
}

static N_INLINE(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw, amp__Ips9bwFHrIX6rSlYPxE9bPBgshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* b) {
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw result;
	memset((void*)(&result), 0, sizeof(result));
	result = (*a);
	result.len += (*b).len;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (*b).len;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI T4_;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				T4_ = (NI)0;
				T4_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure(b, i);
				X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&result), (NI)((*a).len + i), T4_);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

static N_INLINE(void, add_a9bUxVL9cOPtb4G5qorPvQFwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI value) {
	X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure(a, (*a).len, value);
	(*a).len += ((NI) 1);
}

static N_INLINE(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw, amp__TOjJ20TuL4jRu4dv9aAx9bUQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI value) {
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw result;
	memset((void*)(&result), 0, sizeof(result));
	result = (*a);
	add_a9bUxVL9cOPtb4G5qorPvQFwshapeshifting((&result), value);
	return result;
}

static N_INLINE(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw, X5BX5D__OoS4dD6CJIWv4xdZIS9cmqAshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA slice) {
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw result;
	NI bgn_slice;
	NI end_slice;
	memset((void*)(&result), 0, sizeof(result));
	bgn_slice = slice.a;
	end_slice = slice.b;
	{
		if (!(bgn_slice <= end_slice)) goto LA3_;
		result.len = (NI)((NI)(end_slice - bgn_slice) + ((NI) 1));
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = result.len;
			i_2 = ((NI) 0);
			{
				while (1) {
					NI T8_;
					if (!(i_2 < colontmp_)) goto LA7;
					i = i_2;
					T8_ = (NI)0;
					T8_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure(a, (NI)(bgn_slice + i));
					X5BX5Deq__pQwD7xewb0Hj1D5dhH5Glwdata_structure((&result), i, T8_);
					i_2 += ((NI) 1);
				} LA7: ;
			}
		}
	}
	LA3_: ;
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qshapeshifting)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

static N_INLINE(void, copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* s) {
	(*a).len = (*s).len;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (*s).len;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				(*a).data[(i)- 0] = (*s).data[(i)- 0];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

static N_INLINE(void, tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* out_shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout) {
	copyFrom_uWn9aglCATEW9asE9aJgg8UYQshapeshifting((&(*result).shape), out_shape);
	shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A((&(*result).shape), layout, (&(*result).strides));
	(*result).offset = ((NI) 0);
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting)(NI len) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA* result;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)0;
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*)nimNewSeqOfCap((&NTI_Zj5xKXgsXnI4n4hPS6nACA_), len);
	result = (tySequence_Zj5xKXgsXnI4n4hPS6nACA*) setLengthSeq(&(result)->Sup, sizeof(NF), len);
	return result;
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = ((NI) 1);
	{
		NI value;
		value = (NI)0;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (*a).len;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA4;
					i = i_2;
					value = (*a).data[(i)- 0];
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&result), value);
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	return result;
}

static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = product_k2YXWcJ5lNu24E2yfX7EKQvectorize((&(*t).shape));
	return result;
}

static N_INLINE(void, newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NI T1_;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	tensorCpu_xZTr1zxLZODLYPttVydpgwshapeshifting(shape, Result, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101));
	T1_ = (NI)0;
	T1_ = size_9c9bGcb6H7uf0KFeicXmH40Avectorize(Result);
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), newSeqUninit_kMN89ardQ9aDxW1PyJ4VvCawshapeshifting(((NI) (T1_))));
}

static N_INLINE(tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg, bar__AAWg6UBiP1ZXuvNGjYCf5gshapeshifting)(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA s, NI step) {
	tyObject_SteppedSlice_r4gi6b3i9cwWvbDTx29bhqpg result;
{	memset((void*)(&result), 0, sizeof(result));
	memset((void*)(&result), 0, sizeof(result));
	result.a = s.a;
	result.b = s.b;
	result.step = step;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, concat_pmbof8Q9afJfnTHRpwvM0UA)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t_list, NI t_listLen_0, NI axis, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NI axis_dim;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ t0;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw concat_shape;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T5_;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw T6_;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw T7_;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T8_;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw T9_;
	tySequence_SxW2aYvggKVwFUyXX1AjXA* slices;
	tySequence_SxW2aYvggKVwFUyXX1AjXA* result_2;
	tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw t_2;
	NI i_2;
	NI iaxis;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	axis_dim = ((NI) 0);
	memset((void*)(&t0), 0, sizeof(t0));
	t0.shape = t_list[((NI) 0)].shape;
	t0.strides = t_list[((NI) 0)].strides;
	t0.offset = t_list[((NI) 0)].offset;
	t0.storage.Fdata = t_list[((NI) 0)].storage.Fdata;
	{
		tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ t;
		NI i;
		memset((void*)(&t), 0, sizeof(t));
		i = ((NI) 0);
		{
			while (1) {
				NI T4_;
				if (!(i < t_listLen_0)) goto LA3;
				t.shape = t_list[i].shape;
				t.strides = t_list[i].strides;
				t.offset = t_list[i].offset;
				t.storage.Fdata = t_list[i].storage.Fdata;
				T4_ = (NI)0;
				T4_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&t.shape), axis);
				axis_dim += T4_;
				i += ((NI) 1);
			} LA3: ;
		}
	}
	T5_ = dotdot__vDQySKWzgnxQdUarow6k5Qshapeshifting(((NI) 0), (NI)(axis - ((NI) 1)));
	T6_ = X5BX5D__OoS4dD6CJIWv4xdZIS9cmqAshapeshifting((&t0.shape), T5_);
	T7_ = amp__TOjJ20TuL4jRu4dv9aAx9bUQshapeshifting((&T6_), axis_dim);
	T8_ = dotdot__vDQySKWzgnxQdUarow6k5Qshapeshifting((NI)(axis + ((NI) 1)), (NI)(t0.shape.len - ((NI) 1)));
	T9_ = X5BX5D__OoS4dD6CJIWv4xdZIS9cmqAshapeshifting((&t0.shape), T8_);
	concat_shape = amp__Ips9bwFHrIX6rSlYPxE9bPBgshapeshifting((&T7_), (&T9_));
	newTensorUninit_SSeCfVaTJSvl349auD9ciq0wshapeshifting((&concat_shape), Result);
	result_2 = (tySequence_SxW2aYvggKVwFUyXX1AjXA*)0;
	t_2 = concat_shape;
	i_2 = ((NI) 0);
	result_2 = newSeq_peIRSE1mVPDhJfPEUfy84Q(((NI) (concat_shape.len)));
	{
		NI it;
		it = (NI)0;
		{
			NI i_3;
			NI colontmp_;
			NI i_4;
			i_3 = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = t_2.len;
			i_4 = ((NI) 0);
			{
				while (1) {
					tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T14_;
					if (!(i_4 < colontmp_)) goto LA13;
					i_3 = i_4;
					it = t_2.data[(i_3)- 0];
					T14_ = dotdot__vDQySKWzgnxQdUarow6k5Qshapeshifting(((NI) 0), (NI)(it - ((NI) 1)));
					result_2->data[i_2] = bar__AAWg6UBiP1ZXuvNGjYCf5gshapeshifting(T14_, ((NI) 1));
					i_2 += ((NI) 1);
					i_4 += ((NI) 1);
				} LA13: ;
			}
		}
	}
	genericSeqAssign((&slices), result_2, (&NTI_SxW2aYvggKVwFUyXX1AjXA_));
	iaxis = ((NI) 0);
	{
		tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ t_3;
		NI i_5;
		memset((void*)(&t_3), 0, sizeof(t_3));
		i_5 = ((NI) 0);
		{
			while (1) {
				NI T18_;
				NI T19_;
				if (!(i_5 < t_listLen_0)) goto LA17;
				t_3.shape = t_list[i_5].shape;
				t_3.strides = t_list[i_5].strides;
				t_3.offset = t_list[i_5].offset;
				t_3.storage.Fdata = t_list[i_5].storage.Fdata;
				slices->data[axis].a = iaxis;
				T18_ = (NI)0;
				T18_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&t_3.shape), axis);
				slices->data[axis].b = (NI)((NI)(iaxis + T18_) - ((NI) 1));
				slicerMut_l6U8uN9cg40j7SNpXpEi39bA(Result, slices->data, slices->Sup.len, (&t_3));
				T19_ = (NI)0;
				T19_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&t_3.shape), axis);
				iaxis += T19_;
				i_5 += ((NI) 1);
			} LA17: ;
		}
	}
}

N_LIB_PRIVATE N_NIMCALL(void, reshape_CcfajccAdxdySTfWpwLUgw)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* new_shape, NI new_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	reshapeImpl_BM8u7EiCpktujgIBsWNNxQ(t, new_shape, new_shapeLen_0, Result);
}

N_LIB_PRIVATE N_NIMCALL(void, broadcast2_9cisCuLqWVGwqHwLLd3eV5A)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* a, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* b, tyTuple_ZqtwwojkKZ9bCA58nE5quMA* Result) {
	genericReset((void*)Result, (&NTI_ZqtwwojkKZ9bCA58nE5quMA_));
	broadcast2Impl_ZE7WYwzEy0uEQgPiRfB1dA(a, b, Result);
	unsureAsgnRef((void**) (&(*Result).Field0.storage.Fdata), (*a).storage.Fdata);
	unsureAsgnRef((void**) (&(*Result).Field1.storage.Fdata), (*b).storage.Fdata);
}

static N_INLINE(NI, high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = (NI)((*a).len - ((NI) 1));
	return result;
}

static N_INLINE(NIM_BOOL, is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = high_k2YXWcJ5lNu24E2yfX7EKQp_accessors_macros_write((&(*t).shape));
		res = colontmp_;
		{
			while (1) {
				NI T12_;
				if (!(((NI) 0) <= res)) goto LA3;
				i = res;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				res -= ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, is_F_contiguous_rS8xRFMCajURo6KXS4BJfQ_2p_shapeshifting)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NIM_BOOL result;
	NI z;
{	result = (NIM_BOOL)0;
	z = ((NI) 1);
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (*t).shape.len;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI T12_;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				{
					NIM_BOOL T6_;
					NI T7_;
					NI T9_;
					T6_ = (NIM_BOOL)0;
					T7_ = (NI)0;
					T7_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
					T6_ = !((T7_ == ((NI) 1)));
					if (!(T6_)) goto LA8_;
					T9_ = (NI)0;
					T9_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
					T6_ = !((T9_ == z));
					LA8_: ;
					if (!T6_) goto LA10_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA10_: ;
				T12_ = (NI)0;
				T12_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).shape), i);
				stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&z), T12_);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, asContiguous_3BZwdaXStdH0qceZAOttRw)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, NIM_BOOL force, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NIM_BOOL cCont;
	NIM_BOOL fCont;
{	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	cCont = is_C_contiguous_rS8xRFMCajURo6KXS4BJfQp_accessors_macros_write(t);
	fCont = is_F_contiguous_rS8xRFMCajURo6KXS4BJfQ_2p_shapeshifting(t);
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = cCont;
		if (T4_) goto LA5_;
		T4_ = fCont;
		LA5_: ;
		T3_ = T4_;
		if (!(T3_)) goto LA6_;
		T3_ = !(force);
		LA6_: ;
		if (!T3_) goto LA7_;
		(*Result).shape = (*t).shape;
		(*Result).strides = (*t).strides;
		(*Result).offset = (*t).offset;
		unsureAsgnRef((void**) (&(*Result).storage.Fdata), (*t).storage.Fdata);
		goto BeforeRet_;
	}
	goto LA1_;
	LA7_: ;
	{
		NIM_BOOL T10_;
		T10_ = (NIM_BOOL)0;
		T10_ = cCont;
		if (!(T10_)) goto LA11_;
		T10_ = (layout == ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101));
		LA11_: ;
		if (!T10_) goto LA12_;
		(*Result).shape = (*t).shape;
		(*Result).strides = (*t).strides;
		(*Result).offset = (*t).offset;
		unsureAsgnRef((void**) (&(*Result).storage.Fdata), (*t).storage.Fdata);
		goto BeforeRet_;
	}
	goto LA1_;
	LA12_: ;
	{
		NIM_BOOL T15_;
		T15_ = (NIM_BOOL)0;
		T15_ = fCont;
		if (!(T15_)) goto LA16_;
		T15_ = (layout == ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 102));
		LA16_: ;
		if (!T15_) goto LA17_;
		(*Result).shape = (*t).shape;
		(*Result).strides = (*t).strides;
		(*Result).offset = (*t).offset;
		unsureAsgnRef((void**) (&(*Result).storage.Fdata), (*t).storage.Fdata);
		goto BeforeRet_;
	}
	goto LA1_;
	LA17_: ;
	LA1_: ;
	contiguousImpl_Svljdva1cfcaVIAOz2N6GA(t, layout, Result);
	}BeforeRet_: ;
}
NIM_EXTERNC N_NOINLINE(void, arraymancer_shapeshiftingInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, arraymancer_shapeshiftingDatInit000)(void) {
static TNimNode* TM_jJucZAkHHSxt9aAOnSjPlPg_2[2];
static TNimNode TM_jJucZAkHHSxt9aAOnSjPlPg_0[3];
NTI_ZqtwwojkKZ9bCA58nE5quMA_.size = sizeof(tyTuple_ZqtwwojkKZ9bCA58nE5quMA);
NTI_ZqtwwojkKZ9bCA58nE5quMA_.kind = 18;
NTI_ZqtwwojkKZ9bCA58nE5quMA_.base = 0;
NTI_ZqtwwojkKZ9bCA58nE5quMA_.flags = 2;
TM_jJucZAkHHSxt9aAOnSjPlPg_2[0] = &TM_jJucZAkHHSxt9aAOnSjPlPg_0[1];
TM_jJucZAkHHSxt9aAOnSjPlPg_0[1].kind = 1;
TM_jJucZAkHHSxt9aAOnSjPlPg_0[1].offset = offsetof(tyTuple_ZqtwwojkKZ9bCA58nE5quMA, Field0);
TM_jJucZAkHHSxt9aAOnSjPlPg_0[1].typ = (&NTI_urhjHEwA2NkLvIUFwuBxiQ_);
TM_jJucZAkHHSxt9aAOnSjPlPg_0[1].name = "Field0";
TM_jJucZAkHHSxt9aAOnSjPlPg_2[1] = &TM_jJucZAkHHSxt9aAOnSjPlPg_0[2];
TM_jJucZAkHHSxt9aAOnSjPlPg_0[2].kind = 1;
TM_jJucZAkHHSxt9aAOnSjPlPg_0[2].offset = offsetof(tyTuple_ZqtwwojkKZ9bCA58nE5quMA, Field1);
TM_jJucZAkHHSxt9aAOnSjPlPg_0[2].typ = (&NTI_urhjHEwA2NkLvIUFwuBxiQ_);
TM_jJucZAkHHSxt9aAOnSjPlPg_0[2].name = "Field1";
TM_jJucZAkHHSxt9aAOnSjPlPg_0[0].len = 2; TM_jJucZAkHHSxt9aAOnSjPlPg_0[0].kind = 2; TM_jJucZAkHHSxt9aAOnSjPlPg_0[0].sons = &TM_jJucZAkHHSxt9aAOnSjPlPg_2[0];
NTI_ZqtwwojkKZ9bCA58nE5quMA_.node = &TM_jJucZAkHHSxt9aAOnSjPlPg_0[0];
}

