/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/hasher.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/hasher.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw;
typedef struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ;
typedef struct tySequence_Zj5xKXgsXnI4n4hPS6nACA tySequence_Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg;
typedef NI tyArray_7faYhUidbIkFZQJndG6Ggw[7];
struct tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw {
tyArray_7faYhUidbIkFZQJndG6Ggw data;
NI len;
};
struct tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ {
tySequence_Zj5xKXgsXnI4n4hPS6nACA* Fdata;
};
struct tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ {
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw shape;
tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw strides;
NI offset;
tyObject_CpuStorage_M9ai5QMEb9bZ9cMikEuLTKxTQ storage;
};
typedef NI tyArray_GAcaPw08Gj9cXYhAaMMr9cfw[1];
typedef NI64 tyArray_EawPLnQhPqWwYm5GdCoh8A[2];
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
typedef NI tyArray_HU7qaqKu9czJLT84iCBJnsA[2];
struct tySequence_Zj5xKXgsXnI4n4hPS6nACA {
  TGenericSeq Sup;
  NF data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_INLINE(void, newTensor_8IqP8DVP9clOgUGmzYBEvMgvectorize)(NI* shape, NI shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
static N_INLINE(void, tensorCpu_cwvbRqbkqB6HikRuAXFeWQvectorize)(NI* out_shape, NI out_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout);
static N_INLINE(void, copyFrom_87gws0flOBNTaof6z6y4kwvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI* s, NI sLen_0);
N_LIB_PRIVATE N_NIMCALL(void, shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* shape, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout, tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* result);
N_LIB_PRIVATE N_NIMCALL(tySequence_Zj5xKXgsXnI4n4hPS6nACA*, newSeq_QEg0mebvlEuej5bmGcaclQ)(NI len);
static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a);
static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NI, hashSubstring_sXbP7ngYY7f19cFmFlc5VwQ)(NimStringDesc* s, NI a, NI b, NI nFeatures);
N_LIB_PRIVATE N_NIMCALL(void, murmur_hash_avQi9ckmRChhS4U83NwRMuQ)(NimStringDesc* key, NU32 seed, tyArray_EawPLnQhPqWwYm5GdCoh8A Result);
static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bghasher)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qshapeshifting)(NI a, NI b);
static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAwhasher)(NF* x, NF y);
static N_INLINE(NF*, atIndex_YkNcIjp4SlzRMAsVYSaKtwhasher)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* idx, NI idxLen_0);
static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA**, data_SBSWONiJ6HOnI2fKXIss4Qhasher)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t);
static N_INLINE(NI, getIndex_JI9b9bhedwUjLDTdiHSBej8whasher)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* idx, NI idxLen_0);
static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx);
N_LIB_PRIVATE N_NIMCALL(void, reshape_CcfajccAdxdySTfWpwLUgw)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* new_shape, NI new_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result);
extern TNimType NTI_urhjHEwA2NkLvIUFwuBxiQ_;

static N_INLINE(void, copyFrom_87gws0flOBNTaof6z6y4kwvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI* s, NI sLen_0) {
	(*a).len = sLen_0;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = sLen_0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				(*a).data[(i)- 0] = s[i];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
}

static N_INLINE(void, tensorCpu_cwvbRqbkqB6HikRuAXFeWQvectorize)(NI* out_shape, NI out_shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* result, tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg layout) {
	copyFrom_87gws0flOBNTaof6z6y4kwvectorize((&(*result).shape), out_shape, out_shapeLen_0);
	shape_to_strides_pWpcv5Fx09cqEJC4Ha9als8A((&(*result).shape), layout, (&(*result).strides));
	(*result).offset = ((NI) 0);
}

static N_INLINE(void, stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}

static N_INLINE(NI, product_k2YXWcJ5lNu24E2yfX7EKQvectorize)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a) {
	NI result;
	result = (NI)0;
	result = ((NI) 1);
	{
		NI value;
		value = (NI)0;
		{
			NI i;
			NI colontmp_;
			NI i_2;
			i = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (*a).len;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < colontmp_)) goto LA4;
					i = i_2;
					value = (*a).data[(i)- 0];
					stareq__tk9bwZBdb9bO9baUcUN2AX89bQdata_structure((&result), value);
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	return result;
}

static N_INLINE(NI, size_9c9bGcb6H7uf0KFeicXmH40Avectorize)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	NI result;
	result = (NI)0;
	result = product_k2YXWcJ5lNu24E2yfX7EKQvectorize((&(*t).shape));
	return result;
}

static N_INLINE(void, newTensor_8IqP8DVP9clOgUGmzYBEvMgvectorize)(NI* shape, NI shapeLen_0, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	NI T1_;
	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	tensorCpu_cwvbRqbkqB6HikRuAXFeWQvectorize(shape, shapeLen_0, Result, ((tyEnum_OrderType_3Uf6hB8nlsq9c1TFBUPn9bUg) 101));
	T1_ = (NI)0;
	T1_ = size_9c9bGcb6H7uf0KFeicXmH40Avectorize(Result);
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), newSeq_QEg0mebvlEuej5bmGcaclQ(((NI) (T1_))));
}

static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bghasher)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	result = (NimStringDesc*)0;
	a = x.a;
	L = (NI)((NI)(x.b - a) + ((NI) 1));
	result = mnewString(((NI) (L)));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				if (!(i_2 < L)) goto LA3;
				i = i_2;
				result->data[i] = s->data[(NI)(i + a)];
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qshapeshifting)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, hashSubstring_sXbP7ngYY7f19cFmFlc5VwQ)(NimStringDesc* s, NI a, NI b, NI nFeatures) {
	NI result;
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T1_;
	NimStringDesc* T2_;
	tyArray_EawPLnQhPqWwYm5GdCoh8A T3_;
{	result = (NI)0;
	T1_ = dotdot__vDQySKWzgnxQdUarow6k5Qshapeshifting(a, b);
	T2_ = (NimStringDesc*)0;
	T2_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bghasher(s, T1_);
	memset((void*)T3_, 0, sizeof(T3_));
	murmur_hash_avQi9ckmRChhS4U83NwRMuQ(T2_, ((NU32) 0), T3_);
	result = (((NI) ((NI64)(T3_[(((NI) 0))- 0] % ((NI64) (nFeatures))))) > 0? (((NI) ((NI64)(T3_[(((NI) 0))- 0] % ((NI64) (nFeatures)))))) : -(((NI) ((NI64)(T3_[(((NI) 0))- 0] % ((NI64) (nFeatures)))))));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, pluseq__7kHiltrvRlcg6wSYR3CxAwhasher)(NF* x, NF y) {
	(*x) = ((NF)((*x)) + (NF)(y));
}

static N_INLINE(tySequence_Zj5xKXgsXnI4n4hPS6nACA**, data_SBSWONiJ6HOnI2fKXIss4Qhasher)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t) {
	tySequence_Zj5xKXgsXnI4n4hPS6nACA** result;
	result = (&(*t).storage.Fdata);
	return result;
}

static N_INLINE(NI, X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure)(tyObject_DynamicStackArray_sGjc7KeArQw8Nb9cdBLtCaw* a, NI idx) {
	NI result;
	result = (NI)0;
	result = (*a).data[(idx)- 0];
	return result;
}

static N_INLINE(NI, getIndex_JI9b9bhedwUjLDTdiHSBej8whasher)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* idx, NI idxLen_0) {
	NI result;
	result = (NI)0;
	result = (*t).offset;
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = idxLen_0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI T4_;
				if (!(i_2 < colontmp_)) goto LA3;
				i = i_2;
				T4_ = (NI)0;
				T4_ = X5BX5D__m4A0oZJCb0QRWXjDxP2nVgdata_structure((&(*t).strides), i);
				result += (NI)(T4_ * idx[i]);
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}

static N_INLINE(NF*, atIndex_YkNcIjp4SlzRMAsVYSaKtwhasher)(tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* t, NI* idx, NI idxLen_0) {
	NF* result;
	tySequence_Zj5xKXgsXnI4n4hPS6nACA** T1_;
	NI T2_;
	result = (NF*)0;
	T1_ = (tySequence_Zj5xKXgsXnI4n4hPS6nACA**)0;
	T1_ = data_SBSWONiJ6HOnI2fKXIss4Qhasher(t);
	T2_ = (NI)0;
	T2_ = getIndex_JI9b9bhedwUjLDTdiHSBej8whasher((&(*t)), idx, idxLen_0);
	result = (&(*T1_)->data[T2_]);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, makeMurmurTensor_Ra0msq7J9a56ha0rna3UAIg)(NimStringDesc* s, NI nFeatures, tyTuple_1v9bKyksXWMsm0vNwmZ4EuQ nGramRange, tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ* Result) {
	tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T1_;
	NI start;
	NI ending;
	NI l;
	NI h;
	tyArray_HU7qaqKu9czJLT84iCBJnsA T16_;
	tyObject_Tensor_urhjHEwA2NkLvIUFwuBxiQ T17_;
{	genericReset((void*)Result, (&NTI_urhjHEwA2NkLvIUFwuBxiQ_));
	T1_[0] = nFeatures;
	newTensor_8IqP8DVP9clOgUGmzYBEvMgvectorize(T1_, 1, Result);
	start = ((NI) 0);
	ending = (s ? s->Sup.len : 0);
	l = nGramRange.Field0;
	h = nGramRange.Field1;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = start;
		{
			while (1) {
				NI idx;
				tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T5_;
				NF* T6_;
				if (!(res <= ending)) goto LA4;
				i = res;
				idx = hashSubstring_sXbP7ngYY7f19cFmFlc5VwQ(s, i, i, nFeatures);
				T5_[0] = idx;
				T6_ = (NF*)0;
				T6_ = atIndex_YkNcIjp4SlzRMAsVYSaKtwhasher(Result, T5_, 1);
				pluseq__7kHiltrvRlcg6wSYR3CxAwhasher(T6_, 1.0000000000000000e+00);
				{
					NI u;
					NI colontmp_;
					NI res_2;
					u = (NI)0;
					colontmp_ = (NI)0;
					colontmp_ = (NI)(h - ((NI) 1));
					res_2 = l;
					{
						while (1) {
							if (!(res_2 <= colontmp_)) goto LA9;
							u = res_2;
							{
								tyArray_GAcaPw08Gj9cXYhAaMMr9cfw T14_;
								NF* T15_;
								if (!((NI)(i + u) < ending)) goto LA12_;
								idx = hashSubstring_sXbP7ngYY7f19cFmFlc5VwQ(s, i, (NI)(i + u), nFeatures);
								T14_[0] = idx;
								T15_ = (NF*)0;
								T15_ = atIndex_YkNcIjp4SlzRMAsVYSaKtwhasher(Result, T14_, 1);
								pluseq__7kHiltrvRlcg6wSYR3CxAwhasher(T15_, 1.0000000000000000e+00);
							}
							LA12_: ;
							res_2 += ((NI) 1);
						} LA9: ;
					}
				}
				res += ((NI) 1);
			} LA4: ;
		}
	}
	T16_[0] = ((NI) 1);
	T16_[1] = nFeatures;
	memset((void*)(&T17_), 0, sizeof(T17_));
	reshape_CcfajccAdxdySTfWpwLUgw(Result, T16_, 2, (&T17_));
	(*Result).shape = T17_.shape;
	(*Result).strides = T17_.strides;
	(*Result).offset = T17_.offset;
	unsureAsgnRef((void**) (&(*Result).storage.Fdata), T17_.storage.Fdata);
	goto BeforeRet_;
	}BeforeRet_: ;
}
NIM_EXTERNC N_NOINLINE(void, unknown_hasherInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, unknown_hasherDatInit000)(void) {
}

