/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/murmur3_murmur3.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/murmur3_murmur3.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NI64 tyArray_EawPLnQhPqWwYm5GdCoh8A[2];
N_NIMCALL(void, MurmurHash3_x64_128)(NCSTRING key, NI len, NU32 seed, NI64* out_hashes);
NIM_CONST tyArray_EawPLnQhPqWwYm5GdCoh8A TM_V8Ler1yoTTlfB9aUsWmLEYA_2 = {IL64(0),
IL64(0)}
;

N_LIB_PRIVATE N_NIMCALL(void, murmur_hash_avQi9ckmRChhS4U83NwRMuQ)(NimStringDesc* key, NU32 seed, tyArray_EawPLnQhPqWwYm5GdCoh8A Result) {
{	memset((void*)Result, 0, sizeof(Result));
	memcpy((void*)Result, (NIM_CONST void*)TM_V8Ler1yoTTlfB9aUsWmLEYA_2, sizeof(tyArray_EawPLnQhPqWwYm5GdCoh8A));
	MurmurHash3_x64_128(key->data, (key ? key->Sup.len : 0), seed, Result);
	goto BeforeRet_;
	}BeforeRet_: ;
}
NIM_EXTERNC N_NOINLINE(void, murmur3_murmur3Init000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, murmur3_murmur3DatInit000)(void) {
}

