/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w -O3  -I/Users/aljohnson/.choosenim/toolchains/nim-0.18.0/lib -o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/stdlib_json.o /Users/aljohnson/code/nim-splunk-vectorizer/src/nimcache/stdlib_json.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <setjmp.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g tySequence_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ tySequence_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ;
typedef struct tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ;
typedef struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw;
typedef struct RootObj RootObj;
typedef struct tySequence_ArNCLAPkQjwz7DrguhEHNA tySequence_ArNCLAPkQjwz7DrguhEHNA;
typedef struct Exception Exception;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ;
typedef struct tyTuple_awOivLjlO76sGdHY7nQUjQ tyTuple_awOivLjlO76sGdHY7nQUjQ;
typedef struct tyTuple_jq7X5k7hWG0tdTZTDkiyGQ tyTuple_jq7X5k7hWG0tdTZTDkiyGQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef NU8 tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw {
tySequence_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q {
tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {tySequence_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw {
  RootObj Sup;
NI bufpos;
NCSTRING buf;
NI bufLen;
tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA;
typedef NU8 tyEnum_JsonEventKind_NdAkGi88owzfBOSBDfW49cQ;
typedef NU8 tyEnum_JsonError_rhaSH4AjHj9bXRijCvdqRhQ;
struct tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ {
  tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw Sup;
NimStringDesc* a;
tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA tok;
tyEnum_JsonEventKind_NdAkGi88owzfBOSBDfW49cQ kind;
tyEnum_JsonError_rhaSH4AjHj9bXRijCvdqRhQ err;
tySequence_ArNCLAPkQjwz7DrguhEHNA* state;
NimStringDesc* filename;
};
typedef NU8 tyEnum_ParserState_UzfeQnJimUtC9bt1BjDzcdQ;
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClP_0) (Exception* e, void* ClE_0);
void* ClE_0;
} tyProc_KeeAOYBd84Ofsw6Y7LizaQ;
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
tyProc_KeeAOYBd84Ofsw6Y7LizaQ raiseAction;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
typedef NimStringDesc* tyArray_sMpvt1sOxOJ3LFGulnbeMQ[4];
typedef NimStringDesc* tyArray_FTpfONgp1jey0x30eh1eQQ[14];
struct tyTuple_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyTuple_jq7X5k7hWG0tdTZTDkiyGQ {
NimStringDesc* Field0;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field1;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef N_NIMCALL_PTR(void, tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc_KjFcmLOhf4VQvVcyLJWXZw) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(void, tyProc_jlOYFw9cHausuCbPoWx2iiA) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s);
typedef N_NIMCALL_PTR(NI, tyProc_tjaJtoUzLe1BMUbItlcGhQ) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc_b9bsIuILxTLVZHPvJBW187A) (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ {
  RootObj Sup;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q closeImpl;
tyProc_KjFcmLOhf4VQvVcyLJWXZw atEndImpl;
tyProc_jlOYFw9cHausuCbPoWx2iiA setPositionImpl;
tyProc_Xzm85qBLb9cf9cu8VOfAr8PQ getPositionImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ readDataImpl;
tyProc_tjaJtoUzLe1BMUbItlcGhQ peekDataImpl;
tyProc_b9bsIuILxTLVZHPvJBW187A writeDataImpl;
tyProc_cnkJEp9bna8U6yi9aVW9cAJ0Q flushImpl;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ {
  tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ Sup;
NimStringDesc* data;
NI pos;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
struct tySequence_ArNCLAPkQjwz7DrguhEHNA {
  TGenericSeq Sup;
  tyEnum_ParserState_UzfeQnJimUtC9bt1BjDzcdQ data[SEQ_DECL_SIZE];
};
struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_oLpBKXzW3hF9aCVMo5EymfQ)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef_zfzzuQ8txrdZAYK0WGWpHg)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_C0SON7jz9cWK9bCJHvsFscEw)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc* filename);
static N_NIMCALL(void, Marker_tySequence_ArNCLAPkQjwz7DrguhEHNA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, open_USrSbIzr5aC08n4vhuXaWA)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(void, open_xmgaYJZNnO6QcDtac9bs3Vg)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NI bufLen, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw refillChars);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA, getTok_bhdBvXONA2D049cZWsITG7A)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, skip_3S9b9cVNhGg79bsA5hP4JMAbA)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR_IwUEvMBOLRY9cqyar6XKEaw)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF_IwUEvMBOLRY9cqyar6XKEaw_3)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(void, parseNumber_JYjE8i409cEC8b5C0sqMO7A)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_m1TSS3QwQPclQATuiRuVZg)(NimStringDesc* s, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw chars);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA, parseString_bhdBvXONA2D049cZWsITG7A_2)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my);
N_LIB_PRIVATE N_NIMCALL(NI, parseEscapedUTF16_e6kX9atmDSRFKBvyA9bJj1Ew)(NCSTRING buf, NI* pos);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, handleHexChar_B9aB9bYdlH7mQEQhG7ESFXbg)(NIM_CHAR c, NI* x);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nuctoUTF8)(NI32 c);
N_LIB_PRIVATE N_NIMCALL(void, parseName_JYjE8i409cEC8b5C0sqMO7A_2)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_ZpTCprfoMR56CxpiABjGXw)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* p);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJStringMove_8iXO9aRAijCPe58pujCBbuQ_2)(NimStringDesc* s);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJInt_z0g83xvrx4R10lOvgItZ9aQ)(NI64 n);
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJFloat_U9b9aOjHQ9bZDMSNNz4CuY4Pg)(NF n);
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJBool_bESUahFJIJ0RSySOPtSYZg)(NIM_BOOL b);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJNull_phgxr9cKlc0dmrJpCth52pw)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJObject_phgxr9cKlc0dmrJpCth52pw_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable_PHRF9cHqhXGiWC9cIiRW9bTWw)(NI initialSize, tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* Result);
N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr_4afCLEB5DzcwYAdDumDqYQ)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* p, NimStringDesc* msg) __attribute__((noreturn));
static N_NIMCALL(void, Marker_tyRef_TOl9bBVGahlQmjZBc3UGISg)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsgExpected_JX5zi2U38bL44QMaeRJjvQ)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my, NimStringDesc* e);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
static N_INLINE(NI, getLine_P0hkpPjGtCF4FNZ6q9atEnAjson)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(NI, getColumn_P0hkpPjGtCF4FNZ6q9atEnA_2json)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber_9cj186ckGjLqyndkoW7bBdg)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L, NI pos);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, eat_PuMXgG8Mfi39aPwlrKmXUeQ)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* p, tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA tok);
static N_INLINE(void, X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__9bwm9c9bGAcoIGLjRndWCPT3Q)(tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJArray_phgxr9cKlc0dmrJpCth52pw_3)(void);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, add_NE4BWkXVxUMFtDmmA5ZcHw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* father, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* child);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, close_beTlXOuQRpDyx43UOI9cfsgjson)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my);
N_LIB_PRIVATE N_NIMCALL(void, close_QbedUCk2XwI9c7bbRzXBY0g_2)(tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* L);
N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ*, newStringStream_0dQ0A0pna0dG9cMxo4TbLKQ)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(NI, len_1r8KCEmq7uHhZ2GR9c7tsOA)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n);
static N_INLINE(NI, len_a0ORwcHIaewozuGDsc9b3TAjson)(tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t);
N_LIB_PRIVATE N_NIMCALL(void, toUgly_5SA9aXRryVJvgoCag29cRzQw)(NimStringDesc** result, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
N_LIB_PRIVATE N_NIMCALL(void, escapeJson_xxovtptDIL7ctJosN3ocbA)(NimStringDesc* s, NimStringDesc** result);
N_LIB_PRIVATE N_NIMCALL(void, add_IbYQ9cTcoQ89aIwM2IEYGMng)(NimStringDesc** result, NI64 x);
N_LIB_PRIVATE N_NIMCALL(void, add_A9bDQDKw5SEqD3OvtOnC1bg)(NimStringDesc** result, NF x);
TNimType NTI_df9bshXB7C9cTiWPIOtX3j1Q_;
TNimType NTI_RUngo7nCHe6O8aBGIcrhtg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_Aav8dQoMlCFnZRxA0IhTHQ_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_AF39bJ7XDr6gpANuGpxkHrw_;
TNimType NTI_oLpBKXzW3hF9aCVMo5EymfQ_;
TNimType NTI_zfzzuQ8txrdZAYK0WGWpHg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_B6cGbTPhMsqMovc9cOcIHRw_;
TNimType NTI_TAl5cv6tbH9avL9cKfMc0hkQ_;
TNimType NTI_vfEI6XZ7Xkb5BV9c6202vjA_;
TNimType NTI_NdAkGi88owzfBOSBDfW49cQ_;
TNimType NTI_rhaSH4AjHj9bXRijCvdqRhQ_;
TNimType NTI_UzfeQnJimUtC9bt1BjDzcdQ_;
TNimType NTI_ArNCLAPkQjwz7DrguhEHNA_;
extern TSafePoint* excHandler_rqLlY5bs9atDw2OXYqJEn5g;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
TNimType NTI_4avqtqpbmyD9bxH9bUmO9b0yw_;
TNimType NTI_TOl9bBVGahlQmjZBc3UGISg_;
TNimNode* NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[8];
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_9b9bytt1stv9cZ8uqII7HFgew_18 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
NIM_CONST struct {
  TGenericSeq Sup;
  tyEnum_ParserState_UzfeQnJimUtC9bt1BjDzcdQ data[1];
} TM_9b9bytt1stv9cZ8uqII7HFgew_20 = {{1, 1}, {((tyEnum_ParserState_UzfeQnJimUtC9bt1BjDzcdQ) 1)}};
NIM_CONST tySequence_ArNCLAPkQjwz7DrguhEHNA* TM_9b9bytt1stv9cZ8uqII7HFgew_19 = ((tySequence_ArNCLAPkQjwz7DrguhEHNA*)&TM_9b9bytt1stv9cZ8uqII7HFgew_20);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_21, "", 0);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_23, "0.", 2);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_9b9bytt1stv9cZ8uqII7HFgew_24 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00,
0x20, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_25, "\\u", 2);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_26, "null", 4);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_27, "true", 4);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_28, "false", 5);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_29, "$1($2, $3) Error: $4", 20);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_30, " expected", 9);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_31, "string literal as key", 21);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_32, "invalid token", 13);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_33, "EOF", 3);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_34, "string literal", 14);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_35, "int literal", 11);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_36, "float literal", 13);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_37, "{", 1);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_38, "}", 1);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_39, "[", 1);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_40, "]", 1);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_41, ":", 1);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_42, ",", 1);
NIM_CONST tyArray_FTpfONgp1jey0x30eh1eQQ tokToStr_SwoVz4SUTzqVSylUqMwmkw = {((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_32),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_33),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_34),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_35),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_36),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_27),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_28),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_26),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_37),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_38),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_39),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_40),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_41),
((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_42)}
;
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_43, "input", 5);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_44, "\"", 1);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_45, "\\n", 2);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_46, "\\b", 2);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_47, "\\f", 2);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_48, "\\t", 2);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_49, "\\r", 2);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_50, "\\\"", 2);
STRING_LITERAL(TM_9b9bytt1stv9cZ8uqII7HFgew_51, "\\\\", 2);
static N_NIMCALL(void, Marker_tySequence_oLpBKXzW3hF9aCVMo5EymfQ)(void* p, NI op) {
	tySequence_oLpBKXzW3hF9aCVMo5EymfQ* a;
	NI T1_;
	a = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_], op);
	}
}
static N_NIMCALL(void, Marker_tyRef_zfzzuQ8txrdZAYK0WGWpHg)(void* p, NI op) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* a;
	a = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)p;
	switch ((*a).kind) {
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 4):
	nimGCvisit((void*)(*a).kindU.S1.str, op);
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 2):
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 3):
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 1):
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 0):
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5):
	nimGCvisit((void*)(*a).kindU.S6.fields.data, op);
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6):
	nimGCvisit((void*)(*a).kindU.S7.elems, op);
	break;
	} 
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__8iXO9aRAijCPe58pujCBbuQ)(NimStringDesc* s) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	NimStringDesc* T5_;
{	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	{
		if (!(s == 0)) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	(*result).kind = ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 4);
	T5_ = (NimStringDesc*)0;
	T5_ = (*result).kindU.S1.str; (*result).kindU.S1.str = copyStringRC1(s);
	if (T5_) nimGCunrefNoCycle(T5_);
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, Marker_tySequence_ArNCLAPkQjwz7DrguhEHNA)(void* p, NI op) {
	tySequence_ArNCLAPkQjwz7DrguhEHNA* a;
	NI T1_;
	a = (tySequence_ArNCLAPkQjwz7DrguhEHNA*)p;
	T1_ = (NI)0;
}

N_LIB_PRIVATE N_NIMCALL(void, open_USrSbIzr5aC08n4vhuXaWA)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my, tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* input, NimStringDesc* filename) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	open_xmgaYJZNnO6QcDtac9bs3Vg(T1_, input, ((NI) 8192), TM_9b9bytt1stv9cZ8uqII7HFgew_18);
	unsureAsgnRef((void**) (&(*my).filename), copyString(filename));
	genericSeqAssign((&(*my).state), TM_9b9bytt1stv9cZ8uqII7HFgew_19, (&NTI_ArNCLAPkQjwz7DrguhEHNA_));
	(*my).kind = ((tyEnum_JsonEventKind_NdAkGi88owzfBOSBDfW49cQ) 0);
	unsureAsgnRef((void**) (&(*my).a), copyString(((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_21)));
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = excHandler_rqLlY5bs9atDw2OXYqJEn5g;
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = s;
}

N_LIB_PRIVATE N_NIMCALL(void, skip_3S9b9cVNhGg79bsA5hP4JMAbA)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my) {
	NI pos;
	NCSTRING buf;
	pos = (*my).Sup.bufpos;
	buf = (*my).Sup.buf;
	{
		while (1) {
			switch (((NU8)(buf[pos]))) {
			case 47:
			{
				{
					if (!((NU8)(buf[(NI)(pos + ((NI) 1))]) == (NU8)(47))) goto LA6_;
					pos += ((NI) 2);
					{
						while (1) {
							switch (((NU8)(buf[pos]))) {
							case 0:
							{
								goto LA8;
							}
							break;
							case 13:
							{
								tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T12_;
								T12_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
								T12_ = &my->Sup;
								pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw(T12_, pos);
								buf = (*my).Sup.buf;
								goto LA8;
							}
							break;
							case 10:
							{
								tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T14_;
								T14_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
								T14_ = &my->Sup;
								pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T14_, pos);
								buf = (*my).Sup.buf;
								goto LA8;
							}
							break;
							default:
							{
								pos += ((NI) 1);
							}
							break;
							}
						}
					} LA8: ;
				}
				goto LA4_;
				LA6_: ;
				{
					if (!((NU8)(buf[(NI)(pos + ((NI) 1))]) == (NU8)(42))) goto LA17_;
					pos += ((NI) 2);
					{
						while (1) {
							switch (((NU8)(buf[pos]))) {
							case 0:
							{
								(*my).err = ((tyEnum_JsonError_rhaSH4AjHj9bXRijCvdqRhQ) 8);
								goto LA19;
							}
							break;
							case 13:
							{
								tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T23_;
								T23_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
								T23_ = &my->Sup;
								pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw(T23_, pos);
								buf = (*my).Sup.buf;
							}
							break;
							case 10:
							{
								tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T25_;
								T25_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
								T25_ = &my->Sup;
								pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T25_, pos);
								buf = (*my).Sup.buf;
							}
							break;
							case 42:
							{
								pos += ((NI) 1);
								{
									if (!((NU8)(buf[pos]) == (NU8)(47))) goto LA29_;
									pos += ((NI) 1);
									goto LA19;
								}
								LA29_: ;
							}
							break;
							default:
							{
								pos += ((NI) 1);
							}
							break;
							}
						}
					} LA19: ;
				}
				goto LA4_;
				LA17_: ;
				{
					goto LA1;
				}
				LA4_: ;
			}
			break;
			case 32:
			case 9:
			{
				pos += ((NI) 1);
			}
			break;
			case 13:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T35_;
				T35_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T35_ = &my->Sup;
				pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw(T35_, pos);
				buf = (*my).Sup.buf;
			}
			break;
			case 10:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T37_;
				T37_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T37_ = &my->Sup;
				pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T37_, pos);
				buf = (*my).Sup.buf;
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	(*my).Sup.bufpos = pos;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(void, parseNumber_JYjE8i409cEC8b5C0sqMO7A)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my) {
	NI pos;
	NCSTRING buf;
	pos = (*my).Sup.bufpos;
	buf = (*my).Sup.buf;
	{
		if (!((NU8)(buf[pos]) == (NU8)(45))) goto LA3_;
		(*my).a = addChar((*my).a, 45);
		pos += ((NI) 1);
	}
	LA3_: ;
	{
		if (!((NU8)(buf[pos]) == (NU8)(46))) goto LA7_;
		(*my).a = resizeString((*my).a, 2);
appendString((*my).a, ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_23));
		pos += ((NI) 1);
	}
	goto LA5_;
	LA7_: ;
	{
		{
			while (1) {
				if (!(((NU8)(buf[pos])) >= ((NU8)(48)) && ((NU8)(buf[pos])) <= ((NU8)(57)))) goto LA11;
				(*my).a = addChar((*my).a, buf[pos]);
				pos += ((NI) 1);
			} LA11: ;
		}
		{
			if (!((NU8)(buf[pos]) == (NU8)(46))) goto LA14_;
			(*my).a = addChar((*my).a, 46);
			pos += ((NI) 1);
		}
		LA14_: ;
	}
	LA5_: ;
	{
		while (1) {
			if (!(((NU8)(buf[pos])) >= ((NU8)(48)) && ((NU8)(buf[pos])) <= ((NU8)(57)))) goto LA17;
			(*my).a = addChar((*my).a, buf[pos]);
			pos += ((NI) 1);
		} LA17: ;
	}
	{
		if (!(((NU8)(buf[pos])) == ((NU8)(69)) || ((NU8)(buf[pos])) == ((NU8)(101)))) goto LA20_;
		(*my).a = addChar((*my).a, buf[pos]);
		pos += ((NI) 1);
		{
			if (!(((NU8)(buf[pos])) == ((NU8)(43)) || ((NU8)(buf[pos])) == ((NU8)(45)))) goto LA24_;
			(*my).a = addChar((*my).a, buf[pos]);
			pos += ((NI) 1);
		}
		LA24_: ;
		{
			while (1) {
				if (!(((NU8)(buf[pos])) >= ((NU8)(48)) && ((NU8)(buf[pos])) <= ((NU8)(57)))) goto LA27;
				(*my).a = addChar((*my).a, buf[pos]);
				pos += ((NI) 1);
			} LA27: ;
		}
	}
	LA20_: ;
	(*my).Sup.bufpos = pos;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, handleHexChar_B9aB9bYdlH7mQEQhG7ESFXbg)(NIM_CHAR c, NI* x) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = NIM_TRUE;
	switch (((NU8)(c))) {
	case 48 ... 57:
	{
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)(((NU8)(c)) - ((NI) 48)));
	}
	break;
	case 97 ... 102:
	{
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)((NI)(((NU8)(c)) - ((NI) 97)) + ((NI) 10)));
	}
	break;
	case 65 ... 70:
	{
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)((NI)(((NU8)(c)) - ((NI) 65)) + ((NI) 10)));
	}
	break;
	default:
	{
		result = NIM_FALSE;
	}
	break;
	}
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, parseEscapedUTF16_e6kX9atmDSRFKBvyA9bJj1Ew)(NCSTRING buf, NI* pos) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	{
		NI _;
		NI res;
		_ = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 3))) goto LA3;
				_ = res;
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = handleHexChar_B9aB9bYdlH7mQEQhG7ESFXbg(buf[(*pos)], (&result));
					if (!T6_) goto LA7_;
					(*pos) += ((NI) 1);
				}
				goto LA4_;
				LA7_: ;
				{
					result = ((NI) -1);
					goto BeforeRet_;
				}
				LA4_: ;
				res += ((NI) 1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQlogging(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA, parseString_bhdBvXONA2D049cZWsITG7A_2)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my) {
	tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA result;
	NI pos;
	NCSTRING buf;
	result = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
	result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 2);
	pos = (NI)((*my).Sup.bufpos + ((NI) 1));
	buf = (*my).Sup.buf;
	{
		while (1) {
			switch (((NU8)(buf[pos]))) {
			case 0:
			{
				(*my).err = ((tyEnum_JsonError_rhaSH4AjHj9bXRijCvdqRhQ) 7);
				result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 0);
				goto LA1;
			}
			break;
			case 34:
			{
				pos += ((NI) 1);
				goto LA1;
			}
			break;
			case 92:
			{
				switch (((NU8)(buf[(NI)(pos + ((NI) 1))]))) {
				case 92:
				case 34:
				case 39:
				case 47:
				{
					(*my).a = addChar((*my).a, buf[(NI)(pos + ((NI) 1))]);
					pos += ((NI) 2);
				}
				break;
				case 98:
				{
					(*my).a = addChar((*my).a, 8);
					pos += ((NI) 2);
				}
				break;
				case 102:
				{
					(*my).a = addChar((*my).a, 12);
					pos += ((NI) 2);
				}
				break;
				case 110:
				{
					(*my).a = addChar((*my).a, 10);
					pos += ((NI) 2);
				}
				break;
				case 114:
				{
					(*my).a = addChar((*my).a, 13);
					pos += ((NI) 2);
				}
				break;
				case 116:
				{
					(*my).a = addChar((*my).a, 9);
					pos += ((NI) 2);
				}
				break;
				case 117:
				{
					NI r;
					NimStringDesc* T33_;
					pos += ((NI) 2);
					r = parseEscapedUTF16_e6kX9atmDSRFKBvyA9bJj1Ew(buf, (&pos));
					{
						if (!(r < ((NI) 0))) goto LA15_;
						(*my).err = ((tyEnum_JsonError_rhaSH4AjHj9bXRijCvdqRhQ) 1);
						goto LA1;
					}
					LA15_: ;
					{
						NI s;
						if (!((NI)(r & ((NI) 64512)) == ((NI) 55296))) goto LA19_;
						{
							NimStringDesc* T23_;
							T23_ = (NimStringDesc*)0;
							T23_ = rawNewString(2);
appendChar(T23_, buf[pos]);
appendChar(T23_, buf[(NI)(pos + ((NI) 1))]);
							if (!!(eqStrings(T23_, ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_25)))) goto LA24_;
							(*my).err = ((tyEnum_JsonError_rhaSH4AjHj9bXRijCvdqRhQ) 1);
							goto LA1;
						}
						LA24_: ;
						pos += ((NI) 2);
						s = parseEscapedUTF16_e6kX9atmDSRFKBvyA9bJj1Ew(buf, (&pos));
						{
							NIM_BOOL T28_;
							T28_ = (NIM_BOOL)0;
							T28_ = ((NI)(s & ((NI) 64512)) == ((NI) 56320));
							if (!(T28_)) goto LA29_;
							T28_ = (((NI) 0) < s);
							LA29_: ;
							if (!T28_) goto LA30_;
							r = (NI)(((NI) 65536) + (NI)((NI)((NU64)((NI)(r - ((NI) 55296))) << (NU64)(((NI) 10))) | (NI)(s - ((NI) 56320))));
						}
						goto LA26_;
						LA30_: ;
						{
							(*my).err = ((tyEnum_JsonError_rhaSH4AjHj9bXRijCvdqRhQ) 1);
							goto LA1;
						}
						LA26_: ;
					}
					LA19_: ;
					T33_ = (NimStringDesc*)0;
					T33_ = nuctoUTF8(((NI32) (r)));
					(*my).a = resizeString((*my).a, T33_->Sup.len + 0);
appendString((*my).a, T33_);
				}
				break;
				default:
				{
					(*my).a = addChar((*my).a, buf[pos]);
					pos += ((NI) 1);
				}
				break;
				}
			}
			break;
			case 13:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T36_;
				T36_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T36_ = &my->Sup;
				pos = handleCR_IwUEvMBOLRY9cqyar6XKEaw(T36_, pos);
				buf = (*my).Sup.buf;
				(*my).a = addChar((*my).a, 13);
			}
			break;
			case 10:
			{
				tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T38_;
				T38_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
				T38_ = &my->Sup;
				pos = handleLF_IwUEvMBOLRY9cqyar6XKEaw_3(T38_, pos);
				buf = (*my).Sup.buf;
				(*my).a = addChar((*my).a, 10);
			}
			break;
			default:
			{
				(*my).a = addChar((*my).a, buf[pos]);
				pos += ((NI) 1);
			}
			break;
			}
		}
	} LA1: ;
	(*my).Sup.bufpos = pos;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseName_JYjE8i409cEC8b5C0sqMO7A_2)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my) {
	NI pos;
	NCSTRING buf;
	pos = (*my).Sup.bufpos;
	buf = (*my).Sup.buf;
	{
		if (!(((NU8)(buf[pos])) >= ((NU8)(97)) && ((NU8)(buf[pos])) <= ((NU8)(122)) || ((NU8)(buf[pos])) >= ((NU8)(65)) && ((NU8)(buf[pos])) <= ((NU8)(90)) || ((NU8)(buf[pos])) == ((NU8)(95)))) goto LA3_;
		{
			while (1) {
				if (!(((NU8)(buf[pos])) >= ((NU8)(97)) && ((NU8)(buf[pos])) <= ((NU8)(122)) || ((NU8)(buf[pos])) >= ((NU8)(65)) && ((NU8)(buf[pos])) <= ((NU8)(90)) || ((NU8)(buf[pos])) >= ((NU8)(48)) && ((NU8)(buf[pos])) <= ((NU8)(57)) || ((NU8)(buf[pos])) == ((NU8)(95)))) goto LA6;
				(*my).a = addChar((*my).a, buf[pos]);
				pos += ((NI) 1);
			} LA6: ;
		}
	}
	LA3_: ;
	(*my).Sup.bufpos = pos;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA, getTok_bhdBvXONA2D049cZWsITG7A)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my) {
	tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA result;
	result = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
	(*my).a = setLengthStr((*my).a, ((NI) 0));
	skip_3S9b9cVNhGg79bsA5hP4JMAbA(my);
	switch (((NU8)((*my).Sup.buf[(*my).Sup.bufpos]))) {
	case 45:
	case 46:
	case 48 ... 57:
	{
		parseNumber_JYjE8i409cEC8b5C0sqMO7A(my);
		{
			NIM_BOOL T4_;
			T4_ = (NIM_BOOL)0;
			T4_ = contains_m1TSS3QwQPclQATuiRuVZg((*my).a, TM_9b9bytt1stv9cZ8uqII7HFgew_24);
			if (!T4_) goto LA5_;
			result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 4);
		}
		goto LA2_;
		LA5_: ;
		{
			result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 3);
		}
		LA2_: ;
	}
	break;
	case 34:
	{
		result = parseString_bhdBvXONA2D049cZWsITG7A_2(my);
	}
	break;
	case 91:
	{
		(*my).Sup.bufpos += ((NI) 1);
		result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 10);
	}
	break;
	case 123:
	{
		(*my).Sup.bufpos += ((NI) 1);
		result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 8);
	}
	break;
	case 93:
	{
		(*my).Sup.bufpos += ((NI) 1);
		result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 11);
	}
	break;
	case 125:
	{
		(*my).Sup.bufpos += ((NI) 1);
		result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 9);
	}
	break;
	case 44:
	{
		(*my).Sup.bufpos += ((NI) 1);
		result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 13);
	}
	break;
	case 58:
	{
		(*my).Sup.bufpos += ((NI) 1);
		result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 12);
	}
	break;
	case 0:
	{
		result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 1);
	}
	break;
	case 97 ... 122:
	case 65 ... 90:
	case 95:
	{
		parseName_JYjE8i409cEC8b5C0sqMO7A_2(my);
		if (eqStrings((*my).a, ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_26))) goto LA17_;
		if (eqStrings((*my).a, ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_27))) goto LA18_;
		if (eqStrings((*my).a, ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_28))) goto LA19_;
		goto LA20_;
		LA17_: ;
		{
			result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 7);
		}
		goto LA21_;
		LA18_: ;
		{
			result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 5);
		}
		goto LA21_;
		LA19_: ;
		{
			result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 6);
		}
		goto LA21_;
		LA20_: ;
		{
			result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 0);
		}
		LA21_: ;
	}
	break;
	default:
	{
		(*my).Sup.bufpos += ((NI) 1);
		result = ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 0);
	}
	break;
	}
	(*my).tok = result;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJStringMove_8iXO9aRAijCPe58pujCBbuQ_2)(NimStringDesc* s) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	(*result).kind = ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 4);
	asgnRefNoCycle((void**) (&(*result).kindU.S1.str), s);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJInt_z0g83xvrx4R10lOvgItZ9aQ)(NI64 n) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	(*result).kind = ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 2);
	(*result).kindU.S2.num = n;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJFloat_U9b9aOjHQ9bZDMSNNz4CuY4Pg)(NF n) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	(*result).kind = ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 3);
	(*result).kindU.S3.fnum = n;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJBool_bESUahFJIJ0RSySOPtSYZg)(NIM_BOOL b) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	(*result).kind = ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 1);
	(*result).kindU.S4.bval = b;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJNull_phgxr9cKlc0dmrJpCth52pw)(void) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJObject_phgxr9cKlc0dmrJpCth52pw_2)(void) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	(*result).kind = ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5);
	initOrderedTable_PHRF9cHqhXGiWC9cIiRW9bTWw(((NI) 4), (&(*result).kindU.S6.fields));
	return result;
}
static N_NIMCALL(void, Marker_tyRef_TOl9bBVGahlQmjZBc3UGISg)(void* p, NI op) {
	tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw* a;
	a = (tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
}

static N_INLINE(NI, getLine_P0hkpPjGtCF4FNZ6q9atEnAjson)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my) {
	NI result;
	result = (NI)0;
	result = (*my).Sup.lineNumber;
	return result;
}

static N_INLINE(NI, getColumn_P0hkpPjGtCF4FNZ6q9atEnA_2json)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my) {
	NI result;
	result = (NI)0;
	result = getColNumber_9cj186ckGjLqyndkoW7bBdg((&(*my).Sup), (*my).Sup.bufpos);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorMsgExpected_JX5zi2U38bL44QMaeRJjvQ)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my, NimStringDesc* e) {
	NimStringDesc* result;
	tyArray_sMpvt1sOxOJ3LFGulnbeMQ T1_;
	NI T2_;
	NI T3_;
	NimStringDesc* T4_;
	result = (NimStringDesc*)0;
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString((*my).filename);
	T2_ = (NI)0;
	T2_ = getLine_P0hkpPjGtCF4FNZ6q9atEnAjson(my);
	T1_[1] = nimIntToStr(T2_);
	T3_ = (NI)0;
	T3_ = getColumn_P0hkpPjGtCF4FNZ6q9atEnA_2json(my);
	T1_[2] = nimIntToStr(T3_);
	T4_ = (NimStringDesc*)0;
	T4_ = rawNewString(e->Sup.len + 9);
appendString(T4_, e);
appendString(T4_, ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_30));
	T1_[3] = T4_;
	result = nsuFormatOpenArray(((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_29), T1_, 4);
	return result;
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	(*dest) = src;
}

N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr_4afCLEB5DzcwYAdDumDqYQ)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* p, NimStringDesc* msg) {
	tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw* e;
	e = (tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw*)0;
	e = (tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw*) newObj((&NTI_TOl9bBVGahlQmjZBc3UGISg_), sizeof(tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw));
	(*e).Sup.Sup.Sup.m_type = (&NTI_4avqtqpbmyD9bxH9bUmO9b0yw_);
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), errorMsgExpected_JX5zi2U38bL44QMaeRJjvQ(p, msg));
	asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
	raiseException((Exception*)e, "JsonParsingError");
}

N_LIB_PRIVATE N_NIMCALL(void, eat_PuMXgG8Mfi39aPwlrKmXUeQ)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* p, tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA tok) {
	{
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T5_;
		if (!((*p).tok == tok)) goto LA3_;
		T5_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T5_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T5_;
	}
	goto LA1_;
	LA3_: ;
	{
		raiseParseErr_4afCLEB5DzcwYAdDumDqYQ((&(*p)), tokToStr_SwoVz4SUTzqVSylUqMwmkw[(tok)- 0]);
	}
	LA1_: ;
}

static N_INLINE(void, X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val) {
	X5BX5Deq__9bwm9c9bGAcoIGLjRndWCPT3Q((&(*obj).kindU.S6.fields), key, val);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJArray_phgxr9cKlc0dmrJpCth52pw_3)(void) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	(*result).kind = ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6);
	if ((*result).kindU.S7.elems) { nimGCunrefNoCycle((*result).kindU.S7.elems); (*result).kindU.S7.elems = NIM_NIL; }
	(*result).kindU.S7.elems = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*) newSeqRC1((&NTI_oLpBKXzW3hF9aCVMo5EymfQ_), 0);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, add_NE4BWkXVxUMFtDmmA5ZcHw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* father, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* child) {
	NI T1_;
	(*father).kindU.S7.elems = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*) incrSeqV2(&((*father).kindU.S7.elems)->Sup, sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*));
	T1_ = (*father).kindU.S7.elems->Sup.len++;
	asgnRefNoCycle((void**) (&(*father).kindU.S7.elems->data[T1_]), child);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_ZpTCprfoMR56CxpiABjGXw)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* p) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	switch ((*p).tok) {
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 2):
	{
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T2_;
		result = newJStringMove_8iXO9aRAijCPe58pujCBbuQ_2((*p).a);
		unsureAsgnRef((void**) (&(*p).a), copyString(((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_21)));
		T2_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T2_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T2_;
	}
	break;
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 3):
	{
		NI64 T4_;
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T5_;
		T4_ = (NI64)0;
		T4_ = nsuParseBiggestInt((*p).a);
		result = newJInt_z0g83xvrx4R10lOvgItZ9aQ(T4_);
		T5_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T5_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T5_;
	}
	break;
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 4):
	{
		NF T7_;
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T8_;
		T7_ = (NF)0;
		T7_ = nsuParseFloat((*p).a);
		result = newJFloat_U9b9aOjHQ9bZDMSNNz4CuY4Pg(T7_);
		T8_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T8_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T8_;
	}
	break;
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 5):
	{
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T10_;
		result = newJBool_bESUahFJIJ0RSySOPtSYZg(NIM_TRUE);
		T10_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T10_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T10_;
	}
	break;
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 6):
	{
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T12_;
		result = newJBool_bESUahFJIJ0RSySOPtSYZg(NIM_FALSE);
		T12_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T12_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T12_;
	}
	break;
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 7):
	{
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T14_;
		result = newJNull_phgxr9cKlc0dmrJpCth52pw();
		T14_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T14_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T14_;
	}
	break;
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 8):
	{
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T16_;
		result = newJObject_phgxr9cKlc0dmrJpCth52pw_2();
		T16_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T16_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T16_;
		{
			while (1) {
				NimStringDesc* key;
				tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T23_;
				tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val;
				tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T28_;
				if (!!(((*p).tok == ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 9)))) goto LA18;
				{
					if (!!(((*p).tok == ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 2)))) goto LA21_;
					raiseParseErr_4afCLEB5DzcwYAdDumDqYQ((&(*p)), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_31));
				}
				LA21_: ;
				key = copyString((*p).a);
				T23_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
				T23_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
				T23_;
				eat_PuMXgG8Mfi39aPwlrKmXUeQ(p, ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 12));
				val = parseJson_ZpTCprfoMR56CxpiABjGXw(p);
				X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(result, key, val);
				{
					if (!!(((*p).tok == ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 13)))) goto LA26_;
					goto LA17;
				}
				LA26_: ;
				T28_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
				T28_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
				T28_;
			} LA18: ;
		} LA17: ;
		eat_PuMXgG8Mfi39aPwlrKmXUeQ(p, ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 9));
	}
	break;
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 10):
	{
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T30_;
		result = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
		T30_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T30_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
		T30_;
		{
			while (1) {
				tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T33_;
				tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T38_;
				if (!!(((*p).tok == ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 11)))) goto LA32;
				T33_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
				T33_ = parseJson_ZpTCprfoMR56CxpiABjGXw(p);
				add_NE4BWkXVxUMFtDmmA5ZcHw(result, T33_);
				{
					if (!!(((*p).tok == ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 13)))) goto LA36_;
					goto LA31;
				}
				LA36_: ;
				T38_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
				T38_ = getTok_bhdBvXONA2D049cZWsITG7A(p);
				T38_;
			} LA32: ;
		} LA31: ;
		eat_PuMXgG8Mfi39aPwlrKmXUeQ(p, ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 11));
	}
	break;
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 0):
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 9):
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 11):
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 12):
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 13):
	case ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 1):
	{
		raiseParseErr_4afCLEB5DzcwYAdDumDqYQ((&(*p)), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_37));
	}
	break;
	}
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	excHandler_rqLlY5bs9atDw2OXYqJEn5g = (*excHandler_rqLlY5bs9atDw2OXYqJEn5g).prev;
}

static N_INLINE(void, close_beTlXOuQRpDyx43UOI9cfsgjson)(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ* my) {
	tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw* T1_;
	T1_ = (tyObject_BaseLexer_B6cGbTPhMsqMovc9cOcIHRw*)0;
	T1_ = &my->Sup;
	close_QbedUCk2XwI9c7bbRzXBY0g_2(T1_);
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_C0SON7jz9cWK9bCJHvsFscEw)(tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* s, NimStringDesc* filename) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* volatile result;
	tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ p;
	TSafePoint TM_9b9bytt1stv9cZ8uqII7HFgew_22;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	memset((void*)(&p), 0, sizeof(p));
	p.Sup.Sup.m_type = (&NTI_TAl5cv6tbH9avL9cKfMc0hkQ_);
	open_USrSbIzr5aC08n4vhuXaWA((&p), s, filename);
	pushSafePoint(&TM_9b9bytt1stv9cZ8uqII7HFgew_22);
	TM_9b9bytt1stv9cZ8uqII7HFgew_22.status = _setjmp(TM_9b9bytt1stv9cZ8uqII7HFgew_22.context);
	if (TM_9b9bytt1stv9cZ8uqII7HFgew_22.status == 0) {
		tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA T2_;
		T2_ = (tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA)0;
		T2_ = getTok_bhdBvXONA2D049cZWsITG7A((&p));
		T2_;
		result = parseJson_ZpTCprfoMR56CxpiABjGXw((&p));
		eat_PuMXgG8Mfi39aPwlrKmXUeQ((&p), ((tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA) 1));
		popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		close_beTlXOuQRpDyx43UOI9cfsgjson((&p));
	}
	if (TM_9b9bytt1stv9cZ8uqII7HFgew_22.status != 0) reraiseException();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, parseJson_q2jt59czHU4BW88Mb7EJDUA)(NimStringDesc* buffer) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ* T1_;
	tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ* T2_;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T1_ = (tyObject_StringStreamObj_lGsM0FdhfyxyplfYoMsgFQ*)0;
	T1_ = newStringStream_0dQ0A0pna0dG9cMxo4TbLKQ(buffer);
	T2_ = (tyObject_StreamObj_RShkcoDOPnoCVhtpN1hDPQ*)0;
	T2_ = &T1_->Sup;
	result = parseJson_C0SON7jz9cWK9bCJHvsFscEw(T2_, ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_43));
	return result;
}

static N_INLINE(NI, len_a0ORwcHIaewozuGDsc9b3TAjson)(tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t) {
	NI result;
	result = (NI)0;
	result = (*t).counter;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, len_1r8KCEmq7uHhZ2GR9c7tsOA)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n) {
	NI result;
	result = (NI)0;
	switch ((*n).kind) {
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6):
	{
		NI T2_;
		T2_ = ((*n).kindU.S7.elems ? (*n).kindU.S7.elems->Sup.len : 0);
		result = T2_;
	}
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5):
	{
		result = len_a0ORwcHIaewozuGDsc9b3TAjson((&(*n).kindU.S6.fields));
	}
	break;
	default:
	{
	}
	break;
	}
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, escapeJson_xxovtptDIL7ctJosN3ocbA)(NimStringDesc* s, NimStringDesc** result) {
	(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_44));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		i = ((NI) 0);
		L = (s ? s->Sup.len : 0);
		{
			while (1) {
				if (!(i < L)) goto LA3;
				c = s->data[i];
				switch (((NU8)(c))) {
				case 10:
				{
					(*result) = resizeString((*result), 2);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_45));
				}
				break;
				case 8:
				{
					(*result) = resizeString((*result), 2);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_46));
				}
				break;
				case 12:
				{
					(*result) = resizeString((*result), 2);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_47));
				}
				break;
				case 9:
				{
					(*result) = resizeString((*result), 2);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_48));
				}
				break;
				case 13:
				{
					(*result) = resizeString((*result), 2);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_49));
				}
				break;
				case 34:
				{
					(*result) = resizeString((*result), 2);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_50));
				}
				break;
				case 92:
				{
					(*result) = resizeString((*result), 2);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_51));
				}
				break;
				default:
				{
					(*result) = addChar((*result), c);
				}
				break;
				}
				i += ((NI) 1);
			} LA3: ;
		}
	}
	(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_44));
}

N_LIB_PRIVATE N_NIMCALL(void, toUgly_5SA9aXRryVJvgoCag29cRzQw)(NimStringDesc** result, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node) {
	NIM_BOOL comma;
	comma = NIM_FALSE;
	switch ((*node).kind) {
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6):
	{
		(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_39));
		{
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* child;
			tySequence_oLpBKXzW3hF9aCVMo5EymfQ* colontmp_;
			NI i;
			NI L;
			NI T3_;
			child = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			colontmp_ = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*)0;
			colontmp_ = (*node).kindU.S7.elems;
			i = ((NI) 0);
			T3_ = (colontmp_ ? colontmp_->Sup.len : 0);
			L = T3_;
			{
				while (1) {
					if (!(i < L)) goto LA5;
					child = colontmp_->data[i];
					{
						if (!comma) goto LA8_;
						(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_42));
					}
					goto LA6_;
					LA8_: ;
					{
						comma = NIM_TRUE;
					}
					LA6_: ;
					toUgly_5SA9aXRryVJvgoCag29cRzQw(result, child);
					i += ((NI) 1);
				} LA5: ;
			}
		}
		(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_40));
	}
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5):
	{
		(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_37));
		{
			NimStringDesc* key;
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* value;
			tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw colontmp__2;
			NI h;
			key = (NimStringDesc*)0;
			value = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			memset((void*)(&colontmp__2), 0, sizeof(colontmp__2));
			colontmp__2.data = (*node).kindU.S6.fields.data;
			colontmp__2.counter = (*node).kindU.S6.fields.counter;
			colontmp__2.first = (*node).kindU.S6.fields.first;
			colontmp__2.last = (*node).kindU.S6.fields.last;
			h = colontmp__2.first;
			{
				while (1) {
					NI nxt;
					if (!(((NI) 0) <= h)) goto LA14;
					nxt = colontmp__2.data->data[h].Field1;
					{
						NIM_BOOL T17_;
						T17_ = (NIM_BOOL)0;
						T17_ = isFilled_IxXD1UAPoEehVDW9cv9cRaewtables(colontmp__2.data->data[h].Field0);
						if (!T17_) goto LA18_;
						key = colontmp__2.data->data[h].Field2;
						value = colontmp__2.data->data[h].Field3;
						{
							if (!comma) goto LA22_;
							(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_42));
						}
						goto LA20_;
						LA22_: ;
						{
							comma = NIM_TRUE;
						}
						LA20_: ;
						escapeJson_xxovtptDIL7ctJosN3ocbA(key, result);
						(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_41));
						toUgly_5SA9aXRryVJvgoCag29cRzQw(result, value);
					}
					LA18_: ;
					h = nxt;
				} LA14: ;
			}
		}
		(*result) = resizeString((*result), 1);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_38));
	}
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 4):
	{
		escapeJson_xxovtptDIL7ctJosN3ocbA((*node).kindU.S1.str, result);
	}
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 2):
	{
		add_IbYQ9cTcoQ89aIwM2IEYGMng(result, (*node).kindU.S2.num);
	}
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 3):
	{
		add_A9bDQDKw5SEqD3OvtOnC1bg(result, (*node).kindU.S3.fnum);
	}
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 1):
	{
		NimStringDesc* T29_;
		T29_ = (NimStringDesc*)0;
		{
			if (!(*node).kindU.S4.bval) goto LA32_;
			T29_ = copyString(((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_27));
		}
		goto LA30_;
		LA32_: ;
		{
			T29_ = copyString(((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_28));
		}
		LA30_: ;
		(*result) = resizeString((*result), T29_->Sup.len + 0);
appendString((*result), T29_);
	}
	break;
	case ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 0):
	{
		(*result) = resizeString((*result), 4);
appendString((*result), ((NimStringDesc*) &TM_9b9bytt1stv9cZ8uqII7HFgew_26));
	}
	break;
	}
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__f9cKpuwjrLNwYtym1kuFzjQ)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node) {
	NimStringDesc* result;
	NI T1_;
	result = (NimStringDesc*)0;
	T1_ = (NI)0;
	T1_ = len_1r8KCEmq7uHhZ2GR9c7tsOA(node);
	result = rawNewString(((NI) ((NI)((NU64)(T1_) << (NU64)(((NI) 1))))));
	toUgly_5SA9aXRryVJvgoCag29cRzQw((&result), node);
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getStr_z2Itmc4KJ7uMBtaTVQ09cqw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, NimStringDesc* default_0) {
	NimStringDesc* result;
{	result = (NimStringDesc*)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 4)));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = copyString(default_0);
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		result = copyString((*n).kindU.S1.str);
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tySequence_oLpBKXzW3hF9aCVMo5EymfQ*, getElems_ES84hcmEkNlkkNKiutnPbg)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n, tySequence_oLpBKXzW3hF9aCVMo5EymfQ* default_0) {
	tySequence_oLpBKXzW3hF9aCVMo5EymfQ* result;
{	result = (tySequence_oLpBKXzW3hF9aCVMo5EymfQ*)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 6)));
		LA4_: ;
		if (!T3_) goto LA5_;
		genericSeqAssign((&result), default_0, (&NTI_oLpBKXzW3hF9aCVMo5EymfQ_));
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		genericSeqAssign((&result), (*n).kindU.S7.elems, (&NTI_oLpBKXzW3hF9aCVMo5EymfQ_));
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__9bR9b9aepApwIZEZZtX9cb7RFA)(tyTuple_jq7X5k7hWG0tdTZTDkiyGQ* keyVals, NI keyValsLen_0) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
{	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	{
		if (!(keyValsLen_0 == ((NI) 0))) goto LA3_;
		result = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
		goto BeforeRet_;
	}
	LA3_: ;
	result = newJObject_phgxr9cKlc0dmrJpCth52pw_2();
	{
		NimStringDesc* key;
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val;
		NI i;
		key = (NimStringDesc*)0;
		val = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < keyValsLen_0)) goto LA7;
				key = keyVals[i].Field0;
				val = keyVals[i].Field1;
				X5BX5Deq__9bwm9c9bGAcoIGLjRndWCPT3Q((&(*result).kindU.S6.fields), key, val);
				i += ((NI) 1);
			} LA7: ;
		}
	}
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__bESUahFJIJ0RSySOPtSYZg_2)(NIM_BOOL b) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*) newObj((&NTI_zfzzuQ8txrdZAYK0WGWpHg_), sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q));
	(*result).kind = ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 1);
	(*result).kindU.S4.bval = b;
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit000)(void) {
}

NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit000)(void) {
static TNimNode* TM_9b9bytt1stv9cZ8uqII7HFgew_2[7];
NI TM_9b9bytt1stv9cZ8uqII7HFgew_4;
static char* NIM_CONST TM_9b9bytt1stv9cZ8uqII7HFgew_3[7] = {
"JNull", 
"JBool", 
"JInt", 
"JFloat", 
"JString", 
"JObject", 
"JArray"};
static TNimNode* TM_9b9bytt1stv9cZ8uqII7HFgew_5[6];
static TNimNode* TM_9b9bytt1stv9cZ8uqII7HFgew_6[14];
NI TM_9b9bytt1stv9cZ8uqII7HFgew_8;
static char* NIM_CONST TM_9b9bytt1stv9cZ8uqII7HFgew_7[14] = {
"tkError", 
"tkEof", 
"tkString", 
"tkInt", 
"tkFloat", 
"tkTrue", 
"tkFalse", 
"tkNull", 
"tkCurlyLe", 
"tkCurlyRi", 
"tkBracketLe", 
"tkBracketRi", 
"tkColon", 
"tkComma"};
static TNimNode* TM_9b9bytt1stv9cZ8uqII7HFgew_9[12];
NI TM_9b9bytt1stv9cZ8uqII7HFgew_11;
static char* NIM_CONST TM_9b9bytt1stv9cZ8uqII7HFgew_10[12] = {
"jsonError", 
"jsonEof", 
"jsonString", 
"jsonInt", 
"jsonFloat", 
"jsonTrue", 
"jsonFalse", 
"jsonNull", 
"jsonObjectStart", 
"jsonObjectEnd", 
"jsonArrayStart", 
"jsonArrayEnd"};
static TNimNode* TM_9b9bytt1stv9cZ8uqII7HFgew_12[11];
NI TM_9b9bytt1stv9cZ8uqII7HFgew_14;
static char* NIM_CONST TM_9b9bytt1stv9cZ8uqII7HFgew_13[11] = {
"errNone", 
"errInvalidToken", 
"errStringExpected", 
"errColonExpected", 
"errCommaExpected", 
"errBracketRiExpected", 
"errCurlyRiExpected", 
"errQuoteExpected", 
"errEOC_Expected", 
"errEofExpected", 
"errExprExpected"};
static TNimNode* TM_9b9bytt1stv9cZ8uqII7HFgew_15[8];
NI TM_9b9bytt1stv9cZ8uqII7HFgew_17;
static char* NIM_CONST TM_9b9bytt1stv9cZ8uqII7HFgew_16[8] = {
"stateEof", 
"stateStart", 
"stateObject", 
"stateArray", 
"stateExpectArrayComma", 
"stateExpectObjectComma", 
"stateExpectColon", 
"stateExpectValue"};
static TNimNode TM_9b9bytt1stv9cZ8uqII7HFgew_0[73];
NTI_df9bshXB7C9cTiWPIOtX3j1Q_.size = sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q);
NTI_df9bshXB7C9cTiWPIOtX3j1Q_.kind = 18;
NTI_df9bshXB7C9cTiWPIOtX3j1Q_.base = 0;
NTI_df9bshXB7C9cTiWPIOtX3j1Q_.flags = 2;
NTI_RUngo7nCHe6O8aBGIcrhtg_.size = sizeof(tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg);
NTI_RUngo7nCHe6O8aBGIcrhtg_.kind = 14;
NTI_RUngo7nCHe6O8aBGIcrhtg_.base = 0;
NTI_RUngo7nCHe6O8aBGIcrhtg_.flags = 3;
for (TM_9b9bytt1stv9cZ8uqII7HFgew_4 = 0; TM_9b9bytt1stv9cZ8uqII7HFgew_4 < 7; TM_9b9bytt1stv9cZ8uqII7HFgew_4++) {
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_4+1].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_4+1].offset = TM_9b9bytt1stv9cZ8uqII7HFgew_4;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_4+1].name = TM_9b9bytt1stv9cZ8uqII7HFgew_3[TM_9b9bytt1stv9cZ8uqII7HFgew_4];
TM_9b9bytt1stv9cZ8uqII7HFgew_2[TM_9b9bytt1stv9cZ8uqII7HFgew_4] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_4+1];
}
TM_9b9bytt1stv9cZ8uqII7HFgew_0[8].len = 7; TM_9b9bytt1stv9cZ8uqII7HFgew_0[8].kind = 2; TM_9b9bytt1stv9cZ8uqII7HFgew_0[8].sons = &TM_9b9bytt1stv9cZ8uqII7HFgew_2[0];
NTI_RUngo7nCHe6O8aBGIcrhtg_.node = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[8];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[0].kind = 3;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[0].offset = offsetof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q, kind);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[0].typ = (&NTI_RUngo7nCHe6O8aBGIcrhtg_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[0].name = "kind";
TM_9b9bytt1stv9cZ8uqII7HFgew_0[0].sons = &NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[0];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[0].len = 7;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[9].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[9].offset = offsetof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q, kindU.S1.str);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[9].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[9].name = "str";
NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[4] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[9];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[10].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[10].offset = offsetof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q, kindU.S2.num);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[10].typ = (&NTI_Aav8dQoMlCFnZRxA0IhTHQ_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[10].name = "num";
NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[2] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[10];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[11].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[11].offset = offsetof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q, kindU.S3.fnum);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[11].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[11].name = "fnum";
NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[3] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[11];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[12].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[12].offset = offsetof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q, kindU.S4.bval);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[12].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[12].name = "bval";
NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[1] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[12];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[13].len = 0; TM_9b9bytt1stv9cZ8uqII7HFgew_0[13].kind = 2;
NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[0] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[13];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[14].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[14].offset = offsetof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q, kindU.S6.fields);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[14].typ = (&NTI_AF39bJ7XDr6gpANuGpxkHrw_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[14].name = "fields";
NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[5] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[14];
NTI_oLpBKXzW3hF9aCVMo5EymfQ_.size = sizeof(tySequence_oLpBKXzW3hF9aCVMo5EymfQ*);
NTI_oLpBKXzW3hF9aCVMo5EymfQ_.kind = 24;
NTI_oLpBKXzW3hF9aCVMo5EymfQ_.base = (&NTI_zfzzuQ8txrdZAYK0WGWpHg_);
NTI_oLpBKXzW3hF9aCVMo5EymfQ_.flags = 2;
NTI_oLpBKXzW3hF9aCVMo5EymfQ_.marker = Marker_tySequence_oLpBKXzW3hF9aCVMo5EymfQ;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[15].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[15].offset = offsetof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q, kindU.S7.elems);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[15].typ = (&NTI_oLpBKXzW3hF9aCVMo5EymfQ_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[15].name = "elems";
NimDT__df9bshXB7C9cTiWPIOtX3j1Q_kind[6] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[15];
NTI_df9bshXB7C9cTiWPIOtX3j1Q_.node = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[0];
NTI_zfzzuQ8txrdZAYK0WGWpHg_.size = sizeof(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*);
NTI_zfzzuQ8txrdZAYK0WGWpHg_.kind = 22;
NTI_zfzzuQ8txrdZAYK0WGWpHg_.base = (&NTI_df9bshXB7C9cTiWPIOtX3j1Q_);
NTI_zfzzuQ8txrdZAYK0WGWpHg_.flags = 2;
NTI_zfzzuQ8txrdZAYK0WGWpHg_.marker = Marker_tyRef_zfzzuQ8txrdZAYK0WGWpHg;
NTI_TAl5cv6tbH9avL9cKfMc0hkQ_.size = sizeof(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ);
NTI_TAl5cv6tbH9avL9cKfMc0hkQ_.kind = 17;
NTI_TAl5cv6tbH9avL9cKfMc0hkQ_.base = (&NTI_B6cGbTPhMsqMovc9cOcIHRw_);
TM_9b9bytt1stv9cZ8uqII7HFgew_5[0] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[17];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[17].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[17].offset = offsetof(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ, a);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[17].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[17].name = "a";
TM_9b9bytt1stv9cZ8uqII7HFgew_5[1] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[18];
NTI_vfEI6XZ7Xkb5BV9c6202vjA_.size = sizeof(tyEnum_TokKind_vfEI6XZ7Xkb5BV9c6202vjA);
NTI_vfEI6XZ7Xkb5BV9c6202vjA_.kind = 14;
NTI_vfEI6XZ7Xkb5BV9c6202vjA_.base = 0;
NTI_vfEI6XZ7Xkb5BV9c6202vjA_.flags = 3;
for (TM_9b9bytt1stv9cZ8uqII7HFgew_8 = 0; TM_9b9bytt1stv9cZ8uqII7HFgew_8 < 14; TM_9b9bytt1stv9cZ8uqII7HFgew_8++) {
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_8+19].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_8+19].offset = TM_9b9bytt1stv9cZ8uqII7HFgew_8;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_8+19].name = TM_9b9bytt1stv9cZ8uqII7HFgew_7[TM_9b9bytt1stv9cZ8uqII7HFgew_8];
TM_9b9bytt1stv9cZ8uqII7HFgew_6[TM_9b9bytt1stv9cZ8uqII7HFgew_8] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_8+19];
}
TM_9b9bytt1stv9cZ8uqII7HFgew_0[33].len = 14; TM_9b9bytt1stv9cZ8uqII7HFgew_0[33].kind = 2; TM_9b9bytt1stv9cZ8uqII7HFgew_0[33].sons = &TM_9b9bytt1stv9cZ8uqII7HFgew_6[0];
NTI_vfEI6XZ7Xkb5BV9c6202vjA_.node = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[33];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[18].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[18].offset = offsetof(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ, tok);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[18].typ = (&NTI_vfEI6XZ7Xkb5BV9c6202vjA_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[18].name = "tok";
TM_9b9bytt1stv9cZ8uqII7HFgew_5[2] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[34];
NTI_NdAkGi88owzfBOSBDfW49cQ_.size = sizeof(tyEnum_JsonEventKind_NdAkGi88owzfBOSBDfW49cQ);
NTI_NdAkGi88owzfBOSBDfW49cQ_.kind = 14;
NTI_NdAkGi88owzfBOSBDfW49cQ_.base = 0;
NTI_NdAkGi88owzfBOSBDfW49cQ_.flags = 3;
for (TM_9b9bytt1stv9cZ8uqII7HFgew_11 = 0; TM_9b9bytt1stv9cZ8uqII7HFgew_11 < 12; TM_9b9bytt1stv9cZ8uqII7HFgew_11++) {
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_11+35].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_11+35].offset = TM_9b9bytt1stv9cZ8uqII7HFgew_11;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_11+35].name = TM_9b9bytt1stv9cZ8uqII7HFgew_10[TM_9b9bytt1stv9cZ8uqII7HFgew_11];
TM_9b9bytt1stv9cZ8uqII7HFgew_9[TM_9b9bytt1stv9cZ8uqII7HFgew_11] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_11+35];
}
TM_9b9bytt1stv9cZ8uqII7HFgew_0[47].len = 12; TM_9b9bytt1stv9cZ8uqII7HFgew_0[47].kind = 2; TM_9b9bytt1stv9cZ8uqII7HFgew_0[47].sons = &TM_9b9bytt1stv9cZ8uqII7HFgew_9[0];
NTI_NdAkGi88owzfBOSBDfW49cQ_.node = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[47];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[34].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[34].offset = offsetof(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ, kind);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[34].typ = (&NTI_NdAkGi88owzfBOSBDfW49cQ_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[34].name = "kind";
TM_9b9bytt1stv9cZ8uqII7HFgew_5[3] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[48];
NTI_rhaSH4AjHj9bXRijCvdqRhQ_.size = sizeof(tyEnum_JsonError_rhaSH4AjHj9bXRijCvdqRhQ);
NTI_rhaSH4AjHj9bXRijCvdqRhQ_.kind = 14;
NTI_rhaSH4AjHj9bXRijCvdqRhQ_.base = 0;
NTI_rhaSH4AjHj9bXRijCvdqRhQ_.flags = 3;
for (TM_9b9bytt1stv9cZ8uqII7HFgew_14 = 0; TM_9b9bytt1stv9cZ8uqII7HFgew_14 < 11; TM_9b9bytt1stv9cZ8uqII7HFgew_14++) {
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_14+49].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_14+49].offset = TM_9b9bytt1stv9cZ8uqII7HFgew_14;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_14+49].name = TM_9b9bytt1stv9cZ8uqII7HFgew_13[TM_9b9bytt1stv9cZ8uqII7HFgew_14];
TM_9b9bytt1stv9cZ8uqII7HFgew_12[TM_9b9bytt1stv9cZ8uqII7HFgew_14] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_14+49];
}
TM_9b9bytt1stv9cZ8uqII7HFgew_0[60].len = 11; TM_9b9bytt1stv9cZ8uqII7HFgew_0[60].kind = 2; TM_9b9bytt1stv9cZ8uqII7HFgew_0[60].sons = &TM_9b9bytt1stv9cZ8uqII7HFgew_12[0];
NTI_rhaSH4AjHj9bXRijCvdqRhQ_.node = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[60];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[48].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[48].offset = offsetof(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ, err);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[48].typ = (&NTI_rhaSH4AjHj9bXRijCvdqRhQ_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[48].name = "err";
TM_9b9bytt1stv9cZ8uqII7HFgew_5[4] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[61];
NTI_UzfeQnJimUtC9bt1BjDzcdQ_.size = sizeof(tyEnum_ParserState_UzfeQnJimUtC9bt1BjDzcdQ);
NTI_UzfeQnJimUtC9bt1BjDzcdQ_.kind = 14;
NTI_UzfeQnJimUtC9bt1BjDzcdQ_.base = 0;
NTI_UzfeQnJimUtC9bt1BjDzcdQ_.flags = 3;
for (TM_9b9bytt1stv9cZ8uqII7HFgew_17 = 0; TM_9b9bytt1stv9cZ8uqII7HFgew_17 < 8; TM_9b9bytt1stv9cZ8uqII7HFgew_17++) {
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_17+62].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_17+62].offset = TM_9b9bytt1stv9cZ8uqII7HFgew_17;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_17+62].name = TM_9b9bytt1stv9cZ8uqII7HFgew_16[TM_9b9bytt1stv9cZ8uqII7HFgew_17];
TM_9b9bytt1stv9cZ8uqII7HFgew_15[TM_9b9bytt1stv9cZ8uqII7HFgew_17] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[TM_9b9bytt1stv9cZ8uqII7HFgew_17+62];
}
TM_9b9bytt1stv9cZ8uqII7HFgew_0[70].len = 8; TM_9b9bytt1stv9cZ8uqII7HFgew_0[70].kind = 2; TM_9b9bytt1stv9cZ8uqII7HFgew_0[70].sons = &TM_9b9bytt1stv9cZ8uqII7HFgew_15[0];
NTI_UzfeQnJimUtC9bt1BjDzcdQ_.node = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[70];
NTI_ArNCLAPkQjwz7DrguhEHNA_.size = sizeof(tySequence_ArNCLAPkQjwz7DrguhEHNA*);
NTI_ArNCLAPkQjwz7DrguhEHNA_.kind = 24;
NTI_ArNCLAPkQjwz7DrguhEHNA_.base = (&NTI_UzfeQnJimUtC9bt1BjDzcdQ_);
NTI_ArNCLAPkQjwz7DrguhEHNA_.flags = 2;
NTI_ArNCLAPkQjwz7DrguhEHNA_.marker = Marker_tySequence_ArNCLAPkQjwz7DrguhEHNA;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[61].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[61].offset = offsetof(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ, state);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[61].typ = (&NTI_ArNCLAPkQjwz7DrguhEHNA_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[61].name = "state";
TM_9b9bytt1stv9cZ8uqII7HFgew_5[5] = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[71];
TM_9b9bytt1stv9cZ8uqII7HFgew_0[71].kind = 1;
TM_9b9bytt1stv9cZ8uqII7HFgew_0[71].offset = offsetof(tyObject_JsonParser_TAl5cv6tbH9avL9cKfMc0hkQ, filename);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[71].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[71].name = "filename";
TM_9b9bytt1stv9cZ8uqII7HFgew_0[16].len = 6; TM_9b9bytt1stv9cZ8uqII7HFgew_0[16].kind = 2; TM_9b9bytt1stv9cZ8uqII7HFgew_0[16].sons = &TM_9b9bytt1stv9cZ8uqII7HFgew_5[0];
NTI_TAl5cv6tbH9avL9cKfMc0hkQ_.node = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[16];
NTI_4avqtqpbmyD9bxH9bUmO9b0yw_.size = sizeof(tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw);
NTI_4avqtqpbmyD9bxH9bUmO9b0yw_.kind = 17;
NTI_4avqtqpbmyD9bxH9bUmO9b0yw_.base = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
TM_9b9bytt1stv9cZ8uqII7HFgew_0[72].len = 0; TM_9b9bytt1stv9cZ8uqII7HFgew_0[72].kind = 2;
NTI_4avqtqpbmyD9bxH9bUmO9b0yw_.node = &TM_9b9bytt1stv9cZ8uqII7HFgew_0[72];
NTI_TOl9bBVGahlQmjZBc3UGISg_.size = sizeof(tyObject_JsonParsingError_4avqtqpbmyD9bxH9bUmO9b0yw*);
NTI_TOl9bBVGahlQmjZBc3UGISg_.kind = 22;
NTI_TOl9bBVGahlQmjZBc3UGISg_.base = (&NTI_4avqtqpbmyD9bxH9bUmO9b0yw_);
NTI_TOl9bBVGahlQmjZBc3UGISg_.marker = Marker_tyRef_TOl9bBVGahlQmjZBc3UGISg;
}

